// Copyright 2026 Chaser-Oxide Server
// Browser lifecycle management service

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: browser.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrowserService_Launch_FullMethodName     = "/chaser.oxide.v1.BrowserService/Launch"
	BrowserService_GetPages_FullMethodName   = "/chaser.oxide.v1.BrowserService/GetPages"
	BrowserService_Close_FullMethodName      = "/chaser.oxide.v1.BrowserService/Close"
	BrowserService_GetVersion_FullMethodName = "/chaser.oxide.v1.BrowserService/GetVersion"
	BrowserService_GetStatus_FullMethodName  = "/chaser.oxide.v1.BrowserService/GetStatus"
	BrowserService_ConnectTo_FullMethodName  = "/chaser.oxide.v1.BrowserService/ConnectTo"
)

// BrowserServiceClient is the client API for BrowserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============= BrowserService =============
// Manages browser instance lifecycle
type BrowserServiceClient interface {
	// Launch a new browser instance
	// Returns a browser_id that should be used for all subsequent operations
	Launch(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error)
	// Get all pages/tabs for a browser
	GetPages(ctx context.Context, in *GetPagesRequest, opts ...grpc.CallOption) (*GetPagesResponse, error)
	// Close a browser instance and all its pages
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	// Get browser version information
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// Get browser status and health
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Connect to an existing browser instance
	ConnectTo(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
}

type browserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserServiceClient(cc grpc.ClientConnInterface) BrowserServiceClient {
	return &browserServiceClient{cc}
}

func (c *browserServiceClient) Launch(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchResponse)
	err := c.cc.Invoke(ctx, BrowserService_Launch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) GetPages(ctx context.Context, in *GetPagesRequest, opts ...grpc.CallOption) (*GetPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPagesResponse)
	err := c.cc.Invoke(ctx, BrowserService_GetPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, BrowserService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, BrowserService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, BrowserService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browserServiceClient) ConnectTo(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, BrowserService_ConnectTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowserServiceServer is the server API for BrowserService service.
// All implementations must embed UnimplementedBrowserServiceServer
// for forward compatibility.
//
// ============= BrowserService =============
// Manages browser instance lifecycle
type BrowserServiceServer interface {
	// Launch a new browser instance
	// Returns a browser_id that should be used for all subsequent operations
	Launch(context.Context, *LaunchRequest) (*LaunchResponse, error)
	// Get all pages/tabs for a browser
	GetPages(context.Context, *GetPagesRequest) (*GetPagesResponse, error)
	// Close a browser instance and all its pages
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	// Get browser version information
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// Get browser status and health
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Connect to an existing browser instance
	ConnectTo(context.Context, *ConnectRequest) (*ConnectResponse, error)
	mustEmbedUnimplementedBrowserServiceServer()
}

// UnimplementedBrowserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserServiceServer struct{}

func (UnimplementedBrowserServiceServer) Launch(context.Context, *LaunchRequest) (*LaunchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Launch not implemented")
}
func (UnimplementedBrowserServiceServer) GetPages(context.Context, *GetPagesRequest) (*GetPagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPages not implemented")
}
func (UnimplementedBrowserServiceServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedBrowserServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedBrowserServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedBrowserServiceServer) ConnectTo(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectTo not implemented")
}
func (UnimplementedBrowserServiceServer) mustEmbedUnimplementedBrowserServiceServer() {}
func (UnimplementedBrowserServiceServer) testEmbeddedByValue()                        {}

// UnsafeBrowserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserServiceServer will
// result in compilation errors.
type UnsafeBrowserServiceServer interface {
	mustEmbedUnimplementedBrowserServiceServer()
}

func RegisterBrowserServiceServer(s grpc.ServiceRegistrar, srv BrowserServiceServer) {
	// If the following call panics, it indicates UnimplementedBrowserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrowserService_ServiceDesc, srv)
}

func _BrowserService_Launch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Launch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Launch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Launch(ctx, req.(*LaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_GetPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).GetPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_GetPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).GetPages(ctx, req.(*GetPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowserService_ConnectTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowserServiceServer).ConnectTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowserService_ConnectTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowserServiceServer).ConnectTo(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrowserService_ServiceDesc is the grpc.ServiceDesc for BrowserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrowserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chaser.oxide.v1.BrowserService",
	HandlerType: (*BrowserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Launch",
			Handler:    _BrowserService_Launch_Handler,
		},
		{
			MethodName: "GetPages",
			Handler:    _BrowserService_GetPages_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _BrowserService_Close_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _BrowserService_GetVersion_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _BrowserService_GetStatus_Handler,
		},
		{
			MethodName: "ConnectTo",
			Handler:    _BrowserService_ConnectTo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "browser.proto",
}
