// Copyright 2026 Chaser-Oxide Server
// Common types and error definitions for the gRPC API

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error codes for API responses
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNKNOWN             ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT    ErrorCode = 1  // Invalid request parameters
	ErrorCode_ERROR_CODE_NOT_FOUND           ErrorCode = 2  // Resource not found
	ErrorCode_ERROR_CODE_ALREADY_EXISTS      ErrorCode = 3  // Resource already exists
	ErrorCode_ERROR_CODE_PERMISSION_DENIED   ErrorCode = 4  // Permission denied
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED  ErrorCode = 5  // Resource limit reached
	ErrorCode_ERROR_CODE_FAILED_PRECONDITION ErrorCode = 6  // Precondition failed
	ErrorCode_ERROR_CODE_ABORTED             ErrorCode = 7  // Operation aborted
	ErrorCode_ERROR_CODE_OUT_OF_RANGE        ErrorCode = 8  // Value out of range
	ErrorCode_ERROR_CODE_INTERNAL            ErrorCode = 9  // Internal server error
	ErrorCode_ERROR_CODE_BROWSER_CLOSED      ErrorCode = 10 // Browser is closed
	ErrorCode_ERROR_CODE_PAGE_CLOSED         ErrorCode = 11 // Page is closed
	ErrorCode_ERROR_CODE_ELEMENT_NOT_FOUND   ErrorCode = 12 // DOM element not found
	ErrorCode_ERROR_CODE_NAVIGATION_FAILED   ErrorCode = 13 // Navigation failed
	ErrorCode_ERROR_CODE_TIMEOUT             ErrorCode = 14 // Operation timeout
	ErrorCode_ERROR_CODE_EVALUATION_FAILED   ErrorCode = 15 // JavaScript evaluation failed
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNKNOWN",
		1:  "ERROR_CODE_INVALID_ARGUMENT",
		2:  "ERROR_CODE_NOT_FOUND",
		3:  "ERROR_CODE_ALREADY_EXISTS",
		4:  "ERROR_CODE_PERMISSION_DENIED",
		5:  "ERROR_CODE_RESOURCE_EXHAUSTED",
		6:  "ERROR_CODE_FAILED_PRECONDITION",
		7:  "ERROR_CODE_ABORTED",
		8:  "ERROR_CODE_OUT_OF_RANGE",
		9:  "ERROR_CODE_INTERNAL",
		10: "ERROR_CODE_BROWSER_CLOSED",
		11: "ERROR_CODE_PAGE_CLOSED",
		12: "ERROR_CODE_ELEMENT_NOT_FOUND",
		13: "ERROR_CODE_NAVIGATION_FAILED",
		14: "ERROR_CODE_TIMEOUT",
		15: "ERROR_CODE_EVALUATION_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNKNOWN":             0,
		"ERROR_CODE_INVALID_ARGUMENT":    1,
		"ERROR_CODE_NOT_FOUND":           2,
		"ERROR_CODE_ALREADY_EXISTS":      3,
		"ERROR_CODE_PERMISSION_DENIED":   4,
		"ERROR_CODE_RESOURCE_EXHAUSTED":  5,
		"ERROR_CODE_FAILED_PRECONDITION": 6,
		"ERROR_CODE_ABORTED":             7,
		"ERROR_CODE_OUT_OF_RANGE":        8,
		"ERROR_CODE_INTERNAL":            9,
		"ERROR_CODE_BROWSER_CLOSED":      10,
		"ERROR_CODE_PAGE_CLOSED":         11,
		"ERROR_CODE_ELEMENT_NOT_FOUND":   12,
		"ERROR_CODE_NAVIGATION_FAILED":   13,
		"ERROR_CODE_TIMEOUT":             14,
		"ERROR_CODE_EVALUATION_FAILED":   15,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Element selector types
type SelectorType int32

const (
	SelectorType_SELECTOR_TYPE_UNSPECIFIED SelectorType = 0
	SelectorType_SELECTOR_TYPE_CSS         SelectorType = 1 // CSS selector
	SelectorType_SELECTOR_TYPE_XPATH       SelectorType = 2 // XPath expression
	SelectorType_SELECTOR_TYPE_TEXT        SelectorType = 3 // Text content
	SelectorType_SELECTOR_TYPE_ARIA        SelectorType = 4 // ARIA label/role
)

// Enum value maps for SelectorType.
var (
	SelectorType_name = map[int32]string{
		0: "SELECTOR_TYPE_UNSPECIFIED",
		1: "SELECTOR_TYPE_CSS",
		2: "SELECTOR_TYPE_XPATH",
		3: "SELECTOR_TYPE_TEXT",
		4: "SELECTOR_TYPE_ARIA",
	}
	SelectorType_value = map[string]int32{
		"SELECTOR_TYPE_UNSPECIFIED": 0,
		"SELECTOR_TYPE_CSS":         1,
		"SELECTOR_TYPE_XPATH":       2,
		"SELECTOR_TYPE_TEXT":        3,
		"SELECTOR_TYPE_ARIA":        4,
	}
)

func (x SelectorType) Enum() *SelectorType {
	p := new(SelectorType)
	*p = x
	return p
}

func (x SelectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (SelectorType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x SelectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectorType.Descriptor instead.
func (SelectorType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// Element position for mouse interaction
type ElementPosition int32

const (
	ElementPosition_ELEMENT_POSITION_UNSPECIFIED  ElementPosition = 0
	ElementPosition_ELEMENT_POSITION_CENTER       ElementPosition = 1 // Click center of element
	ElementPosition_ELEMENT_POSITION_TOP_LEFT     ElementPosition = 2
	ElementPosition_ELEMENT_POSITION_TOP_RIGHT    ElementPosition = 3
	ElementPosition_ELEMENT_POSITION_BOTTOM_LEFT  ElementPosition = 4
	ElementPosition_ELEMENT_POSITION_BOTTOM_RIGHT ElementPosition = 5
	ElementPosition_ELEMENT_POSITION_RANDOM       ElementPosition = 6 // Random position within element
)

// Enum value maps for ElementPosition.
var (
	ElementPosition_name = map[int32]string{
		0: "ELEMENT_POSITION_UNSPECIFIED",
		1: "ELEMENT_POSITION_CENTER",
		2: "ELEMENT_POSITION_TOP_LEFT",
		3: "ELEMENT_POSITION_TOP_RIGHT",
		4: "ELEMENT_POSITION_BOTTOM_LEFT",
		5: "ELEMENT_POSITION_BOTTOM_RIGHT",
		6: "ELEMENT_POSITION_RANDOM",
	}
	ElementPosition_value = map[string]int32{
		"ELEMENT_POSITION_UNSPECIFIED":  0,
		"ELEMENT_POSITION_CENTER":       1,
		"ELEMENT_POSITION_TOP_LEFT":     2,
		"ELEMENT_POSITION_TOP_RIGHT":    3,
		"ELEMENT_POSITION_BOTTOM_LEFT":  4,
		"ELEMENT_POSITION_BOTTOM_RIGHT": 5,
		"ELEMENT_POSITION_RANDOM":       6,
	}
)

func (x ElementPosition) Enum() *ElementPosition {
	p := new(ElementPosition)
	*p = x
	return p
}

func (x ElementPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (ElementPosition) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x ElementPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementPosition.Descriptor instead.
func (ElementPosition) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// Mouse button types
type MouseButton int32

const (
	MouseButton_MOUSE_BUTTON_UNSPECIFIED MouseButton = 0
	MouseButton_MOUSE_BUTTON_LEFT        MouseButton = 1
	MouseButton_MOUSE_BUTTON_MIDDLE      MouseButton = 2
	MouseButton_MOUSE_BUTTON_RIGHT       MouseButton = 3
	MouseButton_MOUSE_BUTTON_BACK        MouseButton = 4
	MouseButton_MOUSE_BUTTON_FORWARD     MouseButton = 5
)

// Enum value maps for MouseButton.
var (
	MouseButton_name = map[int32]string{
		0: "MOUSE_BUTTON_UNSPECIFIED",
		1: "MOUSE_BUTTON_LEFT",
		2: "MOUSE_BUTTON_MIDDLE",
		3: "MOUSE_BUTTON_RIGHT",
		4: "MOUSE_BUTTON_BACK",
		5: "MOUSE_BUTTON_FORWARD",
	}
	MouseButton_value = map[string]int32{
		"MOUSE_BUTTON_UNSPECIFIED": 0,
		"MOUSE_BUTTON_LEFT":        1,
		"MOUSE_BUTTON_MIDDLE":      2,
		"MOUSE_BUTTON_RIGHT":       3,
		"MOUSE_BUTTON_BACK":        4,
		"MOUSE_BUTTON_FORWARD":     5,
	}
)

func (x MouseButton) Enum() *MouseButton {
	p := new(MouseButton)
	*p = x
	return p
}

func (x MouseButton) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MouseButton) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (MouseButton) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x MouseButton) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MouseButton.Descriptor instead.
func (MouseButton) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

// Keyboard modifier keys
type KeyModifier int32

const (
	KeyModifier_KEY_MODIFIER_UNSPECIFIED     KeyModifier = 0
	KeyModifier_KEY_MODIFIER_ALT             KeyModifier = 1
	KeyModifier_KEY_MODIFIER_CONTROL         KeyModifier = 2
	KeyModifier_KEY_MODIFIER_CONTROL_OR_META KeyModifier = 3 // Control on Windows/Linux, Meta on Mac
	KeyModifier_KEY_MODIFIER_META            KeyModifier = 4
	KeyModifier_KEY_MODIFIER_SHIFT           KeyModifier = 5
)

// Enum value maps for KeyModifier.
var (
	KeyModifier_name = map[int32]string{
		0: "KEY_MODIFIER_UNSPECIFIED",
		1: "KEY_MODIFIER_ALT",
		2: "KEY_MODIFIER_CONTROL",
		3: "KEY_MODIFIER_CONTROL_OR_META",
		4: "KEY_MODIFIER_META",
		5: "KEY_MODIFIER_SHIFT",
	}
	KeyModifier_value = map[string]int32{
		"KEY_MODIFIER_UNSPECIFIED":     0,
		"KEY_MODIFIER_ALT":             1,
		"KEY_MODIFIER_CONTROL":         2,
		"KEY_MODIFIER_CONTROL_OR_META": 3,
		"KEY_MODIFIER_META":            4,
		"KEY_MODIFIER_SHIFT":           5,
	}
)

func (x KeyModifier) Enum() *KeyModifier {
	p := new(KeyModifier)
	*p = x
	return p
}

func (x KeyModifier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyModifier) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (KeyModifier) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x KeyModifier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyModifier.Descriptor instead.
func (KeyModifier) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

// Wait until specific condition
type NavigationOptions_LoadState int32

const (
	NavigationOptions_LOAD_STATE_UNSPECIFIED         NavigationOptions_LoadState = 0
	NavigationOptions_LOAD_STATE_LOAD                NavigationOptions_LoadState = 1 // Wait for 'load' event
	NavigationOptions_LOAD_STATE_DOM_CONTENT_LOADED  NavigationOptions_LoadState = 2 // Wait for 'DOMContentLoaded'
	NavigationOptions_LOAD_STATE_NETWORK_IDLE        NavigationOptions_LoadState = 3 // Wait for network to be idle
	NavigationOptions_LOAD_STATE_NETWORK_ALMOST_IDLE NavigationOptions_LoadState = 4 // Wait for network to be almost idle
)

// Enum value maps for NavigationOptions_LoadState.
var (
	NavigationOptions_LoadState_name = map[int32]string{
		0: "LOAD_STATE_UNSPECIFIED",
		1: "LOAD_STATE_LOAD",
		2: "LOAD_STATE_DOM_CONTENT_LOADED",
		3: "LOAD_STATE_NETWORK_IDLE",
		4: "LOAD_STATE_NETWORK_ALMOST_IDLE",
	}
	NavigationOptions_LoadState_value = map[string]int32{
		"LOAD_STATE_UNSPECIFIED":         0,
		"LOAD_STATE_LOAD":                1,
		"LOAD_STATE_DOM_CONTENT_LOADED":  2,
		"LOAD_STATE_NETWORK_IDLE":        3,
		"LOAD_STATE_NETWORK_ALMOST_IDLE": 4,
	}
)

func (x NavigationOptions_LoadState) Enum() *NavigationOptions_LoadState {
	p := new(NavigationOptions_LoadState)
	*p = x
	return p
}

func (x NavigationOptions_LoadState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NavigationOptions_LoadState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[5].Descriptor()
}

func (NavigationOptions_LoadState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[5]
}

func (x NavigationOptions_LoadState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NavigationOptions_LoadState.Descriptor instead.
func (NavigationOptions_LoadState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5, 0}
}

// Screenshot format
type ScreenshotOptions_Format int32

const (
	ScreenshotOptions_FORMAT_UNSPECIFIED ScreenshotOptions_Format = 0
	ScreenshotOptions_FORMAT_PNG         ScreenshotOptions_Format = 1
	ScreenshotOptions_FORMAT_JPEG        ScreenshotOptions_Format = 2
	ScreenshotOptions_FORMAT_WEBP        ScreenshotOptions_Format = 3
)

// Enum value maps for ScreenshotOptions_Format.
var (
	ScreenshotOptions_Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_PNG",
		2: "FORMAT_JPEG",
		3: "FORMAT_WEBP",
	}
	ScreenshotOptions_Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_PNG":         1,
		"FORMAT_JPEG":        2,
		"FORMAT_WEBP":        3,
	}
)

func (x ScreenshotOptions_Format) Enum() *ScreenshotOptions_Format {
	p := new(ScreenshotOptions_Format)
	*p = x
	return p
}

func (x ScreenshotOptions_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScreenshotOptions_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[6].Descriptor()
}

func (ScreenshotOptions_Format) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[6]
}

func (x ScreenshotOptions_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScreenshotOptions_Format.Descriptor instead.
func (ScreenshotOptions_Format) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6, 0}
}

// Empty message for requests with no parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Session identifiers for multi-tenancy
type SessionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowserId     string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"` // Browser instance UUID
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`          // Page/tab UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionID) Reset() {
	*x = SessionID{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionID) ProtoMessage() {}

func (x *SessionID) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionID.ProtoReflect.Descriptor instead.
func (*SessionID) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *SessionID) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *SessionID) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

// Standard error response
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=chaser.oxide.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNKNOWN
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Browser launch options
type BrowserOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to Chrome/Chromium executable
	ExecutablePath string `protobuf:"bytes,1,opt,name=executable_path,json=executablePath,proto3" json:"executable_path,omitempty"`
	// Additional command line arguments
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Headless mode (no visible UI)
	Headless bool `protobuf:"varint,3,opt,name=headless,proto3" json:"headless,omitempty"`
	// Browser window dimensions
	WindowWidth  int32 `protobuf:"varint,4,opt,name=window_width,json=windowWidth,proto3" json:"window_width,omitempty"`
	WindowHeight int32 `protobuf:"varint,5,opt,name=window_height,json=windowHeight,proto3" json:"window_height,omitempty"`
	// User data directory for persistent session
	UserDataDir string `protobuf:"bytes,6,opt,name=user_data_dir,json=userDataDir,proto3" json:"user_data_dir,omitempty"`
	// Proxy configuration
	ProxyServer     string `protobuf:"bytes,7,opt,name=proxy_server,json=proxyServer,proto3" json:"proxy_server,omitempty"`
	ProxyBypassList string `protobuf:"bytes,8,opt,name=proxy_bypass_list,json=proxyBypassList,proto3" json:"proxy_bypass_list,omitempty"`
	// Disable web security
	DisableWebSecurity bool `protobuf:"varint,9,opt,name=disable_web_security,json=disableWebSecurity,proto3" json:"disable_web_security,omitempty"`
	// Ignore certificate errors
	IgnoreCertificateErrors bool `protobuf:"varint,10,opt,name=ignore_certificate_errors,json=ignoreCertificateErrors,proto3" json:"ignore_certificate_errors,omitempty"`
	// Disable GPU acceleration
	DisableGpu bool `protobuf:"varint,11,opt,name=disable_gpu,json=disableGpu,proto3" json:"disable_gpu,omitempty"`
	// Disable extensions
	DisableExtensions bool `protobuf:"varint,12,opt,name=disable_extensions,json=disableExtensions,proto3" json:"disable_extensions,omitempty"`
	// Enable devtools
	EnableDevtools bool `protobuf:"varint,13,opt,name=enable_devtools,json=enableDevtools,proto3" json:"enable_devtools,omitempty"`
	// User agent override
	UserAgent string `protobuf:"bytes,14,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Language
	Lang string `protobuf:"bytes,15,opt,name=lang,proto3" json:"lang,omitempty"`
	// Timezone
	Timezone      string `protobuf:"bytes,16,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserOptions) Reset() {
	*x = BrowserOptions{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserOptions) ProtoMessage() {}

func (x *BrowserOptions) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserOptions.ProtoReflect.Descriptor instead.
func (*BrowserOptions) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *BrowserOptions) GetExecutablePath() string {
	if x != nil {
		return x.ExecutablePath
	}
	return ""
}

func (x *BrowserOptions) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *BrowserOptions) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

func (x *BrowserOptions) GetWindowWidth() int32 {
	if x != nil {
		return x.WindowWidth
	}
	return 0
}

func (x *BrowserOptions) GetWindowHeight() int32 {
	if x != nil {
		return x.WindowHeight
	}
	return 0
}

func (x *BrowserOptions) GetUserDataDir() string {
	if x != nil {
		return x.UserDataDir
	}
	return ""
}

func (x *BrowserOptions) GetProxyServer() string {
	if x != nil {
		return x.ProxyServer
	}
	return ""
}

func (x *BrowserOptions) GetProxyBypassList() string {
	if x != nil {
		return x.ProxyBypassList
	}
	return ""
}

func (x *BrowserOptions) GetDisableWebSecurity() bool {
	if x != nil {
		return x.DisableWebSecurity
	}
	return false
}

func (x *BrowserOptions) GetIgnoreCertificateErrors() bool {
	if x != nil {
		return x.IgnoreCertificateErrors
	}
	return false
}

func (x *BrowserOptions) GetDisableGpu() bool {
	if x != nil {
		return x.DisableGpu
	}
	return false
}

func (x *BrowserOptions) GetDisableExtensions() bool {
	if x != nil {
		return x.DisableExtensions
	}
	return false
}

func (x *BrowserOptions) GetEnableDevtools() bool {
	if x != nil {
		return x.EnableDevtools
	}
	return false
}

func (x *BrowserOptions) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *BrowserOptions) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *BrowserOptions) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// Browser process information
type BrowserInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BrowserId      string                 `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	ExecutablePath string                 `protobuf:"bytes,2,opt,name=executable_path,json=executablePath,proto3" json:"executable_path,omitempty"`
	Pid            int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"` // Process ID
	Headless       bool                   `protobuf:"varint,4,opt,name=headless,proto3" json:"headless,omitempty"`
	UserAgent      string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	LaunchedAt     int64                  `protobuf:"varint,6,opt,name=launched_at,json=launchedAt,proto3" json:"launched_at,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BrowserInfo) Reset() {
	*x = BrowserInfo{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserInfo) ProtoMessage() {}

func (x *BrowserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserInfo.ProtoReflect.Descriptor instead.
func (*BrowserInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *BrowserInfo) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *BrowserInfo) GetExecutablePath() string {
	if x != nil {
		return x.ExecutablePath
	}
	return ""
}

func (x *BrowserInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *BrowserInfo) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

func (x *BrowserInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *BrowserInfo) GetLaunchedAt() int64 {
	if x != nil {
		return x.LaunchedAt
	}
	return 0
}

// Page navigation options
type NavigationOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum navigation timeout in milliseconds
	Timeout   int32                       `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	WaitUntil NavigationOptions_LoadState `protobuf:"varint,2,opt,name=wait_until,json=waitUntil,proto3,enum=chaser.oxide.v1.NavigationOptions_LoadState" json:"wait_until,omitempty"`
	// Referer header
	Referer       string `protobuf:"bytes,3,opt,name=referer,proto3" json:"referer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationOptions) Reset() {
	*x = NavigationOptions{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationOptions) ProtoMessage() {}

func (x *NavigationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationOptions.ProtoReflect.Descriptor instead.
func (*NavigationOptions) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *NavigationOptions) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *NavigationOptions) GetWaitUntil() NavigationOptions_LoadState {
	if x != nil {
		return x.WaitUntil
	}
	return NavigationOptions_LOAD_STATE_UNSPECIFIED
}

func (x *NavigationOptions) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

// Page screenshot options
type ScreenshotOptions struct {
	state  protoimpl.MessageState   `protogen:"open.v1"`
	Format ScreenshotOptions_Format `protobuf:"varint,1,opt,name=format,proto3,enum=chaser.oxide.v1.ScreenshotOptions_Format" json:"format,omitempty"`
	// Quality for JPEG/WEBP (0-100)
	Quality int32 `protobuf:"varint,2,opt,name=quality,proto3" json:"quality,omitempty"`
	// Clip region
	Clip *Rectangle `protobuf:"bytes,3,opt,name=clip,proto3" json:"clip,omitempty"`
	// Capture full page (including scrollable content)
	FullPage bool `protobuf:"varint,4,opt,name=full_page,json=fullPage,proto3" json:"full_page,omitempty"`
	// Omit background (for transparent PNG)
	OmitBackground bool `protobuf:"varint,5,opt,name=omit_background,json=omitBackground,proto3" json:"omit_background,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScreenshotOptions) Reset() {
	*x = ScreenshotOptions{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotOptions) ProtoMessage() {}

func (x *ScreenshotOptions) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotOptions.ProtoReflect.Descriptor instead.
func (*ScreenshotOptions) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *ScreenshotOptions) GetFormat() ScreenshotOptions_Format {
	if x != nil {
		return x.Format
	}
	return ScreenshotOptions_FORMAT_UNSPECIFIED
}

func (x *ScreenshotOptions) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ScreenshotOptions) GetClip() *Rectangle {
	if x != nil {
		return x.Clip
	}
	return nil
}

func (x *ScreenshotOptions) GetFullPage() bool {
	if x != nil {
		return x.FullPage
	}
	return false
}

func (x *ScreenshotOptions) GetOmitBackground() bool {
	if x != nil {
		return x.OmitBackground
	}
	return false
}

// Rectangular region
type Rectangle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *Rectangle) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rectangle) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rectangle) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rectangle) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Page viewport settings
type Viewport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Width             int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height            int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	DeviceScaleFactor float64                `protobuf:"fixed64,3,opt,name=device_scale_factor,json=deviceScaleFactor,proto3" json:"device_scale_factor,omitempty"` // Default: 1.0
	Mobile            bool                   `protobuf:"varint,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	ScreenWidth       int32                  `protobuf:"varint,5,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight      int32                  `protobuf:"varint,6,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	PositionX         int32                  `protobuf:"varint,7,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY         int32                  `protobuf:"varint,8,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Viewport) Reset() {
	*x = Viewport{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Viewport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewport) ProtoMessage() {}

func (x *Viewport) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewport.ProtoReflect.Descriptor instead.
func (*Viewport) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *Viewport) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Viewport) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Viewport) GetDeviceScaleFactor() float64 {
	if x != nil {
		return x.DeviceScaleFactor
	}
	return 0
}

func (x *Viewport) GetMobile() bool {
	if x != nil {
		return x.Mobile
	}
	return false
}

func (x *Viewport) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *Viewport) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *Viewport) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *Viewport) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

// Element reference
type ElementRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	ElementId     string                 `protobuf:"bytes,2,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"` // Unique element identifier
	SelectorType  SelectorType           `protobuf:"varint,3,opt,name=selector_type,json=selectorType,proto3,enum=chaser.oxide.v1.SelectorType" json:"selector_type,omitempty"`
	Selector      string                 `protobuf:"bytes,4,opt,name=selector,proto3" json:"selector,omitempty"`
	Index         int32                  `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"` // For multiple matches
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementRef) Reset() {
	*x = ElementRef{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementRef) ProtoMessage() {}

func (x *ElementRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementRef.ProtoReflect.Descriptor instead.
func (*ElementRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *ElementRef) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ElementRef) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *ElementRef) GetSelectorType() SelectorType {
	if x != nil {
		return x.SelectorType
	}
	return SelectorType_SELECTOR_TYPE_UNSPECIFIED
}

func (x *ElementRef) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *ElementRef) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// JavaScript evaluation result
type EvaluationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*EvaluationResult_StringValue
	//	*EvaluationResult_IntValue
	//	*EvaluationResult_DoubleValue
	//	*EvaluationResult_BoolValue
	//	*EvaluationResult_BinaryValue
	//	*EvaluationResult_NullValue
	Response      isEvaluationResult_Response `protobuf_oneof:"response"`
	Type          string                      `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`                            // JavaScript type name
	ClassName     string                      `protobuf:"bytes,8,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"` // JavaScript class name (if object)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResult) Reset() {
	*x = EvaluationResult{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResult) ProtoMessage() {}

func (x *EvaluationResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResult.ProtoReflect.Descriptor instead.
func (*EvaluationResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *EvaluationResult) GetResponse() isEvaluationResult_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *EvaluationResult) GetStringValue() string {
	if x != nil {
		if x, ok := x.Response.(*EvaluationResult_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *EvaluationResult) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Response.(*EvaluationResult_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *EvaluationResult) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Response.(*EvaluationResult_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *EvaluationResult) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Response.(*EvaluationResult_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *EvaluationResult) GetBinaryValue() []byte {
	if x != nil {
		if x, ok := x.Response.(*EvaluationResult_BinaryValue); ok {
			return x.BinaryValue
		}
	}
	return nil
}

func (x *EvaluationResult) GetNullValue() *Value {
	if x != nil {
		if x, ok := x.Response.(*EvaluationResult_NullValue); ok {
			return x.NullValue
		}
	}
	return nil
}

func (x *EvaluationResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EvaluationResult) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type isEvaluationResult_Response interface {
	isEvaluationResult_Response()
}

type EvaluationResult_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type EvaluationResult_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type EvaluationResult_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type EvaluationResult_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type EvaluationResult_BinaryValue struct {
	BinaryValue []byte `protobuf:"bytes,5,opt,name=binary_value,json=binaryValue,proto3,oneof"` // For base64 encoded data
}

type EvaluationResult_NullValue struct {
	NullValue *Value `protobuf:"bytes,6,opt,name=null_value,json=nullValue,proto3,oneof"` // Explicit null
}

func (*EvaluationResult_StringValue) isEvaluationResult_Response() {}

func (*EvaluationResult_IntValue) isEvaluationResult_Response() {}

func (*EvaluationResult_DoubleValue) isEvaluationResult_Response() {}

func (*EvaluationResult_BoolValue) isEvaluationResult_Response() {}

func (*EvaluationResult_BinaryValue) isEvaluationResult_Response() {}

func (*EvaluationResult_NullValue) isEvaluationResult_Response() {}

// Placeholder for null values
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

// Page content
type PageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Html          string                 `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Scripts       []string               `protobuf:"bytes,3,rep,name=scripts,proto3" json:"scripts,omitempty"`
	Stylesheets   []string               `protobuf:"bytes,4,rep,name=stylesheets,proto3" json:"stylesheets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageContent) Reset() {
	*x = PageContent{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageContent) ProtoMessage() {}

func (x *PageContent) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageContent.ProtoReflect.Descriptor instead.
func (*PageContent) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *PageContent) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *PageContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PageContent) GetScripts() []string {
	if x != nil {
		return x.Scripts
	}
	return nil
}

func (x *PageContent) GetStylesheets() []string {
	if x != nil {
		return x.Stylesheets
	}
	return nil
}

// Duration in milliseconds
type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"` // Duration in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *Duration) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Timestamp
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x0fchaser.oxide.v1\"\a\n" +
	"\x05Empty\"C\n" +
	"\tSessionID\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\"\xcc\x01\n" +
	"\x05Error\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.chaser.oxide.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\adetails\x18\x03 \x03(\v2#.chaser.oxide.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x04\n" +
	"\x0eBrowserOptions\x12'\n" +
	"\x0fexecutable_path\x18\x01 \x01(\tR\x0eexecutablePath\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1a\n" +
	"\bheadless\x18\x03 \x01(\bR\bheadless\x12!\n" +
	"\fwindow_width\x18\x04 \x01(\x05R\vwindowWidth\x12#\n" +
	"\rwindow_height\x18\x05 \x01(\x05R\fwindowHeight\x12\"\n" +
	"\ruser_data_dir\x18\x06 \x01(\tR\vuserDataDir\x12!\n" +
	"\fproxy_server\x18\a \x01(\tR\vproxyServer\x12*\n" +
	"\x11proxy_bypass_list\x18\b \x01(\tR\x0fproxyBypassList\x120\n" +
	"\x14disable_web_security\x18\t \x01(\bR\x12disableWebSecurity\x12:\n" +
	"\x19ignore_certificate_errors\x18\n" +
	" \x01(\bR\x17ignoreCertificateErrors\x12\x1f\n" +
	"\vdisable_gpu\x18\v \x01(\bR\n" +
	"disableGpu\x12-\n" +
	"\x12disable_extensions\x18\f \x01(\bR\x11disableExtensions\x12'\n" +
	"\x0fenable_devtools\x18\r \x01(\bR\x0eenableDevtools\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0e \x01(\tR\tuserAgent\x12\x12\n" +
	"\x04lang\x18\x0f \x01(\tR\x04lang\x12\x1a\n" +
	"\btimezone\x18\x10 \x01(\tR\btimezone\"\xc3\x01\n" +
	"\vBrowserInfo\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tR\tbrowserId\x12'\n" +
	"\x0fexecutable_path\x18\x02 \x01(\tR\x0eexecutablePath\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1a\n" +
	"\bheadless\x18\x04 \x01(\bR\bheadless\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vlaunched_at\x18\x06 \x01(\x03R\n" +
	"launchedAt\"\xb7\x02\n" +
	"\x11NavigationOptions\x12\x18\n" +
	"\atimeout\x18\x01 \x01(\x05R\atimeout\x12K\n" +
	"\n" +
	"wait_until\x18\x02 \x01(\x0e2,.chaser.oxide.v1.NavigationOptions.LoadStateR\twaitUntil\x12\x18\n" +
	"\areferer\x18\x03 \x01(\tR\areferer\"\xa0\x01\n" +
	"\tLoadState\x12\x1a\n" +
	"\x16LOAD_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOAD_STATE_LOAD\x10\x01\x12!\n" +
	"\x1dLOAD_STATE_DOM_CONTENT_LOADED\x10\x02\x12\x1b\n" +
	"\x17LOAD_STATE_NETWORK_IDLE\x10\x03\x12\"\n" +
	"\x1eLOAD_STATE_NETWORK_ALMOST_IDLE\x10\x04\"\xba\x02\n" +
	"\x11ScreenshotOptions\x12A\n" +
	"\x06format\x18\x01 \x01(\x0e2).chaser.oxide.v1.ScreenshotOptions.FormatR\x06format\x12\x18\n" +
	"\aquality\x18\x02 \x01(\x05R\aquality\x12.\n" +
	"\x04clip\x18\x03 \x01(\v2\x1a.chaser.oxide.v1.RectangleR\x04clip\x12\x1b\n" +
	"\tfull_page\x18\x04 \x01(\bR\bfullPage\x12'\n" +
	"\x0fomit_background\x18\x05 \x01(\bR\x0eomitBackground\"R\n" +
	"\x06Format\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FORMAT_PNG\x10\x01\x12\x0f\n" +
	"\vFORMAT_JPEG\x10\x02\x12\x0f\n" +
	"\vFORMAT_WEBP\x10\x03\"U\n" +
	"\tRectangle\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\"\x86\x02\n" +
	"\bViewport\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12.\n" +
	"\x13device_scale_factor\x18\x03 \x01(\x01R\x11deviceScaleFactor\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\bR\x06mobile\x12!\n" +
	"\fscreen_width\x18\x05 \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\x06 \x01(\x05R\fscreenHeight\x12\x1d\n" +
	"\n" +
	"position_x\x18\a \x01(\x05R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\b \x01(\x05R\tpositionY\"\xba\x01\n" +
	"\n" +
	"ElementRef\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1d\n" +
	"\n" +
	"element_id\x18\x02 \x01(\tR\telementId\x12B\n" +
	"\rselector_type\x18\x03 \x01(\x0e2\x1d.chaser.oxide.v1.SelectorTypeR\fselectorType\x12\x1a\n" +
	"\bselector\x18\x04 \x01(\tR\bselector\x12\x14\n" +
	"\x05index\x18\x05 \x01(\x05R\x05index\"\xb9\x02\n" +
	"\x10EvaluationResult\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fbinary_value\x18\x05 \x01(\fH\x00R\vbinaryValue\x127\n" +
	"\n" +
	"null_value\x18\x06 \x01(\v2\x16.chaser.oxide.v1.ValueH\x00R\tnullValue\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"class_name\x18\b \x01(\tR\tclassNameB\n" +
	"\n" +
	"\bresponse\"\a\n" +
	"\x05Value\"q\n" +
	"\vPageContent\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\ascripts\x18\x03 \x03(\tR\ascripts\x12 \n" +
	"\vstylesheets\x18\x04 \x03(\tR\vstylesheets\" \n" +
	"\bDuration\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos*\xed\x03\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12ERROR_CODE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x03\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x04\x12!\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\x05\x12\"\n" +
	"\x1eERROR_CODE_FAILED_PRECONDITION\x10\x06\x12\x16\n" +
	"\x12ERROR_CODE_ABORTED\x10\a\x12\x1b\n" +
	"\x17ERROR_CODE_OUT_OF_RANGE\x10\b\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\t\x12\x1d\n" +
	"\x19ERROR_CODE_BROWSER_CLOSED\x10\n" +
	"\x12\x1a\n" +
	"\x16ERROR_CODE_PAGE_CLOSED\x10\v\x12 \n" +
	"\x1cERROR_CODE_ELEMENT_NOT_FOUND\x10\f\x12 \n" +
	"\x1cERROR_CODE_NAVIGATION_FAILED\x10\r\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\x0e\x12 \n" +
	"\x1cERROR_CODE_EVALUATION_FAILED\x10\x0f*\x8d\x01\n" +
	"\fSelectorType\x12\x1d\n" +
	"\x19SELECTOR_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SELECTOR_TYPE_CSS\x10\x01\x12\x17\n" +
	"\x13SELECTOR_TYPE_XPATH\x10\x02\x12\x16\n" +
	"\x12SELECTOR_TYPE_TEXT\x10\x03\x12\x16\n" +
	"\x12SELECTOR_TYPE_ARIA\x10\x04*\xf1\x01\n" +
	"\x0fElementPosition\x12 \n" +
	"\x1cELEMENT_POSITION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ELEMENT_POSITION_CENTER\x10\x01\x12\x1d\n" +
	"\x19ELEMENT_POSITION_TOP_LEFT\x10\x02\x12\x1e\n" +
	"\x1aELEMENT_POSITION_TOP_RIGHT\x10\x03\x12 \n" +
	"\x1cELEMENT_POSITION_BOTTOM_LEFT\x10\x04\x12!\n" +
	"\x1dELEMENT_POSITION_BOTTOM_RIGHT\x10\x05\x12\x1b\n" +
	"\x17ELEMENT_POSITION_RANDOM\x10\x06*\xa4\x01\n" +
	"\vMouseButton\x12\x1c\n" +
	"\x18MOUSE_BUTTON_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MOUSE_BUTTON_LEFT\x10\x01\x12\x17\n" +
	"\x13MOUSE_BUTTON_MIDDLE\x10\x02\x12\x16\n" +
	"\x12MOUSE_BUTTON_RIGHT\x10\x03\x12\x15\n" +
	"\x11MOUSE_BUTTON_BACK\x10\x04\x12\x18\n" +
	"\x14MOUSE_BUTTON_FORWARD\x10\x05*\xac\x01\n" +
	"\vKeyModifier\x12\x1c\n" +
	"\x18KEY_MODIFIER_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10KEY_MODIFIER_ALT\x10\x01\x12\x18\n" +
	"\x14KEY_MODIFIER_CONTROL\x10\x02\x12 \n" +
	"\x1cKEY_MODIFIER_CONTROL_OR_META\x10\x03\x12\x15\n" +
	"\x11KEY_MODIFIER_META\x10\x04\x12\x16\n" +
	"\x12KEY_MODIFIER_SHIFT\x10\x05b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_common_proto_goTypes = []any{
	(ErrorCode)(0),                   // 0: chaser.oxide.v1.ErrorCode
	(SelectorType)(0),                // 1: chaser.oxide.v1.SelectorType
	(ElementPosition)(0),             // 2: chaser.oxide.v1.ElementPosition
	(MouseButton)(0),                 // 3: chaser.oxide.v1.MouseButton
	(KeyModifier)(0),                 // 4: chaser.oxide.v1.KeyModifier
	(NavigationOptions_LoadState)(0), // 5: chaser.oxide.v1.NavigationOptions.LoadState
	(ScreenshotOptions_Format)(0),    // 6: chaser.oxide.v1.ScreenshotOptions.Format
	(*Empty)(nil),                    // 7: chaser.oxide.v1.Empty
	(*SessionID)(nil),                // 8: chaser.oxide.v1.SessionID
	(*Error)(nil),                    // 9: chaser.oxide.v1.Error
	(*BrowserOptions)(nil),           // 10: chaser.oxide.v1.BrowserOptions
	(*BrowserInfo)(nil),              // 11: chaser.oxide.v1.BrowserInfo
	(*NavigationOptions)(nil),        // 12: chaser.oxide.v1.NavigationOptions
	(*ScreenshotOptions)(nil),        // 13: chaser.oxide.v1.ScreenshotOptions
	(*Rectangle)(nil),                // 14: chaser.oxide.v1.Rectangle
	(*Viewport)(nil),                 // 15: chaser.oxide.v1.Viewport
	(*ElementRef)(nil),               // 16: chaser.oxide.v1.ElementRef
	(*EvaluationResult)(nil),         // 17: chaser.oxide.v1.EvaluationResult
	(*Value)(nil),                    // 18: chaser.oxide.v1.Value
	(*PageContent)(nil),              // 19: chaser.oxide.v1.PageContent
	(*Duration)(nil),                 // 20: chaser.oxide.v1.Duration
	(*Timestamp)(nil),                // 21: chaser.oxide.v1.Timestamp
	nil,                              // 22: chaser.oxide.v1.Error.DetailsEntry
}
var file_common_proto_depIdxs = []int32{
	0,  // 0: chaser.oxide.v1.Error.code:type_name -> chaser.oxide.v1.ErrorCode
	22, // 1: chaser.oxide.v1.Error.details:type_name -> chaser.oxide.v1.Error.DetailsEntry
	5,  // 2: chaser.oxide.v1.NavigationOptions.wait_until:type_name -> chaser.oxide.v1.NavigationOptions.LoadState
	6,  // 3: chaser.oxide.v1.ScreenshotOptions.format:type_name -> chaser.oxide.v1.ScreenshotOptions.Format
	14, // 4: chaser.oxide.v1.ScreenshotOptions.clip:type_name -> chaser.oxide.v1.Rectangle
	1,  // 5: chaser.oxide.v1.ElementRef.selector_type:type_name -> chaser.oxide.v1.SelectorType
	18, // 6: chaser.oxide.v1.EvaluationResult.null_value:type_name -> chaser.oxide.v1.Value
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[10].OneofWrappers = []any{
		(*EvaluationResult_StringValue)(nil),
		(*EvaluationResult_IntValue)(nil),
		(*EvaluationResult_DoubleValue)(nil),
		(*EvaluationResult_BoolValue)(nil),
		(*EvaluationResult_BinaryValue)(nil),
		(*EvaluationResult_NullValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
