// Copyright 2026 Chaser-Oxide Server
// Event streaming service for real-time browser events

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: event.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Log level for console events
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_LOG         LogLevel = 1
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 2
	LogLevel_LOG_LEVEL_INFO        LogLevel = 3
	LogLevel_LOG_LEVEL_WARN        LogLevel = 4
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_LOG",
		2: "LOG_LEVEL_DEBUG",
		3: "LOG_LEVEL_INFO",
		4: "LOG_LEVEL_WARN",
		5: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_LOG":         1,
		"LOG_LEVEL_DEBUG":       2,
		"LOG_LEVEL_INFO":        3,
		"LOG_LEVEL_WARN":        4,
		"LOG_LEVEL_ERROR":       5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// Page lifecycle events
	EventType_EVENT_TYPE_PAGE_CREATED       EventType = 1
	EventType_EVENT_TYPE_PAGE_LOADED        EventType = 2
	EventType_EVENT_TYPE_PAGE_NAVIGATED     EventType = 3
	EventType_EVENT_TYPE_PAGE_CLOSED        EventType = 4
	EventType_EVENT_TYPE_PAGE_ERROR         EventType = 5
	EventType_EVENT_TYPE_DOM_CONTENT_LOADED EventType = 6
	EventType_EVENT_TYPE_LOAD_TIMEOUT       EventType = 7
	// Frame events
	EventType_EVENT_TYPE_FRAME_ATTACHED  EventType = 8
	EventType_EVENT_TYPE_FRAME_DETACHED  EventType = 9
	EventType_EVENT_TYPE_FRAME_NAVIGATED EventType = 10
	// Console events
	EventType_EVENT_TYPE_CONSOLE_LOG       EventType = 11
	EventType_EVENT_TYPE_CONSOLE_DEBUG     EventType = 12
	EventType_EVENT_TYPE_CONSOLE_INFO      EventType = 13
	EventType_EVENT_TYPE_CONSOLE_WARN      EventType = 14
	EventType_EVENT_TYPE_CONSOLE_ERROR     EventType = 15
	EventType_EVENT_TYPE_CONSOLE_EXCEPTION EventType = 16
	// Network events
	EventType_EVENT_TYPE_REQUEST_SENT      EventType = 17
	EventType_EVENT_TYPE_RESPONSE_RECEIVED EventType = 18
	EventType_EVENT_TYPE_REQUEST_FAILED    EventType = 19
	EventType_EVENT_TYPE_REQUEST_FINISHED  EventType = 20
	// JavaScript events
	EventType_EVENT_TYPE_JS_EXCEPTION         EventType = 21
	EventType_EVENT_TYPE_JS_PROMISE_REJECTION EventType = 22
	EventType_EVENT_TYPE_JS_EXECUTION         EventType = 23
	// Dialog events
	EventType_EVENT_TYPE_DIALOG_OPENED EventType = 24
	EventType_EVENT_TYPE_DIALOG_CLOSED EventType = 25
	// Worker events
	EventType_EVENT_TYPE_WORKER_CREATED    EventType = 26
	EventType_EVENT_TYPE_WORKER_TERMINATED EventType = 27
	// Browser events
	EventType_EVENT_TYPE_BROWSER_CRASHED      EventType = 28
	EventType_EVENT_TYPE_BROWSER_DISCONNECTED EventType = 29
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_PAGE_CREATED",
		2:  "EVENT_TYPE_PAGE_LOADED",
		3:  "EVENT_TYPE_PAGE_NAVIGATED",
		4:  "EVENT_TYPE_PAGE_CLOSED",
		5:  "EVENT_TYPE_PAGE_ERROR",
		6:  "EVENT_TYPE_DOM_CONTENT_LOADED",
		7:  "EVENT_TYPE_LOAD_TIMEOUT",
		8:  "EVENT_TYPE_FRAME_ATTACHED",
		9:  "EVENT_TYPE_FRAME_DETACHED",
		10: "EVENT_TYPE_FRAME_NAVIGATED",
		11: "EVENT_TYPE_CONSOLE_LOG",
		12: "EVENT_TYPE_CONSOLE_DEBUG",
		13: "EVENT_TYPE_CONSOLE_INFO",
		14: "EVENT_TYPE_CONSOLE_WARN",
		15: "EVENT_TYPE_CONSOLE_ERROR",
		16: "EVENT_TYPE_CONSOLE_EXCEPTION",
		17: "EVENT_TYPE_REQUEST_SENT",
		18: "EVENT_TYPE_RESPONSE_RECEIVED",
		19: "EVENT_TYPE_REQUEST_FAILED",
		20: "EVENT_TYPE_REQUEST_FINISHED",
		21: "EVENT_TYPE_JS_EXCEPTION",
		22: "EVENT_TYPE_JS_PROMISE_REJECTION",
		23: "EVENT_TYPE_JS_EXECUTION",
		24: "EVENT_TYPE_DIALOG_OPENED",
		25: "EVENT_TYPE_DIALOG_CLOSED",
		26: "EVENT_TYPE_WORKER_CREATED",
		27: "EVENT_TYPE_WORKER_TERMINATED",
		28: "EVENT_TYPE_BROWSER_CRASHED",
		29: "EVENT_TYPE_BROWSER_DISCONNECTED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":          0,
		"EVENT_TYPE_PAGE_CREATED":         1,
		"EVENT_TYPE_PAGE_LOADED":          2,
		"EVENT_TYPE_PAGE_NAVIGATED":       3,
		"EVENT_TYPE_PAGE_CLOSED":          4,
		"EVENT_TYPE_PAGE_ERROR":           5,
		"EVENT_TYPE_DOM_CONTENT_LOADED":   6,
		"EVENT_TYPE_LOAD_TIMEOUT":         7,
		"EVENT_TYPE_FRAME_ATTACHED":       8,
		"EVENT_TYPE_FRAME_DETACHED":       9,
		"EVENT_TYPE_FRAME_NAVIGATED":      10,
		"EVENT_TYPE_CONSOLE_LOG":          11,
		"EVENT_TYPE_CONSOLE_DEBUG":        12,
		"EVENT_TYPE_CONSOLE_INFO":         13,
		"EVENT_TYPE_CONSOLE_WARN":         14,
		"EVENT_TYPE_CONSOLE_ERROR":        15,
		"EVENT_TYPE_CONSOLE_EXCEPTION":    16,
		"EVENT_TYPE_REQUEST_SENT":         17,
		"EVENT_TYPE_RESPONSE_RECEIVED":    18,
		"EVENT_TYPE_REQUEST_FAILED":       19,
		"EVENT_TYPE_REQUEST_FINISHED":     20,
		"EVENT_TYPE_JS_EXCEPTION":         21,
		"EVENT_TYPE_JS_PROMISE_REJECTION": 22,
		"EVENT_TYPE_JS_EXECUTION":         23,
		"EVENT_TYPE_DIALOG_OPENED":        24,
		"EVENT_TYPE_DIALOG_CLOSED":        25,
		"EVENT_TYPE_WORKER_CREATED":       26,
		"EVENT_TYPE_WORKER_TERMINATED":    27,
		"EVENT_TYPE_BROWSER_CRASHED":      28,
		"EVENT_TYPE_BROWSER_DISCONNECTED": 29,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

// Subscription action
type SubscribeRequest_Action int32

const (
	SubscribeRequest_ACTION_UNSPECIFIED        SubscribeRequest_Action = 0
	SubscribeRequest_ACTION_SUBSCRIBE          SubscribeRequest_Action = 1 // Subscribe to events
	SubscribeRequest_ACTION_UNSUBSCRIBE        SubscribeRequest_Action = 2 // Unsubscribe from events
	SubscribeRequest_ACTION_LIST_SUBSCRIPTIONS SubscribeRequest_Action = 3 // List active subscriptions
	SubscribeRequest_ACTION_PING               SubscribeRequest_Action = 4 // Keep-alive ping
)

// Enum value maps for SubscribeRequest_Action.
var (
	SubscribeRequest_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_SUBSCRIBE",
		2: "ACTION_UNSUBSCRIBE",
		3: "ACTION_LIST_SUBSCRIPTIONS",
		4: "ACTION_PING",
	}
	SubscribeRequest_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":        0,
		"ACTION_SUBSCRIBE":          1,
		"ACTION_UNSUBSCRIBE":        2,
		"ACTION_LIST_SUBSCRIPTIONS": 3,
		"ACTION_PING":               4,
	}
)

func (x SubscribeRequest_Action) Enum() *SubscribeRequest_Action {
	p := new(SubscribeRequest_Action)
	*p = x
	return p
}

func (x SubscribeRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[2].Descriptor()
}

func (SubscribeRequest_Action) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[2]
}

func (x SubscribeRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeRequest_Action.Descriptor instead.
func (SubscribeRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0, 0}
}

// Response to subscription actions
type SubscribeResponse_ResponseType int32

const (
	SubscribeResponse_RESPONSE_TYPE_UNSPECIFIED   SubscribeResponse_ResponseType = 0
	SubscribeResponse_RESPONSE_TYPE_SUCCESS       SubscribeResponse_ResponseType = 1
	SubscribeResponse_RESPONSE_TYPE_ERROR         SubscribeResponse_ResponseType = 2
	SubscribeResponse_RESPONSE_TYPE_PONG          SubscribeResponse_ResponseType = 3
	SubscribeResponse_RESPONSE_TYPE_SUBSCRIPTIONS SubscribeResponse_ResponseType = 4
)

// Enum value maps for SubscribeResponse_ResponseType.
var (
	SubscribeResponse_ResponseType_name = map[int32]string{
		0: "RESPONSE_TYPE_UNSPECIFIED",
		1: "RESPONSE_TYPE_SUCCESS",
		2: "RESPONSE_TYPE_ERROR",
		3: "RESPONSE_TYPE_PONG",
		4: "RESPONSE_TYPE_SUBSCRIPTIONS",
	}
	SubscribeResponse_ResponseType_value = map[string]int32{
		"RESPONSE_TYPE_UNSPECIFIED":   0,
		"RESPONSE_TYPE_SUCCESS":       1,
		"RESPONSE_TYPE_ERROR":         2,
		"RESPONSE_TYPE_PONG":          3,
		"RESPONSE_TYPE_SUBSCRIPTIONS": 4,
	}
)

func (x SubscribeResponse_ResponseType) Enum() *SubscribeResponse_ResponseType {
	p := new(SubscribeResponse_ResponseType)
	*p = x
	return p
}

func (x SubscribeResponse_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeResponse_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[3].Descriptor()
}

func (SubscribeResponse_ResponseType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[3]
}

func (x SubscribeResponse_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeResponse_ResponseType.Descriptor instead.
func (SubscribeResponse_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4, 0}
}

type PageEvent_PageEventType int32

const (
	PageEvent_PAGE_EVENT_TYPE_UNSPECIFIED        PageEvent_PageEventType = 0
	PageEvent_PAGE_EVENT_TYPE_CREATED            PageEvent_PageEventType = 1
	PageEvent_PAGE_EVENT_TYPE_LOADED             PageEvent_PageEventType = 2
	PageEvent_PAGE_EVENT_TYPE_NAVIGATED          PageEvent_PageEventType = 3
	PageEvent_PAGE_EVENT_TYPE_CLOSED             PageEvent_PageEventType = 4
	PageEvent_PAGE_EVENT_TYPE_ERROR              PageEvent_PageEventType = 5
	PageEvent_PAGE_EVENT_TYPE_DOM_CONTENT_LOADED PageEvent_PageEventType = 6
	PageEvent_PAGE_EVENT_TYPE_LOAD_TIMEOUT       PageEvent_PageEventType = 7
)

// Enum value maps for PageEvent_PageEventType.
var (
	PageEvent_PageEventType_name = map[int32]string{
		0: "PAGE_EVENT_TYPE_UNSPECIFIED",
		1: "PAGE_EVENT_TYPE_CREATED",
		2: "PAGE_EVENT_TYPE_LOADED",
		3: "PAGE_EVENT_TYPE_NAVIGATED",
		4: "PAGE_EVENT_TYPE_CLOSED",
		5: "PAGE_EVENT_TYPE_ERROR",
		6: "PAGE_EVENT_TYPE_DOM_CONTENT_LOADED",
		7: "PAGE_EVENT_TYPE_LOAD_TIMEOUT",
	}
	PageEvent_PageEventType_value = map[string]int32{
		"PAGE_EVENT_TYPE_UNSPECIFIED":        0,
		"PAGE_EVENT_TYPE_CREATED":            1,
		"PAGE_EVENT_TYPE_LOADED":             2,
		"PAGE_EVENT_TYPE_NAVIGATED":          3,
		"PAGE_EVENT_TYPE_CLOSED":             4,
		"PAGE_EVENT_TYPE_ERROR":              5,
		"PAGE_EVENT_TYPE_DOM_CONTENT_LOADED": 6,
		"PAGE_EVENT_TYPE_LOAD_TIMEOUT":       7,
	}
)

func (x PageEvent_PageEventType) Enum() *PageEvent_PageEventType {
	p := new(PageEvent_PageEventType)
	*p = x
	return p
}

func (x PageEvent_PageEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PageEvent_PageEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[4].Descriptor()
}

func (PageEvent_PageEventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[4]
}

func (x PageEvent_PageEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PageEvent_PageEventType.Descriptor instead.
func (PageEvent_PageEventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8, 0}
}

type FrameEvent_FrameEventType int32

const (
	FrameEvent_FRAME_EVENT_TYPE_UNSPECIFIED FrameEvent_FrameEventType = 0
	FrameEvent_FRAME_EVENT_TYPE_ATTACHED    FrameEvent_FrameEventType = 1
	FrameEvent_FRAME_EVENT_TYPE_DETACHED    FrameEvent_FrameEventType = 2
	FrameEvent_FRAME_EVENT_TYPE_NAVIGATED   FrameEvent_FrameEventType = 3
)

// Enum value maps for FrameEvent_FrameEventType.
var (
	FrameEvent_FrameEventType_name = map[int32]string{
		0: "FRAME_EVENT_TYPE_UNSPECIFIED",
		1: "FRAME_EVENT_TYPE_ATTACHED",
		2: "FRAME_EVENT_TYPE_DETACHED",
		3: "FRAME_EVENT_TYPE_NAVIGATED",
	}
	FrameEvent_FrameEventType_value = map[string]int32{
		"FRAME_EVENT_TYPE_UNSPECIFIED": 0,
		"FRAME_EVENT_TYPE_ATTACHED":    1,
		"FRAME_EVENT_TYPE_DETACHED":    2,
		"FRAME_EVENT_TYPE_NAVIGATED":   3,
	}
)

func (x FrameEvent_FrameEventType) Enum() *FrameEvent_FrameEventType {
	p := new(FrameEvent_FrameEventType)
	*p = x
	return p
}

func (x FrameEvent_FrameEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameEvent_FrameEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[5].Descriptor()
}

func (FrameEvent_FrameEventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[5]
}

func (x FrameEvent_FrameEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameEvent_FrameEventType.Descriptor instead.
func (FrameEvent_FrameEventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9, 0}
}

type NetworkEvent_NetworkEventType int32

const (
	NetworkEvent_NETWORK_EVENT_TYPE_UNSPECIFIED NetworkEvent_NetworkEventType = 0
	NetworkEvent_NETWORK_EVENT_TYPE_SENT        NetworkEvent_NetworkEventType = 1
	NetworkEvent_NETWORK_EVENT_TYPE_RECEIVED    NetworkEvent_NetworkEventType = 2
	NetworkEvent_NETWORK_EVENT_TYPE_FAILED      NetworkEvent_NetworkEventType = 3
	NetworkEvent_NETWORK_EVENT_TYPE_FINISHED    NetworkEvent_NetworkEventType = 4
)

// Enum value maps for NetworkEvent_NetworkEventType.
var (
	NetworkEvent_NetworkEventType_name = map[int32]string{
		0: "NETWORK_EVENT_TYPE_UNSPECIFIED",
		1: "NETWORK_EVENT_TYPE_SENT",
		2: "NETWORK_EVENT_TYPE_RECEIVED",
		3: "NETWORK_EVENT_TYPE_FAILED",
		4: "NETWORK_EVENT_TYPE_FINISHED",
	}
	NetworkEvent_NetworkEventType_value = map[string]int32{
		"NETWORK_EVENT_TYPE_UNSPECIFIED": 0,
		"NETWORK_EVENT_TYPE_SENT":        1,
		"NETWORK_EVENT_TYPE_RECEIVED":    2,
		"NETWORK_EVENT_TYPE_FAILED":      3,
		"NETWORK_EVENT_TYPE_FINISHED":    4,
	}
)

func (x NetworkEvent_NetworkEventType) Enum() *NetworkEvent_NetworkEventType {
	p := new(NetworkEvent_NetworkEventType)
	*p = x
	return p
}

func (x NetworkEvent_NetworkEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkEvent_NetworkEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[6].Descriptor()
}

func (NetworkEvent_NetworkEventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[6]
}

func (x NetworkEvent_NetworkEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkEvent_NetworkEventType.Descriptor instead.
func (NetworkEvent_NetworkEventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11, 0}
}

type JavaScriptEvent_JSEventType int32

const (
	JavaScriptEvent_JS_EVENT_TYPE_UNSPECIFIED       JavaScriptEvent_JSEventType = 0
	JavaScriptEvent_JS_EVENT_TYPE_EXCEPTION         JavaScriptEvent_JSEventType = 1
	JavaScriptEvent_JS_EVENT_TYPE_PROMISE_REJECTION JavaScriptEvent_JSEventType = 2
	JavaScriptEvent_JS_EVENT_TYPE_EXECUTION         JavaScriptEvent_JSEventType = 3
)

// Enum value maps for JavaScriptEvent_JSEventType.
var (
	JavaScriptEvent_JSEventType_name = map[int32]string{
		0: "JS_EVENT_TYPE_UNSPECIFIED",
		1: "JS_EVENT_TYPE_EXCEPTION",
		2: "JS_EVENT_TYPE_PROMISE_REJECTION",
		3: "JS_EVENT_TYPE_EXECUTION",
	}
	JavaScriptEvent_JSEventType_value = map[string]int32{
		"JS_EVENT_TYPE_UNSPECIFIED":       0,
		"JS_EVENT_TYPE_EXCEPTION":         1,
		"JS_EVENT_TYPE_PROMISE_REJECTION": 2,
		"JS_EVENT_TYPE_EXECUTION":         3,
	}
)

func (x JavaScriptEvent_JSEventType) Enum() *JavaScriptEvent_JSEventType {
	p := new(JavaScriptEvent_JSEventType)
	*p = x
	return p
}

func (x JavaScriptEvent_JSEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JavaScriptEvent_JSEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[7].Descriptor()
}

func (JavaScriptEvent_JSEventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[7]
}

func (x JavaScriptEvent_JSEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JavaScriptEvent_JSEventType.Descriptor instead.
func (JavaScriptEvent_JSEventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12, 0}
}

type DialogEvent_DialogType int32

const (
	DialogEvent_DIALOG_TYPE_UNSPECIFIED   DialogEvent_DialogType = 0
	DialogEvent_DIALOG_TYPE_ALERT         DialogEvent_DialogType = 1
	DialogEvent_DIALOG_TYPE_CONFIRM       DialogEvent_DialogType = 2
	DialogEvent_DIALOG_TYPE_PROMPT        DialogEvent_DialogType = 3
	DialogEvent_DIALOG_TYPE_BEFORE_UNLOAD DialogEvent_DialogType = 4
)

// Enum value maps for DialogEvent_DialogType.
var (
	DialogEvent_DialogType_name = map[int32]string{
		0: "DIALOG_TYPE_UNSPECIFIED",
		1: "DIALOG_TYPE_ALERT",
		2: "DIALOG_TYPE_CONFIRM",
		3: "DIALOG_TYPE_PROMPT",
		4: "DIALOG_TYPE_BEFORE_UNLOAD",
	}
	DialogEvent_DialogType_value = map[string]int32{
		"DIALOG_TYPE_UNSPECIFIED":   0,
		"DIALOG_TYPE_ALERT":         1,
		"DIALOG_TYPE_CONFIRM":       2,
		"DIALOG_TYPE_PROMPT":        3,
		"DIALOG_TYPE_BEFORE_UNLOAD": 4,
	}
)

func (x DialogEvent_DialogType) Enum() *DialogEvent_DialogType {
	p := new(DialogEvent_DialogType)
	*p = x
	return p
}

func (x DialogEvent_DialogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialogEvent_DialogType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[8].Descriptor()
}

func (DialogEvent_DialogType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[8]
}

func (x DialogEvent_DialogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialogEvent_DialogType.Descriptor instead.
func (DialogEvent_DialogType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13, 0}
}

type WorkerEvent_WorkerEventType int32

const (
	WorkerEvent_WORKER_EVENT_TYPE_UNSPECIFIED WorkerEvent_WorkerEventType = 0
	WorkerEvent_WORKER_EVENT_TYPE_CREATED     WorkerEvent_WorkerEventType = 1
	WorkerEvent_WORKER_EVENT_TYPE_TERMINATED  WorkerEvent_WorkerEventType = 2
)

// Enum value maps for WorkerEvent_WorkerEventType.
var (
	WorkerEvent_WorkerEventType_name = map[int32]string{
		0: "WORKER_EVENT_TYPE_UNSPECIFIED",
		1: "WORKER_EVENT_TYPE_CREATED",
		2: "WORKER_EVENT_TYPE_TERMINATED",
	}
	WorkerEvent_WorkerEventType_value = map[string]int32{
		"WORKER_EVENT_TYPE_UNSPECIFIED": 0,
		"WORKER_EVENT_TYPE_CREATED":     1,
		"WORKER_EVENT_TYPE_TERMINATED":  2,
	}
)

func (x WorkerEvent_WorkerEventType) Enum() *WorkerEvent_WorkerEventType {
	p := new(WorkerEvent_WorkerEventType)
	*p = x
	return p
}

func (x WorkerEvent_WorkerEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerEvent_WorkerEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[9].Descriptor()
}

func (WorkerEvent_WorkerEventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[9]
}

func (x WorkerEvent_WorkerEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerEvent_WorkerEventType.Descriptor instead.
func (WorkerEvent_WorkerEventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14, 0}
}

type BrowserEvent_BrowserEventType int32

const (
	BrowserEvent_BROWSER_EVENT_TYPE_UNSPECIFIED  BrowserEvent_BrowserEventType = 0
	BrowserEvent_BROWSER_EVENT_TYPE_CRASHED      BrowserEvent_BrowserEventType = 1
	BrowserEvent_BROWSER_EVENT_TYPE_DISCONNECTED BrowserEvent_BrowserEventType = 2
)

// Enum value maps for BrowserEvent_BrowserEventType.
var (
	BrowserEvent_BrowserEventType_name = map[int32]string{
		0: "BROWSER_EVENT_TYPE_UNSPECIFIED",
		1: "BROWSER_EVENT_TYPE_CRASHED",
		2: "BROWSER_EVENT_TYPE_DISCONNECTED",
	}
	BrowserEvent_BrowserEventType_value = map[string]int32{
		"BROWSER_EVENT_TYPE_UNSPECIFIED":  0,
		"BROWSER_EVENT_TYPE_CRASHED":      1,
		"BROWSER_EVENT_TYPE_DISCONNECTED": 2,
	}
)

func (x BrowserEvent_BrowserEventType) Enum() *BrowserEvent_BrowserEventType {
	p := new(BrowserEvent_BrowserEventType)
	*p = x
	return p
}

func (x BrowserEvent_BrowserEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrowserEvent_BrowserEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[10].Descriptor()
}

func (BrowserEvent_BrowserEventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[10]
}

func (x BrowserEvent_BrowserEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrowserEvent_BrowserEventType.Descriptor instead.
func (BrowserEvent_BrowserEventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15, 0}
}

type SubscribeRequest struct {
	state  protoimpl.MessageState  `protogen:"open.v1"`
	Action SubscribeRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=chaser.oxide.v1.SubscribeRequest_Action" json:"action,omitempty"`
	// Subscription configuration
	Subscription *Subscription `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// Client-provided subscription ID (optional, auto-generated if not provided)
	SubscriptionId string `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetAction() SubscribeRequest_Action {
	if x != nil {
		return x.Action
	}
	return SubscribeRequest_ACTION_UNSPECIFIED
}

func (x *SubscribeRequest) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *SubscribeRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type Subscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What to subscribe to
	//
	// Types that are valid to be assigned to Target:
	//
	//	*Subscription_BrowserId
	//	*Subscription_PageId
	//	*Subscription_EventType
	Target isSubscription_Target `protobuf_oneof:"target"`
	// Event types to subscribe to (empty = all)
	EventTypes []EventType `protobuf:"varint,4,rep,packed,name=event_types,json=eventTypes,proto3,enum=chaser.oxide.v1.EventType" json:"event_types,omitempty"`
	// Subscription filters
	Filter *EventFilter `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	// Subscription options
	Options       *SubscriptionOptions `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetTarget() isSubscription_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Subscription) GetBrowserId() string {
	if x != nil {
		if x, ok := x.Target.(*Subscription_BrowserId); ok {
			return x.BrowserId
		}
	}
	return ""
}

func (x *Subscription) GetPageId() string {
	if x != nil {
		if x, ok := x.Target.(*Subscription_PageId); ok {
			return x.PageId
		}
	}
	return ""
}

func (x *Subscription) GetEventType() EventType {
	if x != nil {
		if x, ok := x.Target.(*Subscription_EventType); ok {
			return x.EventType
		}
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Subscription) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *Subscription) GetFilter() *EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Subscription) GetOptions() *SubscriptionOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type isSubscription_Target interface {
	isSubscription_Target()
}

type Subscription_BrowserId struct {
	BrowserId string `protobuf:"bytes,1,opt,name=browser_id,json=browserId,proto3,oneof"` // All events for a browser
}

type Subscription_PageId struct {
	PageId string `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3,oneof"` // All events for a page
}

type Subscription_EventType struct {
	EventType EventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=chaser.oxide.v1.EventType,oneof"` // Specific event type globally
}

func (*Subscription_BrowserId) isSubscription_Target() {}

func (*Subscription_PageId) isSubscription_Target() {}

func (*Subscription_EventType) isSubscription_Target() {}

type EventFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by URL pattern
	UrlPattern string `protobuf:"bytes,1,opt,name=url_pattern,json=urlPattern,proto3" json:"url_pattern,omitempty"`
	// Filter by request/response status
	StatusCodes []int32 `protobuf:"varint,2,rep,packed,name=status_codes,json=statusCodes,proto3" json:"status_codes,omitempty"`
	// Filter by resource type
	ResourceTypes []string `protobuf:"bytes,3,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"` // document, stylesheet, image, etc.
	// Filter by console log level
	LogLevels []LogLevel `protobuf:"varint,4,rep,packed,name=log_levels,json=logLevels,proto3,enum=chaser.oxide.v1.LogLevel" json:"log_levels,omitempty"`
	// Custom JavaScript filter expression
	JsExpression  string `protobuf:"bytes,5,opt,name=js_expression,json=jsExpression,proto3" json:"js_expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventFilter) GetUrlPattern() string {
	if x != nil {
		return x.UrlPattern
	}
	return ""
}

func (x *EventFilter) GetStatusCodes() []int32 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

func (x *EventFilter) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *EventFilter) GetLogLevels() []LogLevel {
	if x != nil {
		return x.LogLevels
	}
	return nil
}

func (x *EventFilter) GetJsExpression() string {
	if x != nil {
		return x.JsExpression
	}
	return ""
}

type SubscriptionOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include event details
	IncludeDetails bool `protobuf:"varint,1,opt,name=include_details,json=includeDetails,proto3" json:"include_details,omitempty"`
	// Include stack traces
	IncludeStackTrace bool `protobuf:"varint,2,opt,name=include_stack_trace,json=includeStackTrace,proto3" json:"include_stack_trace,omitempty"`
	// Throttle events (ms between events)
	ThrottleMs int32 `protobuf:"varint,3,opt,name=throttle_ms,json=throttleMs,proto3" json:"throttle_ms,omitempty"`
	// Maximum buffer size
	BufferSize int32 `protobuf:"varint,4,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	// Enable event batching
	BatchEvents bool `protobuf:"varint,5,opt,name=batch_events,json=batchEvents,proto3" json:"batch_events,omitempty"`
	// Batch size
	BatchSize int32 `protobuf:"varint,6,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// Batch timeout (ms)
	BatchTimeout  int32 `protobuf:"varint,7,opt,name=batch_timeout,json=batchTimeout,proto3" json:"batch_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionOptions) Reset() {
	*x = SubscriptionOptions{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionOptions) ProtoMessage() {}

func (x *SubscriptionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionOptions.ProtoReflect.Descriptor instead.
func (*SubscriptionOptions) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionOptions) GetIncludeDetails() bool {
	if x != nil {
		return x.IncludeDetails
	}
	return false
}

func (x *SubscriptionOptions) GetIncludeStackTrace() bool {
	if x != nil {
		return x.IncludeStackTrace
	}
	return false
}

func (x *SubscriptionOptions) GetThrottleMs() int32 {
	if x != nil {
		return x.ThrottleMs
	}
	return 0
}

func (x *SubscriptionOptions) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *SubscriptionOptions) GetBatchEvents() bool {
	if x != nil {
		return x.BatchEvents
	}
	return false
}

func (x *SubscriptionOptions) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *SubscriptionOptions) GetBatchTimeout() int32 {
	if x != nil {
		return x.BatchTimeout
	}
	return 0
}

type SubscribeResponse struct {
	state protoimpl.MessageState         `protogen:"open.v1"`
	Type  SubscribeResponse_ResponseType `protobuf:"varint,1,opt,name=type,proto3,enum=chaser.oxide.v1.SubscribeResponse_ResponseType" json:"type,omitempty"`
	// Subscription ID for successful subscriptions
	SubscriptionId string `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// Error message (if any)
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// List of active subscriptions (for ACTION_LIST_SUBSCRIPTIONS)
	Subscriptions []*SubscriptionInfo `protobuf:"bytes,4,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeResponse) GetType() SubscribeResponse_ResponseType {
	if x != nil {
		return x.Type
	}
	return SubscribeResponse_RESPONSE_TYPE_UNSPECIFIED
}

func (x *SubscribeResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscribeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SubscribeResponse) GetSubscriptions() []*SubscriptionInfo {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscriptionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Target         string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // browser_id or page_id
	EventTypes     []EventType            `protobuf:"varint,3,rep,packed,name=event_types,json=eventTypes,proto3,enum=chaser.oxide.v1.EventType" json:"event_types,omitempty"`
	SubscribedAt   int64                  `protobuf:"varint,4,opt,name=subscribed_at,json=subscribedAt,proto3" json:"subscribed_at,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionInfo) Reset() {
	*x = SubscriptionInfo{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionInfo) ProtoMessage() {}

func (x *SubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionInfo.ProtoReflect.Descriptor instead.
func (*SubscriptionInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionInfo) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SubscriptionInfo) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *SubscriptionInfo) GetSubscribedAt() int64 {
	if x != nil {
		return x.SubscribedAt
	}
	return 0
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event metadata
	Metadata *EventMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Event-specific data
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Event_PageEvent
	//	*Event_FrameEvent
	//	*Event_ConsoleEvent
	//	*Event_NetworkEvent
	//	*Event_JsEvent
	//	*Event_DialogEvent
	//	*Event_WorkerEvent
	//	*Event_BrowserEvent
	Data isEvent_Data `protobuf_oneof:"data"`
	// Subscription ID that triggered this event
	SubscriptionId string `protobuf:"bytes,10,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetData() isEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetPageEvent() *PageEvent {
	if x != nil {
		if x, ok := x.Data.(*Event_PageEvent); ok {
			return x.PageEvent
		}
	}
	return nil
}

func (x *Event) GetFrameEvent() *FrameEvent {
	if x != nil {
		if x, ok := x.Data.(*Event_FrameEvent); ok {
			return x.FrameEvent
		}
	}
	return nil
}

func (x *Event) GetConsoleEvent() *ConsoleEvent {
	if x != nil {
		if x, ok := x.Data.(*Event_ConsoleEvent); ok {
			return x.ConsoleEvent
		}
	}
	return nil
}

func (x *Event) GetNetworkEvent() *NetworkEvent {
	if x != nil {
		if x, ok := x.Data.(*Event_NetworkEvent); ok {
			return x.NetworkEvent
		}
	}
	return nil
}

func (x *Event) GetJsEvent() *JavaScriptEvent {
	if x != nil {
		if x, ok := x.Data.(*Event_JsEvent); ok {
			return x.JsEvent
		}
	}
	return nil
}

func (x *Event) GetDialogEvent() *DialogEvent {
	if x != nil {
		if x, ok := x.Data.(*Event_DialogEvent); ok {
			return x.DialogEvent
		}
	}
	return nil
}

func (x *Event) GetWorkerEvent() *WorkerEvent {
	if x != nil {
		if x, ok := x.Data.(*Event_WorkerEvent); ok {
			return x.WorkerEvent
		}
	}
	return nil
}

func (x *Event) GetBrowserEvent() *BrowserEvent {
	if x != nil {
		if x, ok := x.Data.(*Event_BrowserEvent); ok {
			return x.BrowserEvent
		}
	}
	return nil
}

func (x *Event) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_PageEvent struct {
	PageEvent *PageEvent `protobuf:"bytes,2,opt,name=page_event,json=pageEvent,proto3,oneof"`
}

type Event_FrameEvent struct {
	FrameEvent *FrameEvent `protobuf:"bytes,3,opt,name=frame_event,json=frameEvent,proto3,oneof"`
}

type Event_ConsoleEvent struct {
	ConsoleEvent *ConsoleEvent `protobuf:"bytes,4,opt,name=console_event,json=consoleEvent,proto3,oneof"`
}

type Event_NetworkEvent struct {
	NetworkEvent *NetworkEvent `protobuf:"bytes,5,opt,name=network_event,json=networkEvent,proto3,oneof"`
}

type Event_JsEvent struct {
	JsEvent *JavaScriptEvent `protobuf:"bytes,6,opt,name=js_event,json=jsEvent,proto3,oneof"`
}

type Event_DialogEvent struct {
	DialogEvent *DialogEvent `protobuf:"bytes,7,opt,name=dialog_event,json=dialogEvent,proto3,oneof"`
}

type Event_WorkerEvent struct {
	WorkerEvent *WorkerEvent `protobuf:"bytes,8,opt,name=worker_event,json=workerEvent,proto3,oneof"`
}

type Event_BrowserEvent struct {
	BrowserEvent *BrowserEvent `protobuf:"bytes,9,opt,name=browser_event,json=browserEvent,proto3,oneof"`
}

func (*Event_PageEvent) isEvent_Data() {}

func (*Event_FrameEvent) isEvent_Data() {}

func (*Event_ConsoleEvent) isEvent_Data() {}

func (*Event_NetworkEvent) isEvent_Data() {}

func (*Event_JsEvent) isEvent_Data() {}

func (*Event_DialogEvent) isEvent_Data() {}

func (*Event_WorkerEvent) isEvent_Data() {}

func (*Event_BrowserEvent) isEvent_Data() {}

type EventMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // Unique event ID
	Type          EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=chaser.oxide.v1.EventType" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp (ms)
	BrowserId     string                 `protobuf:"bytes,4,opt,name=browser_id,json=browserId,proto3" json:"browser_id,omitempty"`
	PageId        string                 `protobuf:"bytes,5,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	FrameId       string                 `protobuf:"bytes,6,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`                                                        // Optional
	Extra         map[string]string      `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *EventMetadata) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventMetadata) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *EventMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EventMetadata) GetBrowserId() string {
	if x != nil {
		return x.BrowserId
	}
	return ""
}

func (x *EventMetadata) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *EventMetadata) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *EventMetadata) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PageEvent struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	EventType     PageEvent_PageEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=chaser.oxide.v1.PageEvent_PageEventType" json:"event_type,omitempty"`
	Url           string                  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	StatusCode    int32                   `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`      // For navigation events
	ErrorMessage  string                  `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // For error events
	LoadTime      int64                   `protobuf:"varint,6,opt,name=load_time,json=loadTime,proto3" json:"load_time,omitempty"`            // Page load time in ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageEvent) Reset() {
	*x = PageEvent{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageEvent) ProtoMessage() {}

func (x *PageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageEvent.ProtoReflect.Descriptor instead.
func (*PageEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *PageEvent) GetEventType() PageEvent_PageEventType {
	if x != nil {
		return x.EventType
	}
	return PageEvent_PAGE_EVENT_TYPE_UNSPECIFIED
}

func (x *PageEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PageEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PageEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PageEvent) GetLoadTime() int64 {
	if x != nil {
		return x.LoadTime
	}
	return 0
}

type FrameEvent struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	EventType     FrameEvent_FrameEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=chaser.oxide.v1.FrameEvent_FrameEventType" json:"event_type,omitempty"`
	FrameId       string                    `protobuf:"bytes,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	ParentFrameId string                    `protobuf:"bytes,3,opt,name=parent_frame_id,json=parentFrameId,proto3" json:"parent_frame_id,omitempty"` // Optional
	Url           string                    `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                    `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"` // Frame name/ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameEvent) Reset() {
	*x = FrameEvent{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameEvent) ProtoMessage() {}

func (x *FrameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameEvent.ProtoReflect.Descriptor instead.
func (*FrameEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *FrameEvent) GetEventType() FrameEvent_FrameEventType {
	if x != nil {
		return x.EventType
	}
	return FrameEvent_FRAME_EVENT_TYPE_UNSPECIFIED
}

func (x *FrameEvent) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *FrameEvent) GetParentFrameId() string {
	if x != nil {
		return x.ParentFrameId
	}
	return ""
}

func (x *FrameEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FrameEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConsoleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=chaser.oxide.v1.LogLevel" json:"level,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`      // Console arguments
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`        // Script URL
	Line          int32                  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`     // Line number
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"` // Column number
	StackTrace    string                 `protobuf:"bytes,6,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleEvent) Reset() {
	*x = ConsoleEvent{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleEvent) ProtoMessage() {}

func (x *ConsoleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleEvent.ProtoReflect.Descriptor instead.
func (*ConsoleEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *ConsoleEvent) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *ConsoleEvent) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ConsoleEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConsoleEvent) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ConsoleEvent) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *ConsoleEvent) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

type NetworkEvent struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	EventType     NetworkEvent_NetworkEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=chaser.oxide.v1.NetworkEvent_NetworkEventType" json:"event_type,omitempty"`
	RequestId     string                        `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Url           string                        `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                        `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"` // GET, POST, etc.
	Headers       map[string]string             `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatusCode    int32                         `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`        // For response events
	FromCache     bool                          `protobuf:"varint,7,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`           // For response events
	ResourceType  string                        `protobuf:"bytes,8,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`   // document, stylesheet, image, etc.
	RequestSize   int64                         `protobuf:"varint,9,opt,name=request_size,json=requestSize,proto3" json:"request_size,omitempty"`     // Bytes
	ResponseSize  int64                         `protobuf:"varint,10,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"` // Bytes
	Duration      float64                       `protobuf:"fixed64,11,opt,name=duration,proto3" json:"duration,omitempty"`                            // Request duration in seconds
	Timing        float64                       `protobuf:"fixed64,12,opt,name=timing,proto3" json:"timing,omitempty"`                                // Timing information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkEvent) GetEventType() NetworkEvent_NetworkEventType {
	if x != nil {
		return x.EventType
	}
	return NetworkEvent_NETWORK_EVENT_TYPE_UNSPECIFIED
}

func (x *NetworkEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NetworkEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NetworkEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NetworkEvent) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *NetworkEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *NetworkEvent) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

func (x *NetworkEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *NetworkEvent) GetRequestSize() int64 {
	if x != nil {
		return x.RequestSize
	}
	return 0
}

func (x *NetworkEvent) GetResponseSize() int64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *NetworkEvent) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *NetworkEvent) GetTiming() float64 {
	if x != nil {
		return x.Timing
	}
	return 0
}

type JavaScriptEvent struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EventType     JavaScriptEvent_JSEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=chaser.oxide.v1.JavaScriptEvent_JSEventType" json:"event_type,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url           string                      `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Line          int32                       `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                       `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	StackTrace    string                      `protobuf:"bytes,6,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	ExceptionId   string                      `protobuf:"bytes,7,opt,name=exception_id,json=exceptionId,proto3" json:"exception_id,omitempty"` // For promise rejections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JavaScriptEvent) Reset() {
	*x = JavaScriptEvent{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JavaScriptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JavaScriptEvent) ProtoMessage() {}

func (x *JavaScriptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JavaScriptEvent.ProtoReflect.Descriptor instead.
func (*JavaScriptEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *JavaScriptEvent) GetEventType() JavaScriptEvent_JSEventType {
	if x != nil {
		return x.EventType
	}
	return JavaScriptEvent_JS_EVENT_TYPE_UNSPECIFIED
}

func (x *JavaScriptEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JavaScriptEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *JavaScriptEvent) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *JavaScriptEvent) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *JavaScriptEvent) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *JavaScriptEvent) GetExceptionId() string {
	if x != nil {
		return x.ExceptionId
	}
	return ""
}

type DialogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DialogEvent_DialogType `protobuf:"varint,1,opt,name=type,proto3,enum=chaser.oxide.v1.DialogEvent_DialogType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DefaultPrompt bool                   `protobuf:"varint,3,opt,name=default_prompt,json=defaultPrompt,proto3" json:"default_prompt,omitempty"` // For prompt dialogs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialogEvent) Reset() {
	*x = DialogEvent{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogEvent) ProtoMessage() {}

func (x *DialogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogEvent.ProtoReflect.Descriptor instead.
func (*DialogEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *DialogEvent) GetType() DialogEvent_DialogType {
	if x != nil {
		return x.Type
	}
	return DialogEvent_DIALOG_TYPE_UNSPECIFIED
}

func (x *DialogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DialogEvent) GetDefaultPrompt() bool {
	if x != nil {
		return x.DefaultPrompt
	}
	return false
}

type WorkerEvent struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	EventType     WorkerEvent_WorkerEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=chaser.oxide.v1.WorkerEvent_WorkerEventType" json:"event_type,omitempty"`
	WorkerId      string                      `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Url           string                      `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	WorkerType    string                      `protobuf:"bytes,4,opt,name=worker_type,json=workerType,proto3" json:"worker_type,omitempty"` // dedicated, shared, service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerEvent) Reset() {
	*x = WorkerEvent{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEvent) ProtoMessage() {}

func (x *WorkerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEvent.ProtoReflect.Descriptor instead.
func (*WorkerEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *WorkerEvent) GetEventType() WorkerEvent_WorkerEventType {
	if x != nil {
		return x.EventType
	}
	return WorkerEvent_WORKER_EVENT_TYPE_UNSPECIFIED
}

func (x *WorkerEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WorkerEvent) GetWorkerType() string {
	if x != nil {
		return x.WorkerType
	}
	return ""
}

type BrowserEvent struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	EventType     BrowserEvent_BrowserEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=chaser.oxide.v1.BrowserEvent_BrowserEventType" json:"event_type,omitempty"`
	ErrorMessage  string                        `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExitCode      int32                         `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // For crash events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserEvent) Reset() {
	*x = BrowserEvent{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserEvent) ProtoMessage() {}

func (x *BrowserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserEvent.ProtoReflect.Descriptor instead.
func (*BrowserEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *BrowserEvent) GetEventType() BrowserEvent_BrowserEventType {
	if x != nil {
		return x.EventType
	}
	return BrowserEvent_BROWSER_EVENT_TYPE_UNSPECIFIED
}

func (x *BrowserEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BrowserEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x0fchaser.oxide.v1\"\xc0\x02\n" +
	"\x10SubscribeRequest\x12@\n" +
	"\x06action\x18\x01 \x01(\x0e2(.chaser.oxide.v1.SubscribeRequest.ActionR\x06action\x12A\n" +
	"\fsubscription\x18\x02 \x01(\v2\x1d.chaser.oxide.v1.SubscriptionR\fsubscription\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\"~\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTION_SUBSCRIBE\x10\x01\x12\x16\n" +
	"\x12ACTION_UNSUBSCRIBE\x10\x02\x12\x1d\n" +
	"\x19ACTION_LIST_SUBSCRIPTIONS\x10\x03\x12\x0f\n" +
	"\vACTION_PING\x10\x04\"\xc4\x02\n" +
	"\fSubscription\x12\x1f\n" +
	"\n" +
	"browser_id\x18\x01 \x01(\tH\x00R\tbrowserId\x12\x19\n" +
	"\apage_id\x18\x02 \x01(\tH\x00R\x06pageId\x12;\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x1a.chaser.oxide.v1.EventTypeH\x00R\teventType\x12;\n" +
	"\vevent_types\x18\x04 \x03(\x0e2\x1a.chaser.oxide.v1.EventTypeR\n" +
	"eventTypes\x124\n" +
	"\x06filter\x18\x05 \x01(\v2\x1c.chaser.oxide.v1.EventFilterR\x06filter\x12>\n" +
	"\aoptions\x18\x06 \x01(\v2$.chaser.oxide.v1.SubscriptionOptionsR\aoptionsB\b\n" +
	"\x06target\"\xd7\x01\n" +
	"\vEventFilter\x12\x1f\n" +
	"\vurl_pattern\x18\x01 \x01(\tR\n" +
	"urlPattern\x12!\n" +
	"\fstatus_codes\x18\x02 \x03(\x05R\vstatusCodes\x12%\n" +
	"\x0eresource_types\x18\x03 \x03(\tR\rresourceTypes\x128\n" +
	"\n" +
	"log_levels\x18\x04 \x03(\x0e2\x19.chaser.oxide.v1.LogLevelR\tlogLevels\x12#\n" +
	"\rjs_expression\x18\x05 \x01(\tR\fjsExpression\"\x97\x02\n" +
	"\x13SubscriptionOptions\x12'\n" +
	"\x0finclude_details\x18\x01 \x01(\bR\x0eincludeDetails\x12.\n" +
	"\x13include_stack_trace\x18\x02 \x01(\bR\x11includeStackTrace\x12\x1f\n" +
	"\vthrottle_ms\x18\x03 \x01(\x05R\n" +
	"throttleMs\x12\x1f\n" +
	"\vbuffer_size\x18\x04 \x01(\x05R\n" +
	"bufferSize\x12!\n" +
	"\fbatch_events\x18\x05 \x01(\bR\vbatchEvents\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x06 \x01(\x05R\tbatchSize\x12#\n" +
	"\rbatch_timeout\x18\a \x01(\x05R\fbatchTimeout\"\x8c\x03\n" +
	"\x11SubscribeResponse\x12C\n" +
	"\x04type\x18\x01 \x01(\x0e2/.chaser.oxide.v1.SubscribeResponse.ResponseTypeR\x04type\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12G\n" +
	"\rsubscriptions\x18\x04 \x03(\v2!.chaser.oxide.v1.SubscriptionInfoR\rsubscriptions\"\x9a\x01\n" +
	"\fResponseType\x12\x1d\n" +
	"\x19RESPONSE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESPONSE_TYPE_SUCCESS\x10\x01\x12\x17\n" +
	"\x13RESPONSE_TYPE_ERROR\x10\x02\x12\x16\n" +
	"\x12RESPONSE_TYPE_PONG\x10\x03\x12\x1f\n" +
	"\x1bRESPONSE_TYPE_SUBSCRIPTIONS\x10\x04\"\xb5\x01\n" +
	"\x10SubscriptionInfo\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12;\n" +
	"\vevent_types\x18\x03 \x03(\x0e2\x1a.chaser.oxide.v1.EventTypeR\n" +
	"eventTypes\x12#\n" +
	"\rsubscribed_at\x18\x04 \x01(\x03R\fsubscribedAt\"\x88\x05\n" +
	"\x05Event\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.chaser.oxide.v1.EventMetadataR\bmetadata\x12;\n" +
	"\n" +
	"page_event\x18\x02 \x01(\v2\x1a.chaser.oxide.v1.PageEventH\x00R\tpageEvent\x12>\n" +
	"\vframe_event\x18\x03 \x01(\v2\x1b.chaser.oxide.v1.FrameEventH\x00R\n" +
	"frameEvent\x12D\n" +
	"\rconsole_event\x18\x04 \x01(\v2\x1d.chaser.oxide.v1.ConsoleEventH\x00R\fconsoleEvent\x12D\n" +
	"\rnetwork_event\x18\x05 \x01(\v2\x1d.chaser.oxide.v1.NetworkEventH\x00R\fnetworkEvent\x12=\n" +
	"\bjs_event\x18\x06 \x01(\v2 .chaser.oxide.v1.JavaScriptEventH\x00R\ajsEvent\x12A\n" +
	"\fdialog_event\x18\a \x01(\v2\x1c.chaser.oxide.v1.DialogEventH\x00R\vdialogEvent\x12A\n" +
	"\fworker_event\x18\b \x01(\v2\x1c.chaser.oxide.v1.WorkerEventH\x00R\vworkerEvent\x12D\n" +
	"\rbrowser_event\x18\t \x01(\v2\x1d.chaser.oxide.v1.BrowserEventH\x00R\fbrowserEvent\x12'\n" +
	"\x0fsubscription_id\x18\n" +
	" \x01(\tR\x0esubscriptionIdB\x06\n" +
	"\x04data\"\xc6\x02\n" +
	"\rEventMetadata\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.chaser.oxide.v1.EventTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"browser_id\x18\x04 \x01(\tR\tbrowserId\x12\x17\n" +
	"\apage_id\x18\x05 \x01(\tR\x06pageId\x12\x19\n" +
	"\bframe_id\x18\x06 \x01(\tR\aframeId\x12?\n" +
	"\x05extra\x18\a \x03(\v2).chaser.oxide.v1.EventMetadata.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x03\n" +
	"\tPageEvent\x12G\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2(.chaser.oxide.v1.PageEvent.PageEventTypeR\teventType\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tload_time\x18\x06 \x01(\x03R\bloadTime\"\x89\x02\n" +
	"\rPageEventType\x12\x1f\n" +
	"\x1bPAGE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PAGE_EVENT_TYPE_CREATED\x10\x01\x12\x1a\n" +
	"\x16PAGE_EVENT_TYPE_LOADED\x10\x02\x12\x1d\n" +
	"\x19PAGE_EVENT_TYPE_NAVIGATED\x10\x03\x12\x1a\n" +
	"\x16PAGE_EVENT_TYPE_CLOSED\x10\x04\x12\x19\n" +
	"\x15PAGE_EVENT_TYPE_ERROR\x10\x05\x12&\n" +
	"\"PAGE_EVENT_TYPE_DOM_CONTENT_LOADED\x10\x06\x12 \n" +
	"\x1cPAGE_EVENT_TYPE_LOAD_TIMEOUT\x10\a\"\xd3\x02\n" +
	"\n" +
	"FrameEvent\x12I\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2*.chaser.oxide.v1.FrameEvent.FrameEventTypeR\teventType\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\tR\aframeId\x12&\n" +
	"\x0fparent_frame_id\x18\x03 \x01(\tR\rparentFrameId\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\x90\x01\n" +
	"\x0eFrameEventType\x12 \n" +
	"\x1cFRAME_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FRAME_EVENT_TYPE_ATTACHED\x10\x01\x12\x1d\n" +
	"\x19FRAME_EVENT_TYPE_DETACHED\x10\x02\x12\x1e\n" +
	"\x1aFRAME_EVENT_TYPE_NAVIGATED\x10\x03\"\xb2\x01\n" +
	"\fConsoleEvent\x12/\n" +
	"\x05level\x18\x01 \x01(\x0e2\x19.chaser.oxide.v1.LogLevelR\x05level\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12\x1f\n" +
	"\vstack_trace\x18\x06 \x01(\tR\n" +
	"stackTrace\"\xc0\x05\n" +
	"\fNetworkEvent\x12M\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2..chaser.oxide.v1.NetworkEvent.NetworkEventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12D\n" +
	"\aheaders\x18\x05 \x03(\v2*.chaser.oxide.v1.NetworkEvent.HeadersEntryR\aheaders\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"from_cache\x18\a \x01(\bR\tfromCache\x12#\n" +
	"\rresource_type\x18\b \x01(\tR\fresourceType\x12!\n" +
	"\frequest_size\x18\t \x01(\x03R\vrequestSize\x12#\n" +
	"\rresponse_size\x18\n" +
	" \x01(\x03R\fresponseSize\x12\x1a\n" +
	"\bduration\x18\v \x01(\x01R\bduration\x12\x16\n" +
	"\x06timing\x18\f \x01(\x01R\x06timing\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x10NetworkEventType\x12\"\n" +
	"\x1eNETWORK_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17NETWORK_EVENT_TYPE_SENT\x10\x01\x12\x1f\n" +
	"\x1bNETWORK_EVENT_TYPE_RECEIVED\x10\x02\x12\x1d\n" +
	"\x19NETWORK_EVENT_TYPE_FAILED\x10\x03\x12\x1f\n" +
	"\x1bNETWORK_EVENT_TYPE_FINISHED\x10\x04\"\x88\x03\n" +
	"\x0fJavaScriptEvent\x12K\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2,.chaser.oxide.v1.JavaScriptEvent.JSEventTypeR\teventType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12\x1f\n" +
	"\vstack_trace\x18\x06 \x01(\tR\n" +
	"stackTrace\x12!\n" +
	"\fexception_id\x18\a \x01(\tR\vexceptionId\"\x8b\x01\n" +
	"\vJSEventType\x12\x1d\n" +
	"\x19JS_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17JS_EVENT_TYPE_EXCEPTION\x10\x01\x12#\n" +
	"\x1fJS_EVENT_TYPE_PROMISE_REJECTION\x10\x02\x12\x1b\n" +
	"\x17JS_EVENT_TYPE_EXECUTION\x10\x03\"\x9e\x02\n" +
	"\vDialogEvent\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.chaser.oxide.v1.DialogEvent.DialogTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0edefault_prompt\x18\x03 \x01(\bR\rdefaultPrompt\"\x90\x01\n" +
	"\n" +
	"DialogType\x12\x1b\n" +
	"\x17DIALOG_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIALOG_TYPE_ALERT\x10\x01\x12\x17\n" +
	"\x13DIALOG_TYPE_CONFIRM\x10\x02\x12\x16\n" +
	"\x12DIALOG_TYPE_PROMPT\x10\x03\x12\x1d\n" +
	"\x19DIALOG_TYPE_BEFORE_UNLOAD\x10\x04\"\xa1\x02\n" +
	"\vWorkerEvent\x12K\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2,.chaser.oxide.v1.WorkerEvent.WorkerEventTypeR\teventType\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1f\n" +
	"\vworker_type\x18\x04 \x01(\tR\n" +
	"workerType\"u\n" +
	"\x0fWorkerEventType\x12!\n" +
	"\x1dWORKER_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WORKER_EVENT_TYPE_CREATED\x10\x01\x12 \n" +
	"\x1cWORKER_EVENT_TYPE_TERMINATED\x10\x02\"\x9c\x02\n" +
	"\fBrowserEvent\x12M\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2..chaser.oxide.v1.BrowserEvent.BrowserEventTypeR\teventType\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"{\n" +
	"\x10BrowserEventType\x12\"\n" +
	"\x1eBROWSER_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aBROWSER_EVENT_TYPE_CRASHED\x10\x01\x12#\n" +
	"\x1fBROWSER_EVENT_TYPE_DISCONNECTED\x10\x02*\x8a\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rLOG_LEVEL_LOG\x10\x01\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x03\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x05*\xa8\a\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_PAGE_CREATED\x10\x01\x12\x1a\n" +
	"\x16EVENT_TYPE_PAGE_LOADED\x10\x02\x12\x1d\n" +
	"\x19EVENT_TYPE_PAGE_NAVIGATED\x10\x03\x12\x1a\n" +
	"\x16EVENT_TYPE_PAGE_CLOSED\x10\x04\x12\x19\n" +
	"\x15EVENT_TYPE_PAGE_ERROR\x10\x05\x12!\n" +
	"\x1dEVENT_TYPE_DOM_CONTENT_LOADED\x10\x06\x12\x1b\n" +
	"\x17EVENT_TYPE_LOAD_TIMEOUT\x10\a\x12\x1d\n" +
	"\x19EVENT_TYPE_FRAME_ATTACHED\x10\b\x12\x1d\n" +
	"\x19EVENT_TYPE_FRAME_DETACHED\x10\t\x12\x1e\n" +
	"\x1aEVENT_TYPE_FRAME_NAVIGATED\x10\n" +
	"\x12\x1a\n" +
	"\x16EVENT_TYPE_CONSOLE_LOG\x10\v\x12\x1c\n" +
	"\x18EVENT_TYPE_CONSOLE_DEBUG\x10\f\x12\x1b\n" +
	"\x17EVENT_TYPE_CONSOLE_INFO\x10\r\x12\x1b\n" +
	"\x17EVENT_TYPE_CONSOLE_WARN\x10\x0e\x12\x1c\n" +
	"\x18EVENT_TYPE_CONSOLE_ERROR\x10\x0f\x12 \n" +
	"\x1cEVENT_TYPE_CONSOLE_EXCEPTION\x10\x10\x12\x1b\n" +
	"\x17EVENT_TYPE_REQUEST_SENT\x10\x11\x12 \n" +
	"\x1cEVENT_TYPE_RESPONSE_RECEIVED\x10\x12\x12\x1d\n" +
	"\x19EVENT_TYPE_REQUEST_FAILED\x10\x13\x12\x1f\n" +
	"\x1bEVENT_TYPE_REQUEST_FINISHED\x10\x14\x12\x1b\n" +
	"\x17EVENT_TYPE_JS_EXCEPTION\x10\x15\x12#\n" +
	"\x1fEVENT_TYPE_JS_PROMISE_REJECTION\x10\x16\x12\x1b\n" +
	"\x17EVENT_TYPE_JS_EXECUTION\x10\x17\x12\x1c\n" +
	"\x18EVENT_TYPE_DIALOG_OPENED\x10\x18\x12\x1c\n" +
	"\x18EVENT_TYPE_DIALOG_CLOSED\x10\x19\x12\x1d\n" +
	"\x19EVENT_TYPE_WORKER_CREATED\x10\x1a\x12 \n" +
	"\x1cEVENT_TYPE_WORKER_TERMINATED\x10\x1b\x12\x1e\n" +
	"\x1aEVENT_TYPE_BROWSER_CRASHED\x10\x1c\x12#\n" +
	"\x1fEVENT_TYPE_BROWSER_DISCONNECTED\x10\x1d2Z\n" +
	"\fEventService\x12J\n" +
	"\tSubscribe\x12!.chaser.oxide.v1.SubscribeRequest\x1a\x16.chaser.oxide.v1.Event(\x010\x01b\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 11)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_event_proto_goTypes = []any{
	(LogLevel)(0),                       // 0: chaser.oxide.v1.LogLevel
	(EventType)(0),                      // 1: chaser.oxide.v1.EventType
	(SubscribeRequest_Action)(0),        // 2: chaser.oxide.v1.SubscribeRequest.Action
	(SubscribeResponse_ResponseType)(0), // 3: chaser.oxide.v1.SubscribeResponse.ResponseType
	(PageEvent_PageEventType)(0),        // 4: chaser.oxide.v1.PageEvent.PageEventType
	(FrameEvent_FrameEventType)(0),      // 5: chaser.oxide.v1.FrameEvent.FrameEventType
	(NetworkEvent_NetworkEventType)(0),  // 6: chaser.oxide.v1.NetworkEvent.NetworkEventType
	(JavaScriptEvent_JSEventType)(0),    // 7: chaser.oxide.v1.JavaScriptEvent.JSEventType
	(DialogEvent_DialogType)(0),         // 8: chaser.oxide.v1.DialogEvent.DialogType
	(WorkerEvent_WorkerEventType)(0),    // 9: chaser.oxide.v1.WorkerEvent.WorkerEventType
	(BrowserEvent_BrowserEventType)(0),  // 10: chaser.oxide.v1.BrowserEvent.BrowserEventType
	(*SubscribeRequest)(nil),            // 11: chaser.oxide.v1.SubscribeRequest
	(*Subscription)(nil),                // 12: chaser.oxide.v1.Subscription
	(*EventFilter)(nil),                 // 13: chaser.oxide.v1.EventFilter
	(*SubscriptionOptions)(nil),         // 14: chaser.oxide.v1.SubscriptionOptions
	(*SubscribeResponse)(nil),           // 15: chaser.oxide.v1.SubscribeResponse
	(*SubscriptionInfo)(nil),            // 16: chaser.oxide.v1.SubscriptionInfo
	(*Event)(nil),                       // 17: chaser.oxide.v1.Event
	(*EventMetadata)(nil),               // 18: chaser.oxide.v1.EventMetadata
	(*PageEvent)(nil),                   // 19: chaser.oxide.v1.PageEvent
	(*FrameEvent)(nil),                  // 20: chaser.oxide.v1.FrameEvent
	(*ConsoleEvent)(nil),                // 21: chaser.oxide.v1.ConsoleEvent
	(*NetworkEvent)(nil),                // 22: chaser.oxide.v1.NetworkEvent
	(*JavaScriptEvent)(nil),             // 23: chaser.oxide.v1.JavaScriptEvent
	(*DialogEvent)(nil),                 // 24: chaser.oxide.v1.DialogEvent
	(*WorkerEvent)(nil),                 // 25: chaser.oxide.v1.WorkerEvent
	(*BrowserEvent)(nil),                // 26: chaser.oxide.v1.BrowserEvent
	nil,                                 // 27: chaser.oxide.v1.EventMetadata.ExtraEntry
	nil,                                 // 28: chaser.oxide.v1.NetworkEvent.HeadersEntry
}
var file_event_proto_depIdxs = []int32{
	2,  // 0: chaser.oxide.v1.SubscribeRequest.action:type_name -> chaser.oxide.v1.SubscribeRequest.Action
	12, // 1: chaser.oxide.v1.SubscribeRequest.subscription:type_name -> chaser.oxide.v1.Subscription
	1,  // 2: chaser.oxide.v1.Subscription.event_type:type_name -> chaser.oxide.v1.EventType
	1,  // 3: chaser.oxide.v1.Subscription.event_types:type_name -> chaser.oxide.v1.EventType
	13, // 4: chaser.oxide.v1.Subscription.filter:type_name -> chaser.oxide.v1.EventFilter
	14, // 5: chaser.oxide.v1.Subscription.options:type_name -> chaser.oxide.v1.SubscriptionOptions
	0,  // 6: chaser.oxide.v1.EventFilter.log_levels:type_name -> chaser.oxide.v1.LogLevel
	3,  // 7: chaser.oxide.v1.SubscribeResponse.type:type_name -> chaser.oxide.v1.SubscribeResponse.ResponseType
	16, // 8: chaser.oxide.v1.SubscribeResponse.subscriptions:type_name -> chaser.oxide.v1.SubscriptionInfo
	1,  // 9: chaser.oxide.v1.SubscriptionInfo.event_types:type_name -> chaser.oxide.v1.EventType
	18, // 10: chaser.oxide.v1.Event.metadata:type_name -> chaser.oxide.v1.EventMetadata
	19, // 11: chaser.oxide.v1.Event.page_event:type_name -> chaser.oxide.v1.PageEvent
	20, // 12: chaser.oxide.v1.Event.frame_event:type_name -> chaser.oxide.v1.FrameEvent
	21, // 13: chaser.oxide.v1.Event.console_event:type_name -> chaser.oxide.v1.ConsoleEvent
	22, // 14: chaser.oxide.v1.Event.network_event:type_name -> chaser.oxide.v1.NetworkEvent
	23, // 15: chaser.oxide.v1.Event.js_event:type_name -> chaser.oxide.v1.JavaScriptEvent
	24, // 16: chaser.oxide.v1.Event.dialog_event:type_name -> chaser.oxide.v1.DialogEvent
	25, // 17: chaser.oxide.v1.Event.worker_event:type_name -> chaser.oxide.v1.WorkerEvent
	26, // 18: chaser.oxide.v1.Event.browser_event:type_name -> chaser.oxide.v1.BrowserEvent
	1,  // 19: chaser.oxide.v1.EventMetadata.type:type_name -> chaser.oxide.v1.EventType
	27, // 20: chaser.oxide.v1.EventMetadata.extra:type_name -> chaser.oxide.v1.EventMetadata.ExtraEntry
	4,  // 21: chaser.oxide.v1.PageEvent.event_type:type_name -> chaser.oxide.v1.PageEvent.PageEventType
	5,  // 22: chaser.oxide.v1.FrameEvent.event_type:type_name -> chaser.oxide.v1.FrameEvent.FrameEventType
	0,  // 23: chaser.oxide.v1.ConsoleEvent.level:type_name -> chaser.oxide.v1.LogLevel
	6,  // 24: chaser.oxide.v1.NetworkEvent.event_type:type_name -> chaser.oxide.v1.NetworkEvent.NetworkEventType
	28, // 25: chaser.oxide.v1.NetworkEvent.headers:type_name -> chaser.oxide.v1.NetworkEvent.HeadersEntry
	7,  // 26: chaser.oxide.v1.JavaScriptEvent.event_type:type_name -> chaser.oxide.v1.JavaScriptEvent.JSEventType
	8,  // 27: chaser.oxide.v1.DialogEvent.type:type_name -> chaser.oxide.v1.DialogEvent.DialogType
	9,  // 28: chaser.oxide.v1.WorkerEvent.event_type:type_name -> chaser.oxide.v1.WorkerEvent.WorkerEventType
	10, // 29: chaser.oxide.v1.BrowserEvent.event_type:type_name -> chaser.oxide.v1.BrowserEvent.BrowserEventType
	11, // 30: chaser.oxide.v1.EventService.Subscribe:input_type -> chaser.oxide.v1.SubscribeRequest
	17, // 31: chaser.oxide.v1.EventService.Subscribe:output_type -> chaser.oxide.v1.Event
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[1].OneofWrappers = []any{
		(*Subscription_BrowserId)(nil),
		(*Subscription_PageId)(nil),
		(*Subscription_EventType)(nil),
	}
	file_event_proto_msgTypes[6].OneofWrappers = []any{
		(*Event_PageEvent)(nil),
		(*Event_FrameEvent)(nil),
		(*Event_ConsoleEvent)(nil),
		(*Event_NetworkEvent)(nil),
		(*Event_JsEvent)(nil),
		(*Event_DialogEvent)(nil),
		(*Event_WorkerEvent)(nil),
		(*Event_BrowserEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      11,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
