// Copyright 2026 Chaser-Oxide Server
// Page operations and navigation service

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: page.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PageService_CreatePage_FullMethodName          = "/chaser.oxide.v1.PageService/CreatePage"
	PageService_Navigate_FullMethodName            = "/chaser.oxide.v1.PageService/Navigate"
	PageService_GetSnapshot_FullMethodName         = "/chaser.oxide.v1.PageService/GetSnapshot"
	PageService_Screenshot_FullMethodName          = "/chaser.oxide.v1.PageService/Screenshot"
	PageService_Evaluate_FullMethodName            = "/chaser.oxide.v1.PageService/Evaluate"
	PageService_EvaluateOnElement_FullMethodName   = "/chaser.oxide.v1.PageService/EvaluateOnElement"
	PageService_SetContent_FullMethodName          = "/chaser.oxide.v1.PageService/SetContent"
	PageService_GetContent_FullMethodName          = "/chaser.oxide.v1.PageService/GetContent"
	PageService_Reload_FullMethodName              = "/chaser.oxide.v1.PageService/Reload"
	PageService_GoBack_FullMethodName              = "/chaser.oxide.v1.PageService/GoBack"
	PageService_GoForward_FullMethodName           = "/chaser.oxide.v1.PageService/GoForward"
	PageService_SetViewport_FullMethodName         = "/chaser.oxide.v1.PageService/SetViewport"
	PageService_EmulateDevice_FullMethodName       = "/chaser.oxide.v1.PageService/EmulateDevice"
	PageService_BringToFront_FullMethodName        = "/chaser.oxide.v1.PageService/BringToFront"
	PageService_GetMetrics_FullMethodName          = "/chaser.oxide.v1.PageService/GetMetrics"
	PageService_ClosePage_FullMethodName           = "/chaser.oxide.v1.PageService/ClosePage"
	PageService_WaitFor_FullMethodName             = "/chaser.oxide.v1.PageService/WaitFor"
	PageService_GetPDF_FullMethodName              = "/chaser.oxide.v1.PageService/GetPDF"
	PageService_AddInitScript_FullMethodName       = "/chaser.oxide.v1.PageService/AddInitScript"
	PageService_OverridePermissions_FullMethodName = "/chaser.oxide.v1.PageService/OverridePermissions"
	PageService_SetGeolocation_FullMethodName      = "/chaser.oxide.v1.PageService/SetGeolocation"
	PageService_SetOfflineMode_FullMethodName      = "/chaser.oxide.v1.PageService/SetOfflineMode"
	PageService_SetCacheEnabled_FullMethodName     = "/chaser.oxide.v1.PageService/SetCacheEnabled"
	PageService_GetCookies_FullMethodName          = "/chaser.oxide.v1.PageService/GetCookies"
	PageService_SetCookies_FullMethodName          = "/chaser.oxide.v1.PageService/SetCookies"
	PageService_ClearCookies_FullMethodName        = "/chaser.oxide.v1.PageService/ClearCookies"
)

// PageServiceClient is the client API for PageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============= PageService =============
// Manages browser pages/tabs and their operations
type PageServiceClient interface {
	// Create a new page/tab in the browser
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error)
	// Navigate to a URL
	Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error)
	// Get current page snapshot (accessible tree)
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	// Take a screenshot of the page
	Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error)
	// Execute JavaScript in the page context
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	// Evaluate JavaScript on a specific element
	EvaluateOnElement(ctx context.Context, in *EvaluateOnElementRequest, opts ...grpc.CallOption) (*EvaluateOnElementResponse, error)
	// Set page HTML content
	SetContent(ctx context.Context, in *SetContentRequest, opts ...grpc.CallOption) (*SetContentResponse, error)
	// Get page HTML content
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
	// Reload the page
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	// Go back in history
	GoBack(ctx context.Context, in *GoBackRequest, opts ...grpc.CallOption) (*GoBackResponse, error)
	// Go forward in history
	GoForward(ctx context.Context, in *GoForwardRequest, opts ...grpc.CallOption) (*GoForwardResponse, error)
	// Set viewport size
	SetViewport(ctx context.Context, in *SetViewportRequest, opts ...grpc.CallOption) (*SetViewportResponse, error)
	// Emulate device (mobile, tablet, etc.)
	EmulateDevice(ctx context.Context, in *EmulateDeviceRequest, opts ...grpc.CallOption) (*EmulateDeviceResponse, error)
	// Bring page to front (focus)
	BringToFront(ctx context.Context, in *BringToFrontRequest, opts ...grpc.CallOption) (*BringToFrontResponse, error)
	// Get page metrics (layout metrics)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// Close a page
	ClosePage(ctx context.Context, in *ClosePageRequest, opts ...grpc.CallOption) (*ClosePageResponse, error)
	// Wait for specific condition or selector
	WaitFor(ctx context.Context, in *WaitForRequest, opts ...grpc.CallOption) (*WaitForResponse, error)
	// Get page PDF
	GetPDF(ctx context.Context, in *GetPDFRequest, opts ...grpc.CallOption) (*GetPDFResponse, error)
	// Add script to evaluate on new documents
	AddInitScript(ctx context.Context, in *AddInitScriptRequest, opts ...grpc.CallOption) (*AddInitScriptResponse, error)
	// Override permissions
	OverridePermissions(ctx context.Context, in *OverridePermissionsRequest, opts ...grpc.CallOption) (*OverridePermissionsResponse, error)
	// Set geolocation
	SetGeolocation(ctx context.Context, in *SetGeolocationRequest, opts ...grpc.CallOption) (*SetGeolocationResponse, error)
	// Set offline mode
	SetOfflineMode(ctx context.Context, in *SetOfflineModeRequest, opts ...grpc.CallOption) (*SetOfflineModeResponse, error)
	// Set cache enabled/disabled
	SetCacheEnabled(ctx context.Context, in *SetCacheEnabledRequest, opts ...grpc.CallOption) (*SetCacheEnabledResponse, error)
	// Get cookies
	GetCookies(ctx context.Context, in *GetCookiesRequest, opts ...grpc.CallOption) (*GetCookiesResponse, error)
	// Set cookies
	SetCookies(ctx context.Context, in *SetCookiesRequest, opts ...grpc.CallOption) (*SetCookiesResponse, error)
	// Clear cookies
	ClearCookies(ctx context.Context, in *ClearCookiesRequest, opts ...grpc.CallOption) (*ClearCookiesResponse, error)
}

type pageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPageServiceClient(cc grpc.ClientConnInterface) PageServiceClient {
	return &pageServiceClient{cc}
}

func (c *pageServiceClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePageResponse)
	err := c.cc.Invoke(ctx, PageService_CreatePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateResponse)
	err := c.cc.Invoke(ctx, PageService_Navigate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, PageService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenshotResponse)
	err := c.cc.Invoke(ctx, PageService_Screenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, PageService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) EvaluateOnElement(ctx context.Context, in *EvaluateOnElementRequest, opts ...grpc.CallOption) (*EvaluateOnElementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateOnElementResponse)
	err := c.cc.Invoke(ctx, PageService_EvaluateOnElement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SetContent(ctx context.Context, in *SetContentRequest, opts ...grpc.CallOption) (*SetContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetContentResponse)
	err := c.cc.Invoke(ctx, PageService_SetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentResponse)
	err := c.cc.Invoke(ctx, PageService_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, PageService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GoBack(ctx context.Context, in *GoBackRequest, opts ...grpc.CallOption) (*GoBackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoBackResponse)
	err := c.cc.Invoke(ctx, PageService_GoBack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GoForward(ctx context.Context, in *GoForwardRequest, opts ...grpc.CallOption) (*GoForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoForwardResponse)
	err := c.cc.Invoke(ctx, PageService_GoForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SetViewport(ctx context.Context, in *SetViewportRequest, opts ...grpc.CallOption) (*SetViewportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetViewportResponse)
	err := c.cc.Invoke(ctx, PageService_SetViewport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) EmulateDevice(ctx context.Context, in *EmulateDeviceRequest, opts ...grpc.CallOption) (*EmulateDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmulateDeviceResponse)
	err := c.cc.Invoke(ctx, PageService_EmulateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) BringToFront(ctx context.Context, in *BringToFrontRequest, opts ...grpc.CallOption) (*BringToFrontResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BringToFrontResponse)
	err := c.cc.Invoke(ctx, PageService_BringToFront_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, PageService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ClosePage(ctx context.Context, in *ClosePageRequest, opts ...grpc.CallOption) (*ClosePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClosePageResponse)
	err := c.cc.Invoke(ctx, PageService_ClosePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) WaitFor(ctx context.Context, in *WaitForRequest, opts ...grpc.CallOption) (*WaitForResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForResponse)
	err := c.cc.Invoke(ctx, PageService_WaitFor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetPDF(ctx context.Context, in *GetPDFRequest, opts ...grpc.CallOption) (*GetPDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPDFResponse)
	err := c.cc.Invoke(ctx, PageService_GetPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) AddInitScript(ctx context.Context, in *AddInitScriptRequest, opts ...grpc.CallOption) (*AddInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddInitScriptResponse)
	err := c.cc.Invoke(ctx, PageService_AddInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) OverridePermissions(ctx context.Context, in *OverridePermissionsRequest, opts ...grpc.CallOption) (*OverridePermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverridePermissionsResponse)
	err := c.cc.Invoke(ctx, PageService_OverridePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SetGeolocation(ctx context.Context, in *SetGeolocationRequest, opts ...grpc.CallOption) (*SetGeolocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGeolocationResponse)
	err := c.cc.Invoke(ctx, PageService_SetGeolocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SetOfflineMode(ctx context.Context, in *SetOfflineModeRequest, opts ...grpc.CallOption) (*SetOfflineModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetOfflineModeResponse)
	err := c.cc.Invoke(ctx, PageService_SetOfflineMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SetCacheEnabled(ctx context.Context, in *SetCacheEnabledRequest, opts ...grpc.CallOption) (*SetCacheEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCacheEnabledResponse)
	err := c.cc.Invoke(ctx, PageService_SetCacheEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetCookies(ctx context.Context, in *GetCookiesRequest, opts ...grpc.CallOption) (*GetCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCookiesResponse)
	err := c.cc.Invoke(ctx, PageService_GetCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SetCookies(ctx context.Context, in *SetCookiesRequest, opts ...grpc.CallOption) (*SetCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCookiesResponse)
	err := c.cc.Invoke(ctx, PageService_SetCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ClearCookies(ctx context.Context, in *ClearCookiesRequest, opts ...grpc.CallOption) (*ClearCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearCookiesResponse)
	err := c.cc.Invoke(ctx, PageService_ClearCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageServiceServer is the server API for PageService service.
// All implementations must embed UnimplementedPageServiceServer
// for forward compatibility.
//
// ============= PageService =============
// Manages browser pages/tabs and their operations
type PageServiceServer interface {
	// Create a new page/tab in the browser
	CreatePage(context.Context, *CreatePageRequest) (*CreatePageResponse, error)
	// Navigate to a URL
	Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error)
	// Get current page snapshot (accessible tree)
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	// Take a screenshot of the page
	Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error)
	// Execute JavaScript in the page context
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	// Evaluate JavaScript on a specific element
	EvaluateOnElement(context.Context, *EvaluateOnElementRequest) (*EvaluateOnElementResponse, error)
	// Set page HTML content
	SetContent(context.Context, *SetContentRequest) (*SetContentResponse, error)
	// Get page HTML content
	GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error)
	// Reload the page
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	// Go back in history
	GoBack(context.Context, *GoBackRequest) (*GoBackResponse, error)
	// Go forward in history
	GoForward(context.Context, *GoForwardRequest) (*GoForwardResponse, error)
	// Set viewport size
	SetViewport(context.Context, *SetViewportRequest) (*SetViewportResponse, error)
	// Emulate device (mobile, tablet, etc.)
	EmulateDevice(context.Context, *EmulateDeviceRequest) (*EmulateDeviceResponse, error)
	// Bring page to front (focus)
	BringToFront(context.Context, *BringToFrontRequest) (*BringToFrontResponse, error)
	// Get page metrics (layout metrics)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// Close a page
	ClosePage(context.Context, *ClosePageRequest) (*ClosePageResponse, error)
	// Wait for specific condition or selector
	WaitFor(context.Context, *WaitForRequest) (*WaitForResponse, error)
	// Get page PDF
	GetPDF(context.Context, *GetPDFRequest) (*GetPDFResponse, error)
	// Add script to evaluate on new documents
	AddInitScript(context.Context, *AddInitScriptRequest) (*AddInitScriptResponse, error)
	// Override permissions
	OverridePermissions(context.Context, *OverridePermissionsRequest) (*OverridePermissionsResponse, error)
	// Set geolocation
	SetGeolocation(context.Context, *SetGeolocationRequest) (*SetGeolocationResponse, error)
	// Set offline mode
	SetOfflineMode(context.Context, *SetOfflineModeRequest) (*SetOfflineModeResponse, error)
	// Set cache enabled/disabled
	SetCacheEnabled(context.Context, *SetCacheEnabledRequest) (*SetCacheEnabledResponse, error)
	// Get cookies
	GetCookies(context.Context, *GetCookiesRequest) (*GetCookiesResponse, error)
	// Set cookies
	SetCookies(context.Context, *SetCookiesRequest) (*SetCookiesResponse, error)
	// Clear cookies
	ClearCookies(context.Context, *ClearCookiesRequest) (*ClearCookiesResponse, error)
	mustEmbedUnimplementedPageServiceServer()
}

// UnimplementedPageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPageServiceServer struct{}

func (UnimplementedPageServiceServer) CreatePage(context.Context, *CreatePageRequest) (*CreatePageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePage not implemented")
}
func (UnimplementedPageServiceServer) Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Navigate not implemented")
}
func (UnimplementedPageServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedPageServiceServer) Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screenshot not implemented")
}
func (UnimplementedPageServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedPageServiceServer) EvaluateOnElement(context.Context, *EvaluateOnElementRequest) (*EvaluateOnElementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateOnElement not implemented")
}
func (UnimplementedPageServiceServer) SetContent(context.Context, *SetContentRequest) (*SetContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetContent not implemented")
}
func (UnimplementedPageServiceServer) GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedPageServiceServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedPageServiceServer) GoBack(context.Context, *GoBackRequest) (*GoBackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoBack not implemented")
}
func (UnimplementedPageServiceServer) GoForward(context.Context, *GoForwardRequest) (*GoForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoForward not implemented")
}
func (UnimplementedPageServiceServer) SetViewport(context.Context, *SetViewportRequest) (*SetViewportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetViewport not implemented")
}
func (UnimplementedPageServiceServer) EmulateDevice(context.Context, *EmulateDeviceRequest) (*EmulateDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmulateDevice not implemented")
}
func (UnimplementedPageServiceServer) BringToFront(context.Context, *BringToFrontRequest) (*BringToFrontResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BringToFront not implemented")
}
func (UnimplementedPageServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedPageServiceServer) ClosePage(context.Context, *ClosePageRequest) (*ClosePageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePage not implemented")
}
func (UnimplementedPageServiceServer) WaitFor(context.Context, *WaitForRequest) (*WaitForResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitFor not implemented")
}
func (UnimplementedPageServiceServer) GetPDF(context.Context, *GetPDFRequest) (*GetPDFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPDF not implemented")
}
func (UnimplementedPageServiceServer) AddInitScript(context.Context, *AddInitScriptRequest) (*AddInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddInitScript not implemented")
}
func (UnimplementedPageServiceServer) OverridePermissions(context.Context, *OverridePermissionsRequest) (*OverridePermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OverridePermissions not implemented")
}
func (UnimplementedPageServiceServer) SetGeolocation(context.Context, *SetGeolocationRequest) (*SetGeolocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGeolocation not implemented")
}
func (UnimplementedPageServiceServer) SetOfflineMode(context.Context, *SetOfflineModeRequest) (*SetOfflineModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOfflineMode not implemented")
}
func (UnimplementedPageServiceServer) SetCacheEnabled(context.Context, *SetCacheEnabledRequest) (*SetCacheEnabledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCacheEnabled not implemented")
}
func (UnimplementedPageServiceServer) GetCookies(context.Context, *GetCookiesRequest) (*GetCookiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCookies not implemented")
}
func (UnimplementedPageServiceServer) SetCookies(context.Context, *SetCookiesRequest) (*SetCookiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCookies not implemented")
}
func (UnimplementedPageServiceServer) ClearCookies(context.Context, *ClearCookiesRequest) (*ClearCookiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearCookies not implemented")
}
func (UnimplementedPageServiceServer) mustEmbedUnimplementedPageServiceServer() {}
func (UnimplementedPageServiceServer) testEmbeddedByValue()                     {}

// UnsafePageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PageServiceServer will
// result in compilation errors.
type UnsafePageServiceServer interface {
	mustEmbedUnimplementedPageServiceServer()
}

func RegisterPageServiceServer(s grpc.ServiceRegistrar, srv PageServiceServer) {
	// If the following call panics, it indicates UnimplementedPageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PageService_ServiceDesc, srv)
}

func _PageService_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_CreatePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Navigate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).Navigate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_Navigate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).Navigate(ctx, req.(*NavigateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Screenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).Screenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_Screenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).Screenshot(ctx, req.(*ScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_EvaluateOnElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateOnElementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).EvaluateOnElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_EvaluateOnElement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).EvaluateOnElement(ctx, req.(*EvaluateOnElementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SetContent(ctx, req.(*SetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GoBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoBackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GoBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GoBack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GoBack(ctx, req.(*GoBackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GoForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GoForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GoForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GoForward(ctx, req.(*GoForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SetViewport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetViewportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SetViewport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SetViewport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SetViewport(ctx, req.(*SetViewportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_EmulateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmulateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).EmulateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_EmulateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).EmulateDevice(ctx, req.(*EmulateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_BringToFront_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BringToFrontRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).BringToFront(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_BringToFront_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).BringToFront(ctx, req.(*BringToFrontRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ClosePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ClosePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ClosePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ClosePage(ctx, req.(*ClosePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_WaitFor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).WaitFor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_WaitFor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).WaitFor(ctx, req.(*WaitForRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GetPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetPDF(ctx, req.(*GetPDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_AddInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).AddInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_AddInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).AddInitScript(ctx, req.(*AddInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_OverridePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverridePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).OverridePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_OverridePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).OverridePermissions(ctx, req.(*OverridePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SetGeolocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGeolocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SetGeolocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SetGeolocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SetGeolocation(ctx, req.(*SetGeolocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SetOfflineMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOfflineModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SetOfflineMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SetOfflineMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SetOfflineMode(ctx, req.(*SetOfflineModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SetCacheEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCacheEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SetCacheEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SetCacheEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SetCacheEnabled(ctx, req.(*SetCacheEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_GetCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetCookies(ctx, req.(*GetCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SetCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SetCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SetCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SetCookies(ctx, req.(*SetCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ClearCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ClearCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_ClearCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ClearCookies(ctx, req.(*ClearCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PageService_ServiceDesc is the grpc.ServiceDesc for PageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chaser.oxide.v1.PageService",
	HandlerType: (*PageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _PageService_CreatePage_Handler,
		},
		{
			MethodName: "Navigate",
			Handler:    _PageService_Navigate_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _PageService_GetSnapshot_Handler,
		},
		{
			MethodName: "Screenshot",
			Handler:    _PageService_Screenshot_Handler,
		},
		{
			MethodName: "Evaluate",
			Handler:    _PageService_Evaluate_Handler,
		},
		{
			MethodName: "EvaluateOnElement",
			Handler:    _PageService_EvaluateOnElement_Handler,
		},
		{
			MethodName: "SetContent",
			Handler:    _PageService_SetContent_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _PageService_GetContent_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _PageService_Reload_Handler,
		},
		{
			MethodName: "GoBack",
			Handler:    _PageService_GoBack_Handler,
		},
		{
			MethodName: "GoForward",
			Handler:    _PageService_GoForward_Handler,
		},
		{
			MethodName: "SetViewport",
			Handler:    _PageService_SetViewport_Handler,
		},
		{
			MethodName: "EmulateDevice",
			Handler:    _PageService_EmulateDevice_Handler,
		},
		{
			MethodName: "BringToFront",
			Handler:    _PageService_BringToFront_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _PageService_GetMetrics_Handler,
		},
		{
			MethodName: "ClosePage",
			Handler:    _PageService_ClosePage_Handler,
		},
		{
			MethodName: "WaitFor",
			Handler:    _PageService_WaitFor_Handler,
		},
		{
			MethodName: "GetPDF",
			Handler:    _PageService_GetPDF_Handler,
		},
		{
			MethodName: "AddInitScript",
			Handler:    _PageService_AddInitScript_Handler,
		},
		{
			MethodName: "OverridePermissions",
			Handler:    _PageService_OverridePermissions_Handler,
		},
		{
			MethodName: "SetGeolocation",
			Handler:    _PageService_SetGeolocation_Handler,
		},
		{
			MethodName: "SetOfflineMode",
			Handler:    _PageService_SetOfflineMode_Handler,
		},
		{
			MethodName: "SetCacheEnabled",
			Handler:    _PageService_SetCacheEnabled_Handler,
		},
		{
			MethodName: "GetCookies",
			Handler:    _PageService_GetCookies_Handler,
		},
		{
			MethodName: "SetCookies",
			Handler:    _PageService_SetCookies_Handler,
		},
		{
			MethodName: "ClearCookies",
			Handler:    _PageService_ClearCookies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "page.proto",
}
