// Copyright 2026 Chaser-Oxide Server
// Stealth profile and fingerprint management service

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: profile.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileService_CreateProfile_FullMethodName       = "/chaser.oxide.v1.ProfileService/CreateProfile"
	ProfileService_ApplyProfile_FullMethodName        = "/chaser.oxide.v1.ProfileService/ApplyProfile"
	ProfileService_GetPresets_FullMethodName          = "/chaser.oxide.v1.ProfileService/GetPresets"
	ProfileService_GetActiveProfile_FullMethodName    = "/chaser.oxide.v1.ProfileService/GetActiveProfile"
	ProfileService_CreateCustomProfile_FullMethodName = "/chaser.oxide.v1.ProfileService/CreateCustomProfile"
	ProfileService_RandomizeProfile_FullMethodName    = "/chaser.oxide.v1.ProfileService/RandomizeProfile"
)

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============= ProfileService =============
// Manages browser fingerprint profiles for anti-detection
type ProfileServiceClient interface {
	// Create a new fingerprint profile
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
	// Apply a profile to a page
	ApplyProfile(ctx context.Context, in *ApplyProfileRequest, opts ...grpc.CallOption) (*ApplyProfileResponse, error)
	// Get predefined/preset profiles
	GetPresets(ctx context.Context, in *GetPresetsRequest, opts ...grpc.CallOption) (*GetPresetsResponse, error)
	// Get active profile for a page
	GetActiveProfile(ctx context.Context, in *GetActiveProfileRequest, opts ...grpc.CallOption) (*GetActiveProfileResponse, error)
	// Create custom profile from template
	CreateCustomProfile(ctx context.Context, in *CreateCustomProfileRequest, opts ...grpc.CallOption) (*CreateCustomProfileResponse, error)
	// Randomize profile for uniqueness
	RandomizeProfile(ctx context.Context, in *RandomizeProfileRequest, opts ...grpc.CallOption) (*RandomizeProfileResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ApplyProfile(ctx context.Context, in *ApplyProfileRequest, opts ...grpc.CallOption) (*ApplyProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_ApplyProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetPresets(ctx context.Context, in *GetPresetsRequest, opts ...grpc.CallOption) (*GetPresetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresetsResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetPresets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetActiveProfile(ctx context.Context, in *GetActiveProfileRequest, opts ...grpc.CallOption) (*GetActiveProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_GetActiveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) CreateCustomProfile(ctx context.Context, in *CreateCustomProfileRequest, opts ...grpc.CallOption) (*CreateCustomProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCustomProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_CreateCustomProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) RandomizeProfile(ctx context.Context, in *RandomizeProfileRequest, opts ...grpc.CallOption) (*RandomizeProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandomizeProfileResponse)
	err := c.cc.Invoke(ctx, ProfileService_RandomizeProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations must embed UnimplementedProfileServiceServer
// for forward compatibility.
//
// ============= ProfileService =============
// Manages browser fingerprint profiles for anti-detection
type ProfileServiceServer interface {
	// Create a new fingerprint profile
	CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
	// Apply a profile to a page
	ApplyProfile(context.Context, *ApplyProfileRequest) (*ApplyProfileResponse, error)
	// Get predefined/preset profiles
	GetPresets(context.Context, *GetPresetsRequest) (*GetPresetsResponse, error)
	// Get active profile for a page
	GetActiveProfile(context.Context, *GetActiveProfileRequest) (*GetActiveProfileResponse, error)
	// Create custom profile from template
	CreateCustomProfile(context.Context, *CreateCustomProfileRequest) (*CreateCustomProfileResponse, error)
	// Randomize profile for uniqueness
	RandomizeProfile(context.Context, *RandomizeProfileRequest) (*RandomizeProfileResponse, error)
	mustEmbedUnimplementedProfileServiceServer()
}

// UnimplementedProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileServiceServer struct{}

func (UnimplementedProfileServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedProfileServiceServer) ApplyProfile(context.Context, *ApplyProfileRequest) (*ApplyProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyProfile not implemented")
}
func (UnimplementedProfileServiceServer) GetPresets(context.Context, *GetPresetsRequest) (*GetPresetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresets not implemented")
}
func (UnimplementedProfileServiceServer) GetActiveProfile(context.Context, *GetActiveProfileRequest) (*GetActiveProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveProfile not implemented")
}
func (UnimplementedProfileServiceServer) CreateCustomProfile(context.Context, *CreateCustomProfileRequest) (*CreateCustomProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCustomProfile not implemented")
}
func (UnimplementedProfileServiceServer) RandomizeProfile(context.Context, *RandomizeProfileRequest) (*RandomizeProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RandomizeProfile not implemented")
}
func (UnimplementedProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {}
func (UnimplementedProfileServiceServer) testEmbeddedByValue()                        {}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ApplyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ApplyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ApplyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ApplyProfile(ctx, req.(*ApplyProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetPresets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetPresets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetPresets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetPresets(ctx, req.(*GetPresetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetActiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetActiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_GetActiveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetActiveProfile(ctx, req.(*GetActiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_CreateCustomProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateCustomProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_CreateCustomProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateCustomProfile(ctx, req.(*CreateCustomProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_RandomizeProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomizeProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).RandomizeProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_RandomizeProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).RandomizeProfile(ctx, req.(*RandomizeProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chaser.oxide.v1.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _ProfileService_CreateProfile_Handler,
		},
		{
			MethodName: "ApplyProfile",
			Handler:    _ProfileService_ApplyProfile_Handler,
		},
		{
			MethodName: "GetPresets",
			Handler:    _ProfileService_GetPresets_Handler,
		},
		{
			MethodName: "GetActiveProfile",
			Handler:    _ProfileService_GetActiveProfile_Handler,
		},
		{
			MethodName: "CreateCustomProfile",
			Handler:    _ProfileService_CreateCustomProfile_Handler,
		},
		{
			MethodName: "RandomizeProfile",
			Handler:    _ProfileService_RandomizeProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
