// Copyright 2026 Chaser-Oxide Server
// Stealth profile and fingerprint management service

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: profile.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileType int32

const (
	ProfileType_PROFILE_TYPE_UNSPECIFIED ProfileType = 0
	ProfileType_PROFILE_TYPE_WINDOWS     ProfileType = 1 // Windows fingerprint
	ProfileType_PROFILE_TYPE_LINUX       ProfileType = 2 // Linux fingerprint
	ProfileType_PROFILE_TYPE_MACOS       ProfileType = 3 // macOS fingerprint
	ProfileType_PROFILE_TYPE_ANDROID     ProfileType = 4 // Android mobile fingerprint
	ProfileType_PROFILE_TYPE_IOS         ProfileType = 5 // iOS mobile fingerprint
	ProfileType_PROFILE_TYPE_CUSTOM      ProfileType = 6 // Custom fingerprint
)

// Enum value maps for ProfileType.
var (
	ProfileType_name = map[int32]string{
		0: "PROFILE_TYPE_UNSPECIFIED",
		1: "PROFILE_TYPE_WINDOWS",
		2: "PROFILE_TYPE_LINUX",
		3: "PROFILE_TYPE_MACOS",
		4: "PROFILE_TYPE_ANDROID",
		5: "PROFILE_TYPE_IOS",
		6: "PROFILE_TYPE_CUSTOM",
	}
	ProfileType_value = map[string]int32{
		"PROFILE_TYPE_UNSPECIFIED": 0,
		"PROFILE_TYPE_WINDOWS":     1,
		"PROFILE_TYPE_LINUX":       2,
		"PROFILE_TYPE_MACOS":       3,
		"PROFILE_TYPE_ANDROID":     4,
		"PROFILE_TYPE_IOS":         5,
		"PROFILE_TYPE_CUSTOM":      6,
	}
)

func (x ProfileType) Enum() *ProfileType {
	p := new(ProfileType)
	*p = x
	return p
}

func (x ProfileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileType) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[0].Descriptor()
}

func (ProfileType) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[0]
}

func (x ProfileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileType.Descriptor instead.
func (ProfileType) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ProfileType            `protobuf:"varint,1,opt,name=type,proto3,enum=chaser.oxide.v1.ProfileType" json:"type,omitempty"` // Use predefined type
	Custom        *CustomProfileOptions  `protobuf:"bytes,2,opt,name=custom,proto3" json:"custom,omitempty"`                               // Or use custom options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileRequest) GetType() ProfileType {
	if x != nil {
		return x.Type
	}
	return ProfileType_PROFILE_TYPE_UNSPECIFIED
}

func (x *CreateProfileRequest) GetCustom() *CustomProfileOptions {
	if x != nil {
		return x.Custom
	}
	return nil
}

type CreateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CreateProfileResponse_Profile
	//	*CreateProfileResponse_Error
	Response      isCreateProfileResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileResponse) GetResponse() isCreateProfileResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateProfileResponse) GetProfile() *Profile {
	if x != nil {
		if x, ok := x.Response.(*CreateProfileResponse_Profile); ok {
			return x.Profile
		}
	}
	return nil
}

func (x *CreateProfileResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*CreateProfileResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateProfileResponse_Response interface {
	isCreateProfileResponse_Response()
}

type CreateProfileResponse_Profile struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3,oneof"`
}

type CreateProfileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateProfileResponse_Profile) isCreateProfileResponse_Response() {}

func (*CreateProfileResponse_Error) isCreateProfileResponse_Response() {}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Type          ProfileType            `protobuf:"varint,2,opt,name=type,proto3,enum=chaser.oxide.v1.ProfileType" json:"type,omitempty"`
	Fingerprint   *Fingerprint           `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Options       *ProfileOptions        `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

func (x *Profile) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Profile) GetType() ProfileType {
	if x != nil {
		return x.Type
	}
	return ProfileType_PROFILE_TYPE_UNSPECIFIED
}

func (x *Profile) GetFingerprint() *Fingerprint {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *Profile) GetOptions() *ProfileOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Profile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Fingerprint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP Headers
	Headers *HTTPHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	// Navigator properties
	Navigator *NavigatorInfo `protobuf:"bytes,2,opt,name=navigator,proto3" json:"navigator,omitempty"`
	// Screen properties
	Screen *ScreenInfo `protobuf:"bytes,3,opt,name=screen,proto3" json:"screen,omitempty"`
	// Hardware properties
	Hardware *HardwareInfo `protobuf:"bytes,4,opt,name=hardware,proto3" json:"hardware,omitempty"`
	// WebGL properties
	Webgl *WebGLInfo `protobuf:"bytes,5,opt,name=webgl,proto3" json:"webgl,omitempty"`
	// Audio properties
	Audio *AudioInfo `protobuf:"bytes,6,opt,name=audio,proto3" json:"audio,omitempty"`
	// Canvas properties
	Canvas *CanvasInfo `protobuf:"bytes,7,opt,name=canvas,proto3" json:"canvas,omitempty"`
	// Timezone and locale
	Timezone  string   `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Locale    string   `protobuf:"bytes,9,opt,name=locale,proto3" json:"locale,omitempty"`
	Languages []string `protobuf:"bytes,10,rep,name=languages,proto3" json:"languages,omitempty"`
	// Permissions
	Permissions   *Permissions `protobuf:"bytes,11,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fingerprint) Reset() {
	*x = Fingerprint{}
	mi := &file_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fingerprint) ProtoMessage() {}

func (x *Fingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fingerprint.ProtoReflect.Descriptor instead.
func (*Fingerprint) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

func (x *Fingerprint) GetHeaders() *HTTPHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Fingerprint) GetNavigator() *NavigatorInfo {
	if x != nil {
		return x.Navigator
	}
	return nil
}

func (x *Fingerprint) GetScreen() *ScreenInfo {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *Fingerprint) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *Fingerprint) GetWebgl() *WebGLInfo {
	if x != nil {
		return x.Webgl
	}
	return nil
}

func (x *Fingerprint) GetAudio() *AudioInfo {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *Fingerprint) GetCanvas() *CanvasInfo {
	if x != nil {
		return x.Canvas
	}
	return nil
}

func (x *Fingerprint) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Fingerprint) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Fingerprint) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *Fingerprint) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type HTTPHeaders struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserAgent       string                 `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	AcceptLanguage  string                 `protobuf:"bytes,2,opt,name=accept_language,json=acceptLanguage,proto3" json:"accept_language,omitempty"`
	AcceptEncoding  string                 `protobuf:"bytes,3,opt,name=accept_encoding,json=acceptEncoding,proto3" json:"accept_encoding,omitempty"`
	SecChUa         string                 `protobuf:"bytes,4,opt,name=sec_ch_ua,json=secChUa,proto3" json:"sec_ch_ua,omitempty"` // Sec-CH-UA header
	SecChUaPlatform string                 `protobuf:"bytes,5,opt,name=sec_ch_ua_platform,json=secChUaPlatform,proto3" json:"sec_ch_ua_platform,omitempty"`
	SecChUaMobile   string                 `protobuf:"bytes,6,opt,name=sec_ch_ua_mobile,json=secChUaMobile,proto3" json:"sec_ch_ua_mobile,omitempty"`
	SecChUaArch     string                 `protobuf:"bytes,7,opt,name=sec_ch_ua_arch,json=secChUaArch,proto3" json:"sec_ch_ua_arch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HTTPHeaders) Reset() {
	*x = HTTPHeaders{}
	mi := &file_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPHeaders) ProtoMessage() {}

func (x *HTTPHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPHeaders.ProtoReflect.Descriptor instead.
func (*HTTPHeaders) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{4}
}

func (x *HTTPHeaders) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *HTTPHeaders) GetAcceptLanguage() string {
	if x != nil {
		return x.AcceptLanguage
	}
	return ""
}

func (x *HTTPHeaders) GetAcceptEncoding() string {
	if x != nil {
		return x.AcceptEncoding
	}
	return ""
}

func (x *HTTPHeaders) GetSecChUa() string {
	if x != nil {
		return x.SecChUa
	}
	return ""
}

func (x *HTTPHeaders) GetSecChUaPlatform() string {
	if x != nil {
		return x.SecChUaPlatform
	}
	return ""
}

func (x *HTTPHeaders) GetSecChUaMobile() string {
	if x != nil {
		return x.SecChUaMobile
	}
	return ""
}

func (x *HTTPHeaders) GetSecChUaArch() string {
	if x != nil {
		return x.SecChUaArch
	}
	return ""
}

type NavigatorInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Platform            string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // Win32, Linux, MacIntel, etc.
	Vendor              string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`     // Usually Google Inc.
	Product             string                 `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`   // Gecko
	AppVersion          string                 `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	AppName             string                 `protobuf:"bytes,5,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`                                      // Netscape
	AppCodeName         string                 `protobuf:"bytes,6,opt,name=app_code_name,json=appCodeName,proto3" json:"app_code_name,omitempty"`                        // Mozilla
	HardwareConcurrency bool                   `protobuf:"varint,7,opt,name=hardware_concurrency,json=hardwareConcurrency,proto3" json:"hardware_concurrency,omitempty"` // CPU cores
	DeviceMemory        int32                  `protobuf:"varint,8,opt,name=device_memory,json=deviceMemory,proto3" json:"device_memory,omitempty"`                      // RAM in GB
	Language            string                 `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	Languages           []string               `protobuf:"bytes,10,rep,name=languages,proto3" json:"languages,omitempty"`
	DoNotTrack          bool                   `protobuf:"varint,11,opt,name=do_not_track,json=doNotTrack,proto3" json:"do_not_track,omitempty"`
	CookieEnabled       string                 `protobuf:"bytes,12,opt,name=cookie_enabled,json=cookieEnabled,proto3" json:"cookie_enabled,omitempty"`
	PdfViewerEnabled    bool                   `protobuf:"varint,13,opt,name=pdf_viewer_enabled,json=pdfViewerEnabled,proto3" json:"pdf_viewer_enabled,omitempty"`
	Webdriver           bool                   `protobuf:"varint,14,opt,name=webdriver,proto3" json:"webdriver,omitempty"` // Should be false for stealth
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NavigatorInfo) Reset() {
	*x = NavigatorInfo{}
	mi := &file_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigatorInfo) ProtoMessage() {}

func (x *NavigatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigatorInfo.ProtoReflect.Descriptor instead.
func (*NavigatorInfo) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{5}
}

func (x *NavigatorInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *NavigatorInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *NavigatorInfo) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *NavigatorInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *NavigatorInfo) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *NavigatorInfo) GetAppCodeName() string {
	if x != nil {
		return x.AppCodeName
	}
	return ""
}

func (x *NavigatorInfo) GetHardwareConcurrency() bool {
	if x != nil {
		return x.HardwareConcurrency
	}
	return false
}

func (x *NavigatorInfo) GetDeviceMemory() int32 {
	if x != nil {
		return x.DeviceMemory
	}
	return 0
}

func (x *NavigatorInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *NavigatorInfo) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *NavigatorInfo) GetDoNotTrack() bool {
	if x != nil {
		return x.DoNotTrack
	}
	return false
}

func (x *NavigatorInfo) GetCookieEnabled() string {
	if x != nil {
		return x.CookieEnabled
	}
	return ""
}

func (x *NavigatorInfo) GetPdfViewerEnabled() bool {
	if x != nil {
		return x.PdfViewerEnabled
	}
	return false
}

func (x *NavigatorInfo) GetWebdriver() bool {
	if x != nil {
		return x.Webdriver
	}
	return false
}

type ScreenInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Width            int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height           int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	AvailWidth       int32                  `protobuf:"varint,3,opt,name=avail_width,json=availWidth,proto3" json:"avail_width,omitempty"`
	AvailHeight      int32                  `protobuf:"varint,4,opt,name=avail_height,json=availHeight,proto3" json:"avail_height,omitempty"`
	ColorDepth       int32                  `protobuf:"varint,5,opt,name=color_depth,json=colorDepth,proto3" json:"color_depth,omitempty"`
	PixelDepth       int32                  `protobuf:"varint,6,opt,name=pixel_depth,json=pixelDepth,proto3" json:"pixel_depth,omitempty"`
	Top              int32                  `protobuf:"varint,7,opt,name=top,proto3" json:"top,omitempty"`
	Left             int32                  `protobuf:"varint,8,opt,name=left,proto3" json:"left,omitempty"`
	DevicePixelRatio float64                `protobuf:"fixed64,9,opt,name=device_pixel_ratio,json=devicePixelRatio,proto3" json:"device_pixel_ratio,omitempty"`
	Orientation      bool                   `protobuf:"varint,10,opt,name=orientation,proto3" json:"orientation,omitempty"` // true=portrait, false=landscape
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScreenInfo) Reset() {
	*x = ScreenInfo{}
	mi := &file_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenInfo) ProtoMessage() {}

func (x *ScreenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenInfo.ProtoReflect.Descriptor instead.
func (*ScreenInfo) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{6}
}

func (x *ScreenInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ScreenInfo) GetAvailWidth() int32 {
	if x != nil {
		return x.AvailWidth
	}
	return 0
}

func (x *ScreenInfo) GetAvailHeight() int32 {
	if x != nil {
		return x.AvailHeight
	}
	return 0
}

func (x *ScreenInfo) GetColorDepth() int32 {
	if x != nil {
		return x.ColorDepth
	}
	return 0
}

func (x *ScreenInfo) GetPixelDepth() int32 {
	if x != nil {
		return x.PixelDepth
	}
	return 0
}

func (x *ScreenInfo) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *ScreenInfo) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *ScreenInfo) GetDevicePixelRatio() float64 {
	if x != nil {
		return x.DevicePixelRatio
	}
	return 0
}

func (x *ScreenInfo) GetOrientation() bool {
	if x != nil {
		return x.Orientation
	}
	return false
}

type HardwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	DeviceMemory  int32                  `protobuf:"varint,2,opt,name=device_memory,json=deviceMemory,proto3" json:"device_memory,omitempty"` // RAM in GB
	GpuVendor     string                 `protobuf:"bytes,3,opt,name=gpu_vendor,json=gpuVendor,proto3" json:"gpu_vendor,omitempty"`
	GpuRenderer   string                 `protobuf:"bytes,4,opt,name=gpu_renderer,json=gpuRenderer,proto3" json:"gpu_renderer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{7}
}

func (x *HardwareInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HardwareInfo) GetDeviceMemory() int32 {
	if x != nil {
		return x.DeviceMemory
	}
	return 0
}

func (x *HardwareInfo) GetGpuVendor() string {
	if x != nil {
		return x.GpuVendor
	}
	return ""
}

func (x *HardwareInfo) GetGpuRenderer() string {
	if x != nil {
		return x.GpuRenderer
	}
	return ""
}

type WebGLInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Vendor                 string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`     // GPU vendor
	Renderer               string                 `protobuf:"bytes,2,opt,name=renderer,proto3" json:"renderer,omitempty"` // GPU renderer
	Version                string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`   // WebGL version
	ShadingLanguageVersion string                 `protobuf:"bytes,4,opt,name=shading_language_version,json=shadingLanguageVersion,proto3" json:"shading_language_version,omitempty"`
	MaxTextureSize         int32                  `protobuf:"varint,5,opt,name=max_texture_size,json=maxTextureSize,proto3" json:"max_texture_size,omitempty"`
	Extensions             []string               `protobuf:"bytes,6,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Webgl2                 bool                   `protobuf:"varint,7,opt,name=webgl2,proto3" json:"webgl2,omitempty"` // WebGL 2.0 support
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WebGLInfo) Reset() {
	*x = WebGLInfo{}
	mi := &file_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebGLInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGLInfo) ProtoMessage() {}

func (x *WebGLInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGLInfo.ProtoReflect.Descriptor instead.
func (*WebGLInfo) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{8}
}

func (x *WebGLInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *WebGLInfo) GetRenderer() string {
	if x != nil {
		return x.Renderer
	}
	return ""
}

func (x *WebGLInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WebGLInfo) GetShadingLanguageVersion() string {
	if x != nil {
		return x.ShadingLanguageVersion
	}
	return ""
}

func (x *WebGLInfo) GetMaxTextureSize() int32 {
	if x != nil {
		return x.MaxTextureSize
	}
	return 0
}

func (x *WebGLInfo) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *WebGLInfo) GetWebgl2() bool {
	if x != nil {
		return x.Webgl2
	}
	return false
}

type AudioInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextCount  int32                  `protobuf:"varint,1,opt,name=context_count,json=contextCount,proto3" json:"context_count,omitempty"` // Number of AudioContexts
	AudioContext  string                 `protobuf:"bytes,2,opt,name=audio_context,json=audioContext,proto3" json:"audio_context,omitempty"`  // BaseAudioContext fingerprint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioInfo) Reset() {
	*x = AudioInfo{}
	mi := &file_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioInfo) ProtoMessage() {}

func (x *AudioInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioInfo.ProtoReflect.Descriptor instead.
func (*AudioInfo) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{9}
}

func (x *AudioInfo) GetContextCount() int32 {
	if x != nil {
		return x.ContextCount
	}
	return 0
}

func (x *AudioInfo) GetAudioContext() string {
	if x != nil {
		return x.AudioContext
	}
	return ""
}

type CanvasInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CanvasFingerprint bool                   `protobuf:"varint,1,opt,name=canvas_fingerprint,json=canvasFingerprint,proto3" json:"canvas_fingerprint,omitempty"` // Canvas fingerprinting detection
	CanvasRenderer    string                 `protobuf:"bytes,2,opt,name=canvas_renderer,json=canvasRenderer,proto3" json:"canvas_renderer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CanvasInfo) Reset() {
	*x = CanvasInfo{}
	mi := &file_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanvasInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasInfo) ProtoMessage() {}

func (x *CanvasInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasInfo.ProtoReflect.Descriptor instead.
func (*CanvasInfo) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{10}
}

func (x *CanvasInfo) GetCanvasFingerprint() bool {
	if x != nil {
		return x.CanvasFingerprint
	}
	return false
}

func (x *CanvasInfo) GetCanvasRenderer() string {
	if x != nil {
		return x.CanvasRenderer
	}
	return ""
}

type Permissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geolocation   bool                   `protobuf:"varint,1,opt,name=geolocation,proto3" json:"geolocation,omitempty"`
	Notifications bool                   `protobuf:"varint,2,opt,name=notifications,proto3" json:"notifications,omitempty"`
	Camera        bool                   `protobuf:"varint,3,opt,name=camera,proto3" json:"camera,omitempty"`
	Microphone    bool                   `protobuf:"varint,4,opt,name=microphone,proto3" json:"microphone,omitempty"`
	Midi          bool                   `protobuf:"varint,5,opt,name=midi,proto3" json:"midi,omitempty"`
	Bluetooth     bool                   `protobuf:"varint,6,opt,name=bluetooth,proto3" json:"bluetooth,omitempty"`
	Usb           bool                   `protobuf:"varint,7,opt,name=usb,proto3" json:"usb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{11}
}

func (x *Permissions) GetGeolocation() bool {
	if x != nil {
		return x.Geolocation
	}
	return false
}

func (x *Permissions) GetNotifications() bool {
	if x != nil {
		return x.Notifications
	}
	return false
}

func (x *Permissions) GetCamera() bool {
	if x != nil {
		return x.Camera
	}
	return false
}

func (x *Permissions) GetMicrophone() bool {
	if x != nil {
		return x.Microphone
	}
	return false
}

func (x *Permissions) GetMidi() bool {
	if x != nil {
		return x.Midi
	}
	return false
}

func (x *Permissions) GetBluetooth() bool {
	if x != nil {
		return x.Bluetooth
	}
	return false
}

func (x *Permissions) GetUsb() bool {
	if x != nil {
		return x.Usb
	}
	return false
}

type ProfileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Script injection options
	InjectNavigator bool `protobuf:"varint,1,opt,name=inject_navigator,json=injectNavigator,proto3" json:"inject_navigator,omitempty"` // Inject navigator properties
	InjectScreen    bool `protobuf:"varint,2,opt,name=inject_screen,json=injectScreen,proto3" json:"inject_screen,omitempty"`          // Inject screen properties
	InjectWebgl     bool `protobuf:"varint,3,opt,name=inject_webgl,json=injectWebgl,proto3" json:"inject_webgl,omitempty"`             // Inject WebGL properties
	InjectCanvas    bool `protobuf:"varint,4,opt,name=inject_canvas,json=injectCanvas,proto3" json:"inject_canvas,omitempty"`          // Inject canvas protection
	InjectAudio     bool `protobuf:"varint,5,opt,name=inject_audio,json=injectAudio,proto3" json:"inject_audio,omitempty"`             // Inject audio fingerprint protection
	// Transport layer stealth
	NeutralizeUtilityWorld bool `protobuf:"varint,6,opt,name=neutralize_utility_world,json=neutralizeUtilityWorld,proto3" json:"neutralize_utility_world,omitempty"` // Neutralize utility world names
	UseIsolatedWorld       bool `protobuf:"varint,7,opt,name=use_isolated_world,json=useIsolatedWorld,proto3" json:"use_isolated_world,omitempty"`                   // Use Page.createIsolatedWorld
	// Additional options
	RandomizeMetrics bool `protobuf:"varint,8,opt,name=randomize_metrics,json=randomizeMetrics,proto3" json:"randomize_metrics,omitempty"` // Randomize timing metrics
	PreventDetection bool `protobuf:"varint,9,opt,name=prevent_detection,json=preventDetection,proto3" json:"prevent_detection,omitempty"` // Prevent bot detection scripts
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProfileOptions) Reset() {
	*x = ProfileOptions{}
	mi := &file_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileOptions) ProtoMessage() {}

func (x *ProfileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileOptions.ProtoReflect.Descriptor instead.
func (*ProfileOptions) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{12}
}

func (x *ProfileOptions) GetInjectNavigator() bool {
	if x != nil {
		return x.InjectNavigator
	}
	return false
}

func (x *ProfileOptions) GetInjectScreen() bool {
	if x != nil {
		return x.InjectScreen
	}
	return false
}

func (x *ProfileOptions) GetInjectWebgl() bool {
	if x != nil {
		return x.InjectWebgl
	}
	return false
}

func (x *ProfileOptions) GetInjectCanvas() bool {
	if x != nil {
		return x.InjectCanvas
	}
	return false
}

func (x *ProfileOptions) GetInjectAudio() bool {
	if x != nil {
		return x.InjectAudio
	}
	return false
}

func (x *ProfileOptions) GetNeutralizeUtilityWorld() bool {
	if x != nil {
		return x.NeutralizeUtilityWorld
	}
	return false
}

func (x *ProfileOptions) GetUseIsolatedWorld() bool {
	if x != nil {
		return x.UseIsolatedWorld
	}
	return false
}

func (x *ProfileOptions) GetRandomizeMetrics() bool {
	if x != nil {
		return x.RandomizeMetrics
	}
	return false
}

func (x *ProfileOptions) GetPreventDetection() bool {
	if x != nil {
		return x.PreventDetection
	}
	return false
}

type CustomProfileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User agent
	UserAgent string `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Platform
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// Screen
	ScreenWidth      int32   `protobuf:"varint,3,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight     int32   `protobuf:"varint,4,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	DevicePixelRatio float64 `protobuf:"fixed64,5,opt,name=device_pixel_ratio,json=devicePixelRatio,proto3" json:"device_pixel_ratio,omitempty"`
	// Hardware
	CpuCores     int32 `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	DeviceMemory int32 `protobuf:"varint,7,opt,name=device_memory,json=deviceMemory,proto3" json:"device_memory,omitempty"`
	// Language
	Locale    string   `protobuf:"bytes,8,opt,name=locale,proto3" json:"locale,omitempty"`
	Languages []string `protobuf:"bytes,9,rep,name=languages,proto3" json:"languages,omitempty"`
	Timezone  string   `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// WebGL
	WebglVendor   string `protobuf:"bytes,11,opt,name=webgl_vendor,json=webglVendor,proto3" json:"webgl_vendor,omitempty"`
	WebglRenderer string `protobuf:"bytes,12,opt,name=webgl_renderer,json=webglRenderer,proto3" json:"webgl_renderer,omitempty"`
	// Navigator
	NavigatorVendor  string `protobuf:"bytes,13,opt,name=navigator_vendor,json=navigatorVendor,proto3" json:"navigator_vendor,omitempty"`
	NavigatorProduct string `protobuf:"bytes,14,opt,name=navigator_product,json=navigatorProduct,proto3" json:"navigator_product,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CustomProfileOptions) Reset() {
	*x = CustomProfileOptions{}
	mi := &file_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomProfileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomProfileOptions) ProtoMessage() {}

func (x *CustomProfileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomProfileOptions.ProtoReflect.Descriptor instead.
func (*CustomProfileOptions) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{13}
}

func (x *CustomProfileOptions) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *CustomProfileOptions) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CustomProfileOptions) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *CustomProfileOptions) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *CustomProfileOptions) GetDevicePixelRatio() float64 {
	if x != nil {
		return x.DevicePixelRatio
	}
	return 0
}

func (x *CustomProfileOptions) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *CustomProfileOptions) GetDeviceMemory() int32 {
	if x != nil {
		return x.DeviceMemory
	}
	return 0
}

func (x *CustomProfileOptions) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CustomProfileOptions) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *CustomProfileOptions) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CustomProfileOptions) GetWebglVendor() string {
	if x != nil {
		return x.WebglVendor
	}
	return ""
}

func (x *CustomProfileOptions) GetWebglRenderer() string {
	if x != nil {
		return x.WebglRenderer
	}
	return ""
}

func (x *CustomProfileOptions) GetNavigatorVendor() string {
	if x != nil {
		return x.NavigatorVendor
	}
	return ""
}

func (x *CustomProfileOptions) GetNavigatorProduct() string {
	if x != nil {
		return x.NavigatorProduct
	}
	return ""
}

type ApplyProfileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PageId           string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	ProfileId        string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`                       // Profile to apply
	OverrideExisting bool                   `protobuf:"varint,3,opt,name=override_existing,json=overrideExisting,proto3" json:"override_existing,omitempty"` // Override existing profile
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyProfileRequest) Reset() {
	*x = ApplyProfileRequest{}
	mi := &file_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProfileRequest) ProtoMessage() {}

func (x *ApplyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProfileRequest.ProtoReflect.Descriptor instead.
func (*ApplyProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{14}
}

func (x *ApplyProfileRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ApplyProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ApplyProfileRequest) GetOverrideExisting() bool {
	if x != nil {
		return x.OverrideExisting
	}
	return false
}

type ApplyProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ApplyProfileResponse_Result
	//	*ApplyProfileResponse_Error
	Response      isApplyProfileResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyProfileResponse) Reset() {
	*x = ApplyProfileResponse{}
	mi := &file_profile_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProfileResponse) ProtoMessage() {}

func (x *ApplyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProfileResponse.ProtoReflect.Descriptor instead.
func (*ApplyProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyProfileResponse) GetResponse() isApplyProfileResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ApplyProfileResponse) GetResult() *ApplyProfileResult {
	if x != nil {
		if x, ok := x.Response.(*ApplyProfileResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ApplyProfileResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*ApplyProfileResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isApplyProfileResponse_Response interface {
	isApplyProfileResponse_Response()
}

type ApplyProfileResponse_Result struct {
	Result *ApplyProfileResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type ApplyProfileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ApplyProfileResponse_Result) isApplyProfileResponse_Response() {}

func (*ApplyProfileResponse_Error) isApplyProfileResponse_Response() {}

type ApplyProfileResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PageId          string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	ProfileId       string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	AppliedFeatures []string               `protobuf:"bytes,4,rep,name=applied_features,json=appliedFeatures,proto3" json:"applied_features,omitempty"` // Features that were applied
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyProfileResult) Reset() {
	*x = ApplyProfileResult{}
	mi := &file_profile_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyProfileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyProfileResult) ProtoMessage() {}

func (x *ApplyProfileResult) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyProfileResult.ProtoReflect.Descriptor instead.
func (*ApplyProfileResult) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyProfileResult) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ApplyProfileResult) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ApplyProfileResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyProfileResult) GetAppliedFeatures() []string {
	if x != nil {
		return x.AppliedFeatures
	}
	return nil
}

type GetPresetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ProfileType            `protobuf:"varint,1,opt,name=type,proto3,enum=chaser.oxide.v1.ProfileType" json:"type,omitempty"` // Filter by type (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresetsRequest) Reset() {
	*x = GetPresetsRequest{}
	mi := &file_profile_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresetsRequest) ProtoMessage() {}

func (x *GetPresetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresetsRequest.ProtoReflect.Descriptor instead.
func (*GetPresetsRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{17}
}

func (x *GetPresetsRequest) GetType() ProfileType {
	if x != nil {
		return x.Type
	}
	return ProfileType_PROFILE_TYPE_UNSPECIFIED
}

type GetPresetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetPresetsResponse_Presets
	//	*GetPresetsResponse_Error
	Response      isGetPresetsResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresetsResponse) Reset() {
	*x = GetPresetsResponse{}
	mi := &file_profile_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresetsResponse) ProtoMessage() {}

func (x *GetPresetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresetsResponse.ProtoReflect.Descriptor instead.
func (*GetPresetsResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{18}
}

func (x *GetPresetsResponse) GetResponse() isGetPresetsResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetPresetsResponse) GetPresets() *PresetProfiles {
	if x != nil {
		if x, ok := x.Response.(*GetPresetsResponse_Presets); ok {
			return x.Presets
		}
	}
	return nil
}

func (x *GetPresetsResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*GetPresetsResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetPresetsResponse_Response interface {
	isGetPresetsResponse_Response()
}

type GetPresetsResponse_Presets struct {
	Presets *PresetProfiles `protobuf:"bytes,1,opt,name=presets,proto3,oneof"`
}

type GetPresetsResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetPresetsResponse_Presets) isGetPresetsResponse_Response() {}

func (*GetPresetsResponse_Error) isGetPresetsResponse_Response() {}

type PresetProfiles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presets       []*Profile             `protobuf:"bytes,1,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetProfiles) Reset() {
	*x = PresetProfiles{}
	mi := &file_profile_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetProfiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetProfiles) ProtoMessage() {}

func (x *PresetProfiles) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetProfiles.ProtoReflect.Descriptor instead.
func (*PresetProfiles) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{19}
}

func (x *PresetProfiles) GetPresets() []*Profile {
	if x != nil {
		return x.Presets
	}
	return nil
}

type GetActiveProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveProfileRequest) Reset() {
	*x = GetActiveProfileRequest{}
	mi := &file_profile_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveProfileRequest) ProtoMessage() {}

func (x *GetActiveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveProfileRequest.ProtoReflect.Descriptor instead.
func (*GetActiveProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{20}
}

func (x *GetActiveProfileRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type GetActiveProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetActiveProfileResponse_Profile
	//	*GetActiveProfileResponse_Error
	Response      isGetActiveProfileResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveProfileResponse) Reset() {
	*x = GetActiveProfileResponse{}
	mi := &file_profile_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveProfileResponse) ProtoMessage() {}

func (x *GetActiveProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveProfileResponse.ProtoReflect.Descriptor instead.
func (*GetActiveProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{21}
}

func (x *GetActiveProfileResponse) GetResponse() isGetActiveProfileResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetActiveProfileResponse) GetProfile() *Profile {
	if x != nil {
		if x, ok := x.Response.(*GetActiveProfileResponse_Profile); ok {
			return x.Profile
		}
	}
	return nil
}

func (x *GetActiveProfileResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*GetActiveProfileResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetActiveProfileResponse_Response interface {
	isGetActiveProfileResponse_Response()
}

type GetActiveProfileResponse_Profile struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3,oneof"`
}

type GetActiveProfileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetActiveProfileResponse_Profile) isGetActiveProfileResponse_Response() {}

func (*GetActiveProfileResponse_Error) isGetActiveProfileResponse_Response() {}

type CreateCustomProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProfileName    string                 `protobuf:"bytes,1,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	Template       ProfileType            `protobuf:"varint,2,opt,name=template,proto3,enum=chaser.oxide.v1.ProfileType" json:"template,omitempty"` // Base template to customize
	Options        *CustomProfileOptions  `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	ProfileOptions *ProfileOptions        `protobuf:"bytes,4,opt,name=profile_options,json=profileOptions,proto3" json:"profile_options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCustomProfileRequest) Reset() {
	*x = CreateCustomProfileRequest{}
	mi := &file_profile_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomProfileRequest) ProtoMessage() {}

func (x *CreateCustomProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{22}
}

func (x *CreateCustomProfileRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *CreateCustomProfileRequest) GetTemplate() ProfileType {
	if x != nil {
		return x.Template
	}
	return ProfileType_PROFILE_TYPE_UNSPECIFIED
}

func (x *CreateCustomProfileRequest) GetOptions() *CustomProfileOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateCustomProfileRequest) GetProfileOptions() *ProfileOptions {
	if x != nil {
		return x.ProfileOptions
	}
	return nil
}

type CreateCustomProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CreateCustomProfileResponse_Profile
	//	*CreateCustomProfileResponse_Error
	Response      isCreateCustomProfileResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomProfileResponse) Reset() {
	*x = CreateCustomProfileResponse{}
	mi := &file_profile_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomProfileResponse) ProtoMessage() {}

func (x *CreateCustomProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{23}
}

func (x *CreateCustomProfileResponse) GetResponse() isCreateCustomProfileResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateCustomProfileResponse) GetProfile() *Profile {
	if x != nil {
		if x, ok := x.Response.(*CreateCustomProfileResponse_Profile); ok {
			return x.Profile
		}
	}
	return nil
}

func (x *CreateCustomProfileResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*CreateCustomProfileResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateCustomProfileResponse_Response interface {
	isCreateCustomProfileResponse_Response()
}

type CreateCustomProfileResponse_Profile struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3,oneof"`
}

type CreateCustomProfileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateCustomProfileResponse_Profile) isCreateCustomProfileResponse_Response() {}

func (*CreateCustomProfileResponse_Error) isCreateCustomProfileResponse_Response() {}

type RandomizeProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ProfileType            `protobuf:"varint,1,opt,name=type,proto3,enum=chaser.oxide.v1.ProfileType" json:"type,omitempty"` // Base type to randomize
	Options       *RandomizationOptions  `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomizeProfileRequest) Reset() {
	*x = RandomizeProfileRequest{}
	mi := &file_profile_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomizeProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomizeProfileRequest) ProtoMessage() {}

func (x *RandomizeProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomizeProfileRequest.ProtoReflect.Descriptor instead.
func (*RandomizeProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{24}
}

func (x *RandomizeProfileRequest) GetType() ProfileType {
	if x != nil {
		return x.Type
	}
	return ProfileType_PROFILE_TYPE_UNSPECIFIED
}

func (x *RandomizeProfileRequest) GetOptions() *RandomizationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type RandomizationOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RandomizeScreen   bool                   `protobuf:"varint,1,opt,name=randomize_screen,json=randomizeScreen,proto3" json:"randomize_screen,omitempty"`       // Randomize screen resolution within type
	RandomizeTimezone bool                   `protobuf:"varint,2,opt,name=randomize_timezone,json=randomizeTimezone,proto3" json:"randomize_timezone,omitempty"` // Randomize timezone within region
	RandomizeLanguage bool                   `protobuf:"varint,3,opt,name=randomize_language,json=randomizeLanguage,proto3" json:"randomize_language,omitempty"` // Randomize language variant
	RandomizeWebgl    bool                   `protobuf:"varint,4,opt,name=randomize_webgl,json=randomizeWebgl,proto3" json:"randomize_webgl,omitempty"`          // Randomize WebGL details
	Entropy           float64                `protobuf:"fixed64,5,opt,name=entropy,proto3" json:"entropy,omitempty"`                                             // Randomization entropy (0.0-1.0)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RandomizationOptions) Reset() {
	*x = RandomizationOptions{}
	mi := &file_profile_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomizationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomizationOptions) ProtoMessage() {}

func (x *RandomizationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomizationOptions.ProtoReflect.Descriptor instead.
func (*RandomizationOptions) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{25}
}

func (x *RandomizationOptions) GetRandomizeScreen() bool {
	if x != nil {
		return x.RandomizeScreen
	}
	return false
}

func (x *RandomizationOptions) GetRandomizeTimezone() bool {
	if x != nil {
		return x.RandomizeTimezone
	}
	return false
}

func (x *RandomizationOptions) GetRandomizeLanguage() bool {
	if x != nil {
		return x.RandomizeLanguage
	}
	return false
}

func (x *RandomizationOptions) GetRandomizeWebgl() bool {
	if x != nil {
		return x.RandomizeWebgl
	}
	return false
}

func (x *RandomizationOptions) GetEntropy() float64 {
	if x != nil {
		return x.Entropy
	}
	return 0
}

type RandomizeProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*RandomizeProfileResponse_Profile
	//	*RandomizeProfileResponse_Error
	Response      isRandomizeProfileResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomizeProfileResponse) Reset() {
	*x = RandomizeProfileResponse{}
	mi := &file_profile_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomizeProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomizeProfileResponse) ProtoMessage() {}

func (x *RandomizeProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomizeProfileResponse.ProtoReflect.Descriptor instead.
func (*RandomizeProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{26}
}

func (x *RandomizeProfileResponse) GetResponse() isRandomizeProfileResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RandomizeProfileResponse) GetProfile() *Profile {
	if x != nil {
		if x, ok := x.Response.(*RandomizeProfileResponse_Profile); ok {
			return x.Profile
		}
	}
	return nil
}

func (x *RandomizeProfileResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*RandomizeProfileResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRandomizeProfileResponse_Response interface {
	isRandomizeProfileResponse_Response()
}

type RandomizeProfileResponse_Profile struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3,oneof"`
}

type RandomizeProfileResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RandomizeProfileResponse_Profile) isRandomizeProfileResponse_Response() {}

func (*RandomizeProfileResponse_Error) isRandomizeProfileResponse_Response() {}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\x0fchaser.oxide.v1\x1a\fcommon.proto\"\x87\x01\n" +
	"\x14CreateProfileRequest\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.chaser.oxide.v1.ProfileTypeR\x04type\x12=\n" +
	"\x06custom\x18\x02 \x01(\v2%.chaser.oxide.v1.CustomProfileOptionsR\x06custom\"\x89\x01\n" +
	"\x15CreateProfileResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.chaser.oxide.v1.ProfileH\x00R\aprofile\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.chaser.oxide.v1.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xf4\x01\n" +
	"\aProfile\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.chaser.oxide.v1.ProfileTypeR\x04type\x12>\n" +
	"\vfingerprint\x18\x03 \x01(\v2\x1c.chaser.oxide.v1.FingerprintR\vfingerprint\x129\n" +
	"\aoptions\x18\x04 \x01(\v2\x1f.chaser.oxide.v1.ProfileOptionsR\aoptions\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\x9e\x04\n" +
	"\vFingerprint\x126\n" +
	"\aheaders\x18\x01 \x01(\v2\x1c.chaser.oxide.v1.HTTPHeadersR\aheaders\x12<\n" +
	"\tnavigator\x18\x02 \x01(\v2\x1e.chaser.oxide.v1.NavigatorInfoR\tnavigator\x123\n" +
	"\x06screen\x18\x03 \x01(\v2\x1b.chaser.oxide.v1.ScreenInfoR\x06screen\x129\n" +
	"\bhardware\x18\x04 \x01(\v2\x1d.chaser.oxide.v1.HardwareInfoR\bhardware\x120\n" +
	"\x05webgl\x18\x05 \x01(\v2\x1a.chaser.oxide.v1.WebGLInfoR\x05webgl\x120\n" +
	"\x05audio\x18\x06 \x01(\v2\x1a.chaser.oxide.v1.AudioInfoR\x05audio\x123\n" +
	"\x06canvas\x18\a \x01(\v2\x1b.chaser.oxide.v1.CanvasInfoR\x06canvas\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12\x16\n" +
	"\x06locale\x18\t \x01(\tR\x06locale\x12\x1c\n" +
	"\tlanguages\x18\n" +
	" \x03(\tR\tlanguages\x12>\n" +
	"\vpermissions\x18\v \x01(\v2\x1c.chaser.oxide.v1.PermissionsR\vpermissions\"\x95\x02\n" +
	"\vHTTPHeaders\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\tR\tuserAgent\x12'\n" +
	"\x0faccept_language\x18\x02 \x01(\tR\x0eacceptLanguage\x12'\n" +
	"\x0faccept_encoding\x18\x03 \x01(\tR\x0eacceptEncoding\x12\x1a\n" +
	"\tsec_ch_ua\x18\x04 \x01(\tR\asecChUa\x12+\n" +
	"\x12sec_ch_ua_platform\x18\x05 \x01(\tR\x0fsecChUaPlatform\x12'\n" +
	"\x10sec_ch_ua_mobile\x18\x06 \x01(\tR\rsecChUaMobile\x12#\n" +
	"\x0esec_ch_ua_arch\x18\a \x01(\tR\vsecChUaArch\"\xe4\x03\n" +
	"\rNavigatorInfo\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x18\n" +
	"\aproduct\x18\x03 \x01(\tR\aproduct\x12\x1f\n" +
	"\vapp_version\x18\x04 \x01(\tR\n" +
	"appVersion\x12\x19\n" +
	"\bapp_name\x18\x05 \x01(\tR\aappName\x12\"\n" +
	"\rapp_code_name\x18\x06 \x01(\tR\vappCodeName\x121\n" +
	"\x14hardware_concurrency\x18\a \x01(\bR\x13hardwareConcurrency\x12#\n" +
	"\rdevice_memory\x18\b \x01(\x05R\fdeviceMemory\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\x12\x1c\n" +
	"\tlanguages\x18\n" +
	" \x03(\tR\tlanguages\x12 \n" +
	"\fdo_not_track\x18\v \x01(\bR\n" +
	"doNotTrack\x12%\n" +
	"\x0ecookie_enabled\x18\f \x01(\tR\rcookieEnabled\x12,\n" +
	"\x12pdf_viewer_enabled\x18\r \x01(\bR\x10pdfViewerEnabled\x12\x1c\n" +
	"\twebdriver\x18\x0e \x01(\bR\twebdriver\"\xb6\x02\n" +
	"\n" +
	"ScreenInfo\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x1f\n" +
	"\vavail_width\x18\x03 \x01(\x05R\n" +
	"availWidth\x12!\n" +
	"\favail_height\x18\x04 \x01(\x05R\vavailHeight\x12\x1f\n" +
	"\vcolor_depth\x18\x05 \x01(\x05R\n" +
	"colorDepth\x12\x1f\n" +
	"\vpixel_depth\x18\x06 \x01(\x05R\n" +
	"pixelDepth\x12\x10\n" +
	"\x03top\x18\a \x01(\x05R\x03top\x12\x12\n" +
	"\x04left\x18\b \x01(\x05R\x04left\x12,\n" +
	"\x12device_pixel_ratio\x18\t \x01(\x01R\x10devicePixelRatio\x12 \n" +
	"\vorientation\x18\n" +
	" \x01(\bR\vorientation\"\x92\x01\n" +
	"\fHardwareInfo\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12#\n" +
	"\rdevice_memory\x18\x02 \x01(\x05R\fdeviceMemory\x12\x1d\n" +
	"\n" +
	"gpu_vendor\x18\x03 \x01(\tR\tgpuVendor\x12!\n" +
	"\fgpu_renderer\x18\x04 \x01(\tR\vgpuRenderer\"\xf5\x01\n" +
	"\tWebGLInfo\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x1a\n" +
	"\brenderer\x18\x02 \x01(\tR\brenderer\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\x18shading_language_version\x18\x04 \x01(\tR\x16shadingLanguageVersion\x12(\n" +
	"\x10max_texture_size\x18\x05 \x01(\x05R\x0emaxTextureSize\x12\x1e\n" +
	"\n" +
	"extensions\x18\x06 \x03(\tR\n" +
	"extensions\x12\x16\n" +
	"\x06webgl2\x18\a \x01(\bR\x06webgl2\"U\n" +
	"\tAudioInfo\x12#\n" +
	"\rcontext_count\x18\x01 \x01(\x05R\fcontextCount\x12#\n" +
	"\raudio_context\x18\x02 \x01(\tR\faudioContext\"d\n" +
	"\n" +
	"CanvasInfo\x12-\n" +
	"\x12canvas_fingerprint\x18\x01 \x01(\bR\x11canvasFingerprint\x12'\n" +
	"\x0fcanvas_renderer\x18\x02 \x01(\tR\x0ecanvasRenderer\"\xd1\x01\n" +
	"\vPermissions\x12 \n" +
	"\vgeolocation\x18\x01 \x01(\bR\vgeolocation\x12$\n" +
	"\rnotifications\x18\x02 \x01(\bR\rnotifications\x12\x16\n" +
	"\x06camera\x18\x03 \x01(\bR\x06camera\x12\x1e\n" +
	"\n" +
	"microphone\x18\x04 \x01(\bR\n" +
	"microphone\x12\x12\n" +
	"\x04midi\x18\x05 \x01(\bR\x04midi\x12\x1c\n" +
	"\tbluetooth\x18\x06 \x01(\bR\tbluetooth\x12\x10\n" +
	"\x03usb\x18\a \x01(\bR\x03usb\"\x8d\x03\n" +
	"\x0eProfileOptions\x12)\n" +
	"\x10inject_navigator\x18\x01 \x01(\bR\x0finjectNavigator\x12#\n" +
	"\rinject_screen\x18\x02 \x01(\bR\finjectScreen\x12!\n" +
	"\finject_webgl\x18\x03 \x01(\bR\vinjectWebgl\x12#\n" +
	"\rinject_canvas\x18\x04 \x01(\bR\finjectCanvas\x12!\n" +
	"\finject_audio\x18\x05 \x01(\bR\vinjectAudio\x128\n" +
	"\x18neutralize_utility_world\x18\x06 \x01(\bR\x16neutralizeUtilityWorld\x12,\n" +
	"\x12use_isolated_world\x18\a \x01(\bR\x10useIsolatedWorld\x12+\n" +
	"\x11randomize_metrics\x18\b \x01(\bR\x10randomizeMetrics\x12+\n" +
	"\x11prevent_detection\x18\t \x01(\bR\x10preventDetection\"\xfd\x03\n" +
	"\x14CustomProfileOptions\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\tR\tuserAgent\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12!\n" +
	"\fscreen_width\x18\x03 \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\x04 \x01(\x05R\fscreenHeight\x12,\n" +
	"\x12device_pixel_ratio\x18\x05 \x01(\x01R\x10devicePixelRatio\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\x05R\bcpuCores\x12#\n" +
	"\rdevice_memory\x18\a \x01(\x05R\fdeviceMemory\x12\x16\n" +
	"\x06locale\x18\b \x01(\tR\x06locale\x12\x1c\n" +
	"\tlanguages\x18\t \x03(\tR\tlanguages\x12\x1a\n" +
	"\btimezone\x18\n" +
	" \x01(\tR\btimezone\x12!\n" +
	"\fwebgl_vendor\x18\v \x01(\tR\vwebglVendor\x12%\n" +
	"\x0ewebgl_renderer\x18\f \x01(\tR\rwebglRenderer\x12)\n" +
	"\x10navigator_vendor\x18\r \x01(\tR\x0fnavigatorVendor\x12+\n" +
	"\x11navigator_product\x18\x0e \x01(\tR\x10navigatorProduct\"z\n" +
	"\x13ApplyProfileRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12+\n" +
	"\x11override_existing\x18\x03 \x01(\bR\x10overrideExisting\"\x91\x01\n" +
	"\x14ApplyProfileResponse\x12=\n" +
	"\x06result\x18\x01 \x01(\v2#.chaser.oxide.v1.ApplyProfileResultH\x00R\x06result\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.chaser.oxide.v1.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x91\x01\n" +
	"\x12ApplyProfileResult\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12)\n" +
	"\x10applied_features\x18\x04 \x03(\tR\x0fappliedFeatures\"E\n" +
	"\x11GetPresetsRequest\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.chaser.oxide.v1.ProfileTypeR\x04type\"\x8d\x01\n" +
	"\x12GetPresetsResponse\x12;\n" +
	"\apresets\x18\x01 \x01(\v2\x1f.chaser.oxide.v1.PresetProfilesH\x00R\apresets\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.chaser.oxide.v1.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"D\n" +
	"\x0ePresetProfiles\x122\n" +
	"\apresets\x18\x01 \x03(\v2\x18.chaser.oxide.v1.ProfileR\apresets\"2\n" +
	"\x17GetActiveProfileRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"\x8c\x01\n" +
	"\x18GetActiveProfileResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.chaser.oxide.v1.ProfileH\x00R\aprofile\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.chaser.oxide.v1.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x84\x02\n" +
	"\x1aCreateCustomProfileRequest\x12!\n" +
	"\fprofile_name\x18\x01 \x01(\tR\vprofileName\x128\n" +
	"\btemplate\x18\x02 \x01(\x0e2\x1c.chaser.oxide.v1.ProfileTypeR\btemplate\x12?\n" +
	"\aoptions\x18\x03 \x01(\v2%.chaser.oxide.v1.CustomProfileOptionsR\aoptions\x12H\n" +
	"\x0fprofile_options\x18\x04 \x01(\v2\x1f.chaser.oxide.v1.ProfileOptionsR\x0eprofileOptions\"\x8f\x01\n" +
	"\x1bCreateCustomProfileResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.chaser.oxide.v1.ProfileH\x00R\aprofile\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.chaser.oxide.v1.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x8c\x01\n" +
	"\x17RandomizeProfileRequest\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.chaser.oxide.v1.ProfileTypeR\x04type\x12?\n" +
	"\aoptions\x18\x02 \x01(\v2%.chaser.oxide.v1.RandomizationOptionsR\aoptions\"\xe2\x01\n" +
	"\x14RandomizationOptions\x12)\n" +
	"\x10randomize_screen\x18\x01 \x01(\bR\x0frandomizeScreen\x12-\n" +
	"\x12randomize_timezone\x18\x02 \x01(\bR\x11randomizeTimezone\x12-\n" +
	"\x12randomize_language\x18\x03 \x01(\bR\x11randomizeLanguage\x12'\n" +
	"\x0frandomize_webgl\x18\x04 \x01(\bR\x0erandomizeWebgl\x12\x18\n" +
	"\aentropy\x18\x05 \x01(\x01R\aentropy\"\x8c\x01\n" +
	"\x18RandomizeProfileResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.chaser.oxide.v1.ProfileH\x00R\aprofile\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.chaser.oxide.v1.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse*\xbe\x01\n" +
	"\vProfileType\x12\x1c\n" +
	"\x18PROFILE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROFILE_TYPE_WINDOWS\x10\x01\x12\x16\n" +
	"\x12PROFILE_TYPE_LINUX\x10\x02\x12\x16\n" +
	"\x12PROFILE_TYPE_MACOS\x10\x03\x12\x18\n" +
	"\x14PROFILE_TYPE_ANDROID\x10\x04\x12\x14\n" +
	"\x10PROFILE_TYPE_IOS\x10\x05\x12\x17\n" +
	"\x13PROFILE_TYPE_CUSTOM\x10\x062\xe8\x04\n" +
	"\x0eProfileService\x12^\n" +
	"\rCreateProfile\x12%.chaser.oxide.v1.CreateProfileRequest\x1a&.chaser.oxide.v1.CreateProfileResponse\x12[\n" +
	"\fApplyProfile\x12$.chaser.oxide.v1.ApplyProfileRequest\x1a%.chaser.oxide.v1.ApplyProfileResponse\x12U\n" +
	"\n" +
	"GetPresets\x12\".chaser.oxide.v1.GetPresetsRequest\x1a#.chaser.oxide.v1.GetPresetsResponse\x12g\n" +
	"\x10GetActiveProfile\x12(.chaser.oxide.v1.GetActiveProfileRequest\x1a).chaser.oxide.v1.GetActiveProfileResponse\x12p\n" +
	"\x13CreateCustomProfile\x12+.chaser.oxide.v1.CreateCustomProfileRequest\x1a,.chaser.oxide.v1.CreateCustomProfileResponse\x12g\n" +
	"\x10RandomizeProfile\x12(.chaser.oxide.v1.RandomizeProfileRequest\x1a).chaser.oxide.v1.RandomizeProfileResponseb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_profile_proto_goTypes = []any{
	(ProfileType)(0),                    // 0: chaser.oxide.v1.ProfileType
	(*CreateProfileRequest)(nil),        // 1: chaser.oxide.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),       // 2: chaser.oxide.v1.CreateProfileResponse
	(*Profile)(nil),                     // 3: chaser.oxide.v1.Profile
	(*Fingerprint)(nil),                 // 4: chaser.oxide.v1.Fingerprint
	(*HTTPHeaders)(nil),                 // 5: chaser.oxide.v1.HTTPHeaders
	(*NavigatorInfo)(nil),               // 6: chaser.oxide.v1.NavigatorInfo
	(*ScreenInfo)(nil),                  // 7: chaser.oxide.v1.ScreenInfo
	(*HardwareInfo)(nil),                // 8: chaser.oxide.v1.HardwareInfo
	(*WebGLInfo)(nil),                   // 9: chaser.oxide.v1.WebGLInfo
	(*AudioInfo)(nil),                   // 10: chaser.oxide.v1.AudioInfo
	(*CanvasInfo)(nil),                  // 11: chaser.oxide.v1.CanvasInfo
	(*Permissions)(nil),                 // 12: chaser.oxide.v1.Permissions
	(*ProfileOptions)(nil),              // 13: chaser.oxide.v1.ProfileOptions
	(*CustomProfileOptions)(nil),        // 14: chaser.oxide.v1.CustomProfileOptions
	(*ApplyProfileRequest)(nil),         // 15: chaser.oxide.v1.ApplyProfileRequest
	(*ApplyProfileResponse)(nil),        // 16: chaser.oxide.v1.ApplyProfileResponse
	(*ApplyProfileResult)(nil),          // 17: chaser.oxide.v1.ApplyProfileResult
	(*GetPresetsRequest)(nil),           // 18: chaser.oxide.v1.GetPresetsRequest
	(*GetPresetsResponse)(nil),          // 19: chaser.oxide.v1.GetPresetsResponse
	(*PresetProfiles)(nil),              // 20: chaser.oxide.v1.PresetProfiles
	(*GetActiveProfileRequest)(nil),     // 21: chaser.oxide.v1.GetActiveProfileRequest
	(*GetActiveProfileResponse)(nil),    // 22: chaser.oxide.v1.GetActiveProfileResponse
	(*CreateCustomProfileRequest)(nil),  // 23: chaser.oxide.v1.CreateCustomProfileRequest
	(*CreateCustomProfileResponse)(nil), // 24: chaser.oxide.v1.CreateCustomProfileResponse
	(*RandomizeProfileRequest)(nil),     // 25: chaser.oxide.v1.RandomizeProfileRequest
	(*RandomizationOptions)(nil),        // 26: chaser.oxide.v1.RandomizationOptions
	(*RandomizeProfileResponse)(nil),    // 27: chaser.oxide.v1.RandomizeProfileResponse
	(*Error)(nil),                       // 28: chaser.oxide.v1.Error
}
var file_profile_proto_depIdxs = []int32{
	0,  // 0: chaser.oxide.v1.CreateProfileRequest.type:type_name -> chaser.oxide.v1.ProfileType
	14, // 1: chaser.oxide.v1.CreateProfileRequest.custom:type_name -> chaser.oxide.v1.CustomProfileOptions
	3,  // 2: chaser.oxide.v1.CreateProfileResponse.profile:type_name -> chaser.oxide.v1.Profile
	28, // 3: chaser.oxide.v1.CreateProfileResponse.error:type_name -> chaser.oxide.v1.Error
	0,  // 4: chaser.oxide.v1.Profile.type:type_name -> chaser.oxide.v1.ProfileType
	4,  // 5: chaser.oxide.v1.Profile.fingerprint:type_name -> chaser.oxide.v1.Fingerprint
	13, // 6: chaser.oxide.v1.Profile.options:type_name -> chaser.oxide.v1.ProfileOptions
	5,  // 7: chaser.oxide.v1.Fingerprint.headers:type_name -> chaser.oxide.v1.HTTPHeaders
	6,  // 8: chaser.oxide.v1.Fingerprint.navigator:type_name -> chaser.oxide.v1.NavigatorInfo
	7,  // 9: chaser.oxide.v1.Fingerprint.screen:type_name -> chaser.oxide.v1.ScreenInfo
	8,  // 10: chaser.oxide.v1.Fingerprint.hardware:type_name -> chaser.oxide.v1.HardwareInfo
	9,  // 11: chaser.oxide.v1.Fingerprint.webgl:type_name -> chaser.oxide.v1.WebGLInfo
	10, // 12: chaser.oxide.v1.Fingerprint.audio:type_name -> chaser.oxide.v1.AudioInfo
	11, // 13: chaser.oxide.v1.Fingerprint.canvas:type_name -> chaser.oxide.v1.CanvasInfo
	12, // 14: chaser.oxide.v1.Fingerprint.permissions:type_name -> chaser.oxide.v1.Permissions
	17, // 15: chaser.oxide.v1.ApplyProfileResponse.result:type_name -> chaser.oxide.v1.ApplyProfileResult
	28, // 16: chaser.oxide.v1.ApplyProfileResponse.error:type_name -> chaser.oxide.v1.Error
	0,  // 17: chaser.oxide.v1.GetPresetsRequest.type:type_name -> chaser.oxide.v1.ProfileType
	20, // 18: chaser.oxide.v1.GetPresetsResponse.presets:type_name -> chaser.oxide.v1.PresetProfiles
	28, // 19: chaser.oxide.v1.GetPresetsResponse.error:type_name -> chaser.oxide.v1.Error
	3,  // 20: chaser.oxide.v1.PresetProfiles.presets:type_name -> chaser.oxide.v1.Profile
	3,  // 21: chaser.oxide.v1.GetActiveProfileResponse.profile:type_name -> chaser.oxide.v1.Profile
	28, // 22: chaser.oxide.v1.GetActiveProfileResponse.error:type_name -> chaser.oxide.v1.Error
	0,  // 23: chaser.oxide.v1.CreateCustomProfileRequest.template:type_name -> chaser.oxide.v1.ProfileType
	14, // 24: chaser.oxide.v1.CreateCustomProfileRequest.options:type_name -> chaser.oxide.v1.CustomProfileOptions
	13, // 25: chaser.oxide.v1.CreateCustomProfileRequest.profile_options:type_name -> chaser.oxide.v1.ProfileOptions
	3,  // 26: chaser.oxide.v1.CreateCustomProfileResponse.profile:type_name -> chaser.oxide.v1.Profile
	28, // 27: chaser.oxide.v1.CreateCustomProfileResponse.error:type_name -> chaser.oxide.v1.Error
	0,  // 28: chaser.oxide.v1.RandomizeProfileRequest.type:type_name -> chaser.oxide.v1.ProfileType
	26, // 29: chaser.oxide.v1.RandomizeProfileRequest.options:type_name -> chaser.oxide.v1.RandomizationOptions
	3,  // 30: chaser.oxide.v1.RandomizeProfileResponse.profile:type_name -> chaser.oxide.v1.Profile
	28, // 31: chaser.oxide.v1.RandomizeProfileResponse.error:type_name -> chaser.oxide.v1.Error
	1,  // 32: chaser.oxide.v1.ProfileService.CreateProfile:input_type -> chaser.oxide.v1.CreateProfileRequest
	15, // 33: chaser.oxide.v1.ProfileService.ApplyProfile:input_type -> chaser.oxide.v1.ApplyProfileRequest
	18, // 34: chaser.oxide.v1.ProfileService.GetPresets:input_type -> chaser.oxide.v1.GetPresetsRequest
	21, // 35: chaser.oxide.v1.ProfileService.GetActiveProfile:input_type -> chaser.oxide.v1.GetActiveProfileRequest
	23, // 36: chaser.oxide.v1.ProfileService.CreateCustomProfile:input_type -> chaser.oxide.v1.CreateCustomProfileRequest
	25, // 37: chaser.oxide.v1.ProfileService.RandomizeProfile:input_type -> chaser.oxide.v1.RandomizeProfileRequest
	2,  // 38: chaser.oxide.v1.ProfileService.CreateProfile:output_type -> chaser.oxide.v1.CreateProfileResponse
	16, // 39: chaser.oxide.v1.ProfileService.ApplyProfile:output_type -> chaser.oxide.v1.ApplyProfileResponse
	19, // 40: chaser.oxide.v1.ProfileService.GetPresets:output_type -> chaser.oxide.v1.GetPresetsResponse
	22, // 41: chaser.oxide.v1.ProfileService.GetActiveProfile:output_type -> chaser.oxide.v1.GetActiveProfileResponse
	24, // 42: chaser.oxide.v1.ProfileService.CreateCustomProfile:output_type -> chaser.oxide.v1.CreateCustomProfileResponse
	27, // 43: chaser.oxide.v1.ProfileService.RandomizeProfile:output_type -> chaser.oxide.v1.RandomizeProfileResponse
	38, // [38:44] is the sub-list for method output_type
	32, // [32:38] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	file_common_proto_init()
	file_profile_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateProfileResponse_Profile)(nil),
		(*CreateProfileResponse_Error)(nil),
	}
	file_profile_proto_msgTypes[15].OneofWrappers = []any{
		(*ApplyProfileResponse_Result)(nil),
		(*ApplyProfileResponse_Error)(nil),
	}
	file_profile_proto_msgTypes[18].OneofWrappers = []any{
		(*GetPresetsResponse_Presets)(nil),
		(*GetPresetsResponse_Error)(nil),
	}
	file_profile_proto_msgTypes[21].OneofWrappers = []any{
		(*GetActiveProfileResponse_Profile)(nil),
		(*GetActiveProfileResponse_Error)(nil),
	}
	file_profile_proto_msgTypes[23].OneofWrappers = []any{
		(*CreateCustomProfileResponse_Profile)(nil),
		(*CreateCustomProfileResponse_Error)(nil),
	}
	file_profile_proto_msgTypes[26].OneofWrappers = []any{
		(*RandomizeProfileResponse_Profile)(nil),
		(*RandomizeProfileResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		EnumInfos:         file_profile_proto_enumTypes,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
