# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import profile_pb2 as profile__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfileServiceStub(object):
    """============= ProfileService =============
    Manages browser fingerprint profiles for anti-detection
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProfile = channel.unary_unary(
                '/chaser.oxide.v1.ProfileService/CreateProfile',
                request_serializer=profile__pb2.CreateProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.CreateProfileResponse.FromString,
                _registered_method=True)
        self.ApplyProfile = channel.unary_unary(
                '/chaser.oxide.v1.ProfileService/ApplyProfile',
                request_serializer=profile__pb2.ApplyProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.ApplyProfileResponse.FromString,
                _registered_method=True)
        self.GetPresets = channel.unary_unary(
                '/chaser.oxide.v1.ProfileService/GetPresets',
                request_serializer=profile__pb2.GetPresetsRequest.SerializeToString,
                response_deserializer=profile__pb2.GetPresetsResponse.FromString,
                _registered_method=True)
        self.GetActiveProfile = channel.unary_unary(
                '/chaser.oxide.v1.ProfileService/GetActiveProfile',
                request_serializer=profile__pb2.GetActiveProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.GetActiveProfileResponse.FromString,
                _registered_method=True)
        self.CreateCustomProfile = channel.unary_unary(
                '/chaser.oxide.v1.ProfileService/CreateCustomProfile',
                request_serializer=profile__pb2.CreateCustomProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.CreateCustomProfileResponse.FromString,
                _registered_method=True)
        self.RandomizeProfile = channel.unary_unary(
                '/chaser.oxide.v1.ProfileService/RandomizeProfile',
                request_serializer=profile__pb2.RandomizeProfileRequest.SerializeToString,
                response_deserializer=profile__pb2.RandomizeProfileResponse.FromString,
                _registered_method=True)


class ProfileServiceServicer(object):
    """============= ProfileService =============
    Manages browser fingerprint profiles for anti-detection
    """

    def CreateProfile(self, request, context):
        """Create a new fingerprint profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyProfile(self, request, context):
        """Apply a profile to a page
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresets(self, request, context):
        """Get predefined/preset profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveProfile(self, request, context):
        """Get active profile for a page
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomProfile(self, request, context):
        """Create custom profile from template
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RandomizeProfile(self, request, context):
        """Randomize profile for uniqueness
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfile,
                    request_deserializer=profile__pb2.CreateProfileRequest.FromString,
                    response_serializer=profile__pb2.CreateProfileResponse.SerializeToString,
            ),
            'ApplyProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyProfile,
                    request_deserializer=profile__pb2.ApplyProfileRequest.FromString,
                    response_serializer=profile__pb2.ApplyProfileResponse.SerializeToString,
            ),
            'GetPresets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresets,
                    request_deserializer=profile__pb2.GetPresetsRequest.FromString,
                    response_serializer=profile__pb2.GetPresetsResponse.SerializeToString,
            ),
            'GetActiveProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveProfile,
                    request_deserializer=profile__pb2.GetActiveProfileRequest.FromString,
                    response_serializer=profile__pb2.GetActiveProfileResponse.SerializeToString,
            ),
            'CreateCustomProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomProfile,
                    request_deserializer=profile__pb2.CreateCustomProfileRequest.FromString,
                    response_serializer=profile__pb2.CreateCustomProfileResponse.SerializeToString,
            ),
            'RandomizeProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.RandomizeProfile,
                    request_deserializer=profile__pb2.RandomizeProfileRequest.FromString,
                    response_serializer=profile__pb2.RandomizeProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chaser.oxide.v1.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chaser.oxide.v1.ProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """============= ProfileService =============
    Manages browser fingerprint profiles for anti-detection
    """

    @staticmethod
    def CreateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ProfileService/CreateProfile',
            profile__pb2.CreateProfileRequest.SerializeToString,
            profile__pb2.CreateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ProfileService/ApplyProfile',
            profile__pb2.ApplyProfileRequest.SerializeToString,
            profile__pb2.ApplyProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPresets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ProfileService/GetPresets',
            profile__pb2.GetPresetsRequest.SerializeToString,
            profile__pb2.GetPresetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ProfileService/GetActiveProfile',
            profile__pb2.GetActiveProfileRequest.SerializeToString,
            profile__pb2.GetActiveProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCustomProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ProfileService/CreateCustomProfile',
            profile__pb2.CreateCustomProfileRequest.SerializeToString,
            profile__pb2.CreateCustomProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RandomizeProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ProfileService/RandomizeProfile',
            profile__pb2.RandomizeProfileRequest.SerializeToString,
            profile__pb2.RandomizeProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
