# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chaser.oxide.v1 import element_pb2 as element__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in element_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ElementServiceStub(object):
    """============= ElementService =============
    Handles DOM element finding and interaction
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindElement = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/FindElement',
                request_serializer=element__pb2.FindElementRequest.SerializeToString,
                response_deserializer=element__pb2.FindElementResponse.FromString,
                _registered_method=True)
        self.FindElements = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/FindElements',
                request_serializer=element__pb2.FindElementsRequest.SerializeToString,
                response_deserializer=element__pb2.FindElementsResponse.FromString,
                _registered_method=True)
        self.Click = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/Click',
                request_serializer=element__pb2.ClickRequest.SerializeToString,
                response_deserializer=element__pb2.ClickResponse.FromString,
                _registered_method=True)
        self.Type = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/Type',
                request_serializer=element__pb2.TypeRequest.SerializeToString,
                response_deserializer=element__pb2.TypeResponse.FromString,
                _registered_method=True)
        self.Fill = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/Fill',
                request_serializer=element__pb2.FillRequest.SerializeToString,
                response_deserializer=element__pb2.FillResponse.FromString,
                _registered_method=True)
        self.GetAttribute = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/GetAttribute',
                request_serializer=element__pb2.GetAttributeRequest.SerializeToString,
                response_deserializer=element__pb2.GetAttributeResponse.FromString,
                _registered_method=True)
        self.GetAttributes = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/GetAttributes',
                request_serializer=element__pb2.GetAttributesRequest.SerializeToString,
                response_deserializer=element__pb2.GetAttributesResponse.FromString,
                _registered_method=True)
        self.GetText = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/GetText',
                request_serializer=element__pb2.GetTextRequest.SerializeToString,
                response_deserializer=element__pb2.GetTextResponse.FromString,
                _registered_method=True)
        self.GetHTML = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/GetHTML',
                request_serializer=element__pb2.GetHTMLRequest.SerializeToString,
                response_deserializer=element__pb2.GetHTMLResponse.FromString,
                _registered_method=True)
        self.Hover = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/Hover',
                request_serializer=element__pb2.HoverRequest.SerializeToString,
                response_deserializer=element__pb2.HoverResponse.FromString,
                _registered_method=True)
        self.Focus = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/Focus',
                request_serializer=element__pb2.FocusRequest.SerializeToString,
                response_deserializer=element__pb2.FocusResponse.FromString,
                _registered_method=True)
        self.SelectOption = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/SelectOption',
                request_serializer=element__pb2.SelectOptionRequest.SerializeToString,
                response_deserializer=element__pb2.SelectOptionResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/UploadFile',
                request_serializer=element__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=element__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.ScrollIntoView = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/ScrollIntoView',
                request_serializer=element__pb2.ScrollIntoViewRequest.SerializeToString,
                response_deserializer=element__pb2.ScrollIntoViewResponse.FromString,
                _registered_method=True)
        self.GetBoundingBox = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/GetBoundingBox',
                request_serializer=element__pb2.GetBoundingBoxRequest.SerializeToString,
                response_deserializer=element__pb2.GetBoundingBoxResponse.FromString,
                _registered_method=True)
        self.IsVisible = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/IsVisible',
                request_serializer=element__pb2.IsVisibleRequest.SerializeToString,
                response_deserializer=element__pb2.IsVisibleResponse.FromString,
                _registered_method=True)
        self.IsEnabled = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/IsEnabled',
                request_serializer=element__pb2.IsEnabledRequest.SerializeToString,
                response_deserializer=element__pb2.IsEnabledResponse.FromString,
                _registered_method=True)
        self.WaitForElement = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/WaitForElement',
                request_serializer=element__pb2.WaitForElementRequest.SerializeToString,
                response_deserializer=element__pb2.WaitForElementResponse.FromString,
                _registered_method=True)
        self.GetProperties = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/GetProperties',
                request_serializer=element__pb2.GetPropertiesRequest.SerializeToString,
                response_deserializer=element__pb2.GetPropertiesResponse.FromString,
                _registered_method=True)
        self.PressKey = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/PressKey',
                request_serializer=element__pb2.PressKeyRequest.SerializeToString,
                response_deserializer=element__pb2.PressKeyResponse.FromString,
                _registered_method=True)
        self.DragAndDrop = channel.unary_unary(
                '/chaser.oxide.v1.ElementService/DragAndDrop',
                request_serializer=element__pb2.DragAndDropRequest.SerializeToString,
                response_deserializer=element__pb2.DragAndDropResponse.FromString,
                _registered_method=True)


class ElementServiceServicer(object):
    """============= ElementService =============
    Handles DOM element finding and interaction
    """

    def FindElement(self, request, context):
        """Find a single element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindElements(self, request, context):
        """Find multiple elements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Click on an element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Type(self, request, context):
        """Type text into an element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fill(self, request, context):
        """Fill a form element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttribute(self, request, context):
        """Get element attribute
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributes(self, request, context):
        """Get multiple attributes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetText(self, request, context):
        """Get element text content
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHTML(self, request, context):
        """Get inner HTML
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hover(self, request, context):
        """Hover over an element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Focus(self, request, context):
        """Focus on an element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectOption(self, request, context):
        """Select option(s) from a dropdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request, context):
        """Upload file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScrollIntoView(self, request, context):
        """Scroll element into view
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBoundingBox(self, request, context):
        """Get element bounding box
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsVisible(self, request, context):
        """Check if element is visible
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsEnabled(self, request, context):
        """Check if element is enabled
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForElement(self, request, context):
        """Wait for element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperties(self, request, context):
        """Get element properties
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PressKey(self, request, context):
        """Press key on element
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DragAndDrop(self, request, context):
        """Drag and drop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindElement': grpc.unary_unary_rpc_method_handler(
                    servicer.FindElement,
                    request_deserializer=element__pb2.FindElementRequest.FromString,
                    response_serializer=element__pb2.FindElementResponse.SerializeToString,
            ),
            'FindElements': grpc.unary_unary_rpc_method_handler(
                    servicer.FindElements,
                    request_deserializer=element__pb2.FindElementsRequest.FromString,
                    response_serializer=element__pb2.FindElementsResponse.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=element__pb2.ClickRequest.FromString,
                    response_serializer=element__pb2.ClickResponse.SerializeToString,
            ),
            'Type': grpc.unary_unary_rpc_method_handler(
                    servicer.Type,
                    request_deserializer=element__pb2.TypeRequest.FromString,
                    response_serializer=element__pb2.TypeResponse.SerializeToString,
            ),
            'Fill': grpc.unary_unary_rpc_method_handler(
                    servicer.Fill,
                    request_deserializer=element__pb2.FillRequest.FromString,
                    response_serializer=element__pb2.FillResponse.SerializeToString,
            ),
            'GetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttribute,
                    request_deserializer=element__pb2.GetAttributeRequest.FromString,
                    response_serializer=element__pb2.GetAttributeResponse.SerializeToString,
            ),
            'GetAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributes,
                    request_deserializer=element__pb2.GetAttributesRequest.FromString,
                    response_serializer=element__pb2.GetAttributesResponse.SerializeToString,
            ),
            'GetText': grpc.unary_unary_rpc_method_handler(
                    servicer.GetText,
                    request_deserializer=element__pb2.GetTextRequest.FromString,
                    response_serializer=element__pb2.GetTextResponse.SerializeToString,
            ),
            'GetHTML': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHTML,
                    request_deserializer=element__pb2.GetHTMLRequest.FromString,
                    response_serializer=element__pb2.GetHTMLResponse.SerializeToString,
            ),
            'Hover': grpc.unary_unary_rpc_method_handler(
                    servicer.Hover,
                    request_deserializer=element__pb2.HoverRequest.FromString,
                    response_serializer=element__pb2.HoverResponse.SerializeToString,
            ),
            'Focus': grpc.unary_unary_rpc_method_handler(
                    servicer.Focus,
                    request_deserializer=element__pb2.FocusRequest.FromString,
                    response_serializer=element__pb2.FocusResponse.SerializeToString,
            ),
            'SelectOption': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectOption,
                    request_deserializer=element__pb2.SelectOptionRequest.FromString,
                    response_serializer=element__pb2.SelectOptionResponse.SerializeToString,
            ),
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=element__pb2.UploadFileRequest.FromString,
                    response_serializer=element__pb2.UploadFileResponse.SerializeToString,
            ),
            'ScrollIntoView': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrollIntoView,
                    request_deserializer=element__pb2.ScrollIntoViewRequest.FromString,
                    response_serializer=element__pb2.ScrollIntoViewResponse.SerializeToString,
            ),
            'GetBoundingBox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBoundingBox,
                    request_deserializer=element__pb2.GetBoundingBoxRequest.FromString,
                    response_serializer=element__pb2.GetBoundingBoxResponse.SerializeToString,
            ),
            'IsVisible': grpc.unary_unary_rpc_method_handler(
                    servicer.IsVisible,
                    request_deserializer=element__pb2.IsVisibleRequest.FromString,
                    response_serializer=element__pb2.IsVisibleResponse.SerializeToString,
            ),
            'IsEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.IsEnabled,
                    request_deserializer=element__pb2.IsEnabledRequest.FromString,
                    response_serializer=element__pb2.IsEnabledResponse.SerializeToString,
            ),
            'WaitForElement': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitForElement,
                    request_deserializer=element__pb2.WaitForElementRequest.FromString,
                    response_serializer=element__pb2.WaitForElementResponse.SerializeToString,
            ),
            'GetProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperties,
                    request_deserializer=element__pb2.GetPropertiesRequest.FromString,
                    response_serializer=element__pb2.GetPropertiesResponse.SerializeToString,
            ),
            'PressKey': grpc.unary_unary_rpc_method_handler(
                    servicer.PressKey,
                    request_deserializer=element__pb2.PressKeyRequest.FromString,
                    response_serializer=element__pb2.PressKeyResponse.SerializeToString,
            ),
            'DragAndDrop': grpc.unary_unary_rpc_method_handler(
                    servicer.DragAndDrop,
                    request_deserializer=element__pb2.DragAndDropRequest.FromString,
                    response_serializer=element__pb2.DragAndDropResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chaser.oxide.v1.ElementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chaser.oxide.v1.ElementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ElementService(object):
    """============= ElementService =============
    Handles DOM element finding and interaction
    """

    @staticmethod
    def FindElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/FindElement',
            element__pb2.FindElementRequest.SerializeToString,
            element__pb2.FindElementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/FindElements',
            element__pb2.FindElementsRequest.SerializeToString,
            element__pb2.FindElementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/Click',
            element__pb2.ClickRequest.SerializeToString,
            element__pb2.ClickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Type(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/Type',
            element__pb2.TypeRequest.SerializeToString,
            element__pb2.TypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/Fill',
            element__pb2.FillRequest.SerializeToString,
            element__pb2.FillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/GetAttribute',
            element__pb2.GetAttributeRequest.SerializeToString,
            element__pb2.GetAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/GetAttributes',
            element__pb2.GetAttributesRequest.SerializeToString,
            element__pb2.GetAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/GetText',
            element__pb2.GetTextRequest.SerializeToString,
            element__pb2.GetTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHTML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/GetHTML',
            element__pb2.GetHTMLRequest.SerializeToString,
            element__pb2.GetHTMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/Hover',
            element__pb2.HoverRequest.SerializeToString,
            element__pb2.HoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Focus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/Focus',
            element__pb2.FocusRequest.SerializeToString,
            element__pb2.FocusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/SelectOption',
            element__pb2.SelectOptionRequest.SerializeToString,
            element__pb2.SelectOptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/UploadFile',
            element__pb2.UploadFileRequest.SerializeToString,
            element__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScrollIntoView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/ScrollIntoView',
            element__pb2.ScrollIntoViewRequest.SerializeToString,
            element__pb2.ScrollIntoViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBoundingBox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/GetBoundingBox',
            element__pb2.GetBoundingBoxRequest.SerializeToString,
            element__pb2.GetBoundingBoxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsVisible(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/IsVisible',
            element__pb2.IsVisibleRequest.SerializeToString,
            element__pb2.IsVisibleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/IsEnabled',
            element__pb2.IsEnabledRequest.SerializeToString,
            element__pb2.IsEnabledResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/WaitForElement',
            element__pb2.WaitForElementRequest.SerializeToString,
            element__pb2.WaitForElementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/GetProperties',
            element__pb2.GetPropertiesRequest.SerializeToString,
            element__pb2.GetPropertiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PressKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/PressKey',
            element__pb2.PressKeyRequest.SerializeToString,
            element__pb2.PressKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DragAndDrop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chaser.oxide.v1.ElementService/DragAndDrop',
            element__pb2.DragAndDropRequest.SerializeToString,
            element__pb2.DragAndDropResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
